//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/events/ConnectingStateChanged.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEventsConnectingStateChanged")
#ifdef RESTRICT_ImActorCoreEventsConnectingStateChanged
#define INCLUDE_ALL_ImActorCoreEventsConnectingStateChanged 0
#else
#define INCLUDE_ALL_ImActorCoreEventsConnectingStateChanged 1
#endif
#undef RESTRICT_ImActorCoreEventsConnectingStateChanged

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreEventsConnectingStateChanged_) && (INCLUDE_ALL_ImActorCoreEventsConnectingStateChanged || defined(INCLUDE_ImActorCoreEventsConnectingStateChanged))
#define ImActorCoreEventsConnectingStateChanged_

#define RESTRICT_ImActorRuntimeEventbusEvent 1
#define INCLUDE_ImActorRuntimeEventbusEvent 1
#include "../../../../im/actor/runtime/eventbus/Event.h"

@interface ImActorCoreEventsConnectingStateChanged : ImActorRuntimeEventbusEvent

+ (NSString *)EVENT;

#pragma mark Public

- (instancetype)initWithBoolean:(jboolean)isConnecting;

- (NSString *)getType;

- (jboolean)isConnecting;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreEventsConnectingStateChanged)

inline NSString *ImActorCoreEventsConnectingStateChanged_get_EVENT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ImActorCoreEventsConnectingStateChanged_EVENT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ImActorCoreEventsConnectingStateChanged, EVENT, NSString *)

FOUNDATION_EXPORT void ImActorCoreEventsConnectingStateChanged_initWithBoolean_(ImActorCoreEventsConnectingStateChanged *self, jboolean isConnecting);

FOUNDATION_EXPORT ImActorCoreEventsConnectingStateChanged *new_ImActorCoreEventsConnectingStateChanged_initWithBoolean_(jboolean isConnecting) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreEventsConnectingStateChanged *create_ImActorCoreEventsConnectingStateChanged_initWithBoolean_(jboolean isConnecting);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreEventsConnectingStateChanged)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEventsConnectingStateChanged")
