//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/events/UserVisible.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEventsUserVisible")
#ifdef RESTRICT_ImActorCoreEventsUserVisible
#define INCLUDE_ALL_ImActorCoreEventsUserVisible 0
#else
#define INCLUDE_ALL_ImActorCoreEventsUserVisible 1
#endif
#undef RESTRICT_ImActorCoreEventsUserVisible

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreEventsUserVisible_) && (INCLUDE_ALL_ImActorCoreEventsUserVisible || defined(INCLUDE_ImActorCoreEventsUserVisible))
#define ImActorCoreEventsUserVisible_

#define RESTRICT_ImActorRuntimeEventbusEvent 1
#define INCLUDE_ImActorRuntimeEventbusEvent 1
#include "../../../../im/actor/runtime/eventbus/Event.h"

@interface ImActorCoreEventsUserVisible : ImActorRuntimeEventbusEvent

+ (NSString *)EVENT;

#pragma mark Public

- (instancetype)initWithInt:(jint)uid;

- (NSString *)getType;

- (jint)getUid;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreEventsUserVisible)

inline NSString *ImActorCoreEventsUserVisible_get_EVENT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ImActorCoreEventsUserVisible_EVENT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ImActorCoreEventsUserVisible, EVENT, NSString *)

FOUNDATION_EXPORT void ImActorCoreEventsUserVisible_initWithInt_(ImActorCoreEventsUserVisible *self, jint uid);

FOUNDATION_EXPORT ImActorCoreEventsUserVisible *new_ImActorCoreEventsUserVisible_initWithInt_(jint uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreEventsUserVisible *create_ImActorCoreEventsUserVisible_initWithInt_(jint uid);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreEventsUserVisible)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEventsUserVisible")
