//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/network/TrustedKey.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreNetworkTrustedKey")
#ifdef RESTRICT_ImActorCoreNetworkTrustedKey
#define INCLUDE_ALL_ImActorCoreNetworkTrustedKey 0
#else
#define INCLUDE_ALL_ImActorCoreNetworkTrustedKey 1
#endif
#undef RESTRICT_ImActorCoreNetworkTrustedKey

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACTrustedKey_) && (INCLUDE_ALL_ImActorCoreNetworkTrustedKey || defined(INCLUDE_ACTrustedKey))
#define ACTrustedKey_

@class IOSByteArray;

@interface ACTrustedKey : NSObject

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)key;

- (IOSByteArray *)getKey;

- (jlong)getKeyId;

@end

J2OBJC_EMPTY_STATIC_INIT(ACTrustedKey)

FOUNDATION_EXPORT void ACTrustedKey_initWithByteArray_(ACTrustedKey *self, IOSByteArray *key);

FOUNDATION_EXPORT ACTrustedKey *new_ACTrustedKey_initWithByteArray_(IOSByteArray *key) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACTrustedKey *create_ACTrustedKey_initWithByteArray_(IOSByteArray *key);

J2OBJC_TYPE_LITERAL_HEADER(ACTrustedKey)

@compatibility_alias ImActorCoreNetworkTrustedKey ACTrustedKey;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreNetworkTrustedKey")
