//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/webrtc/WebRTCFeatures.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeWebrtcWebRTCFeatures")
#ifdef RESTRICT_ImActorRuntimeWebrtcWebRTCFeatures
#define INCLUDE_ALL_ImActorRuntimeWebrtcWebRTCFeatures 0
#else
#define INCLUDE_ALL_ImActorRuntimeWebrtcWebRTCFeatures 1
#endif
#undef RESTRICT_ImActorRuntimeWebrtcWebRTCFeatures

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARWebRTCFeatures_) && (INCLUDE_ALL_ImActorRuntimeWebrtcWebRTCFeatures || defined(INCLUDE_ARWebRTCFeatures))
#define ARWebRTCFeatures_

/*!
 @brief WebRTC Features
 */
@interface ARWebRTCFeatures : NSObject
@property (nonatomic, getter=is3DESSupported) jboolean is3DESSupported;

#pragma mark Public

- (instancetype)init;

/*!
 @brief If 3DES supported
 @return is 3DES supported
 */
- (jboolean)is3DESSupported;

/*!
 @brief Setting 3DES support flag
 @param is3DESSupported set if 3DES supported
 */
- (void)setIs3DESSupportedWithBoolean:(jboolean)is3DESSupported;

@end

J2OBJC_EMPTY_STATIC_INIT(ARWebRTCFeatures)

FOUNDATION_EXPORT void ARWebRTCFeatures_init(ARWebRTCFeatures *self);

FOUNDATION_EXPORT ARWebRTCFeatures *new_ARWebRTCFeatures_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARWebRTCFeatures *create_ARWebRTCFeatures_init();

J2OBJC_TYPE_LITERAL_HEADER(ARWebRTCFeatures)

@compatibility_alias ImActorRuntimeWebrtcWebRTCFeatures ARWebRTCFeatures;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeWebrtcWebRTCFeatures")
