//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/updates/UpdateUserLastSeen.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdateUserLastSeen")
#ifdef RESTRICT_ImActorCoreApiUpdatesUpdateUserLastSeen
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdateUserLastSeen 0
#else
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdateUserLastSeen 1
#endif
#undef RESTRICT_ImActorCoreApiUpdatesUpdateUserLastSeen

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdateUserLastSeen_) && (INCLUDE_ALL_ImActorCoreApiUpdatesUpdateUserLastSeen || defined(INCLUDE_ARUpdateUserLastSeen))
#define ARUpdateUserLastSeen_

#define RESTRICT_ImActorCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/actor/core/network/parser/Update.h"

@class ARApiDeviceType;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARUpdateUserLastSeen : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)uid
                   withLong:(jlong)date
        withARApiDeviceType:(ARApiDeviceType * __nullable)deviceType
               withNSString:(NSString * __nullable)deviceCategory;

+ (ARUpdateUserLastSeen *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jlong)getDate;

- (NSString * __nullable)getDeviceCategory;

- (ARApiDeviceType * __nullable)getDeviceType;

- (jint)getHeaderKey;

- (jint)getUid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateUserLastSeen)

inline jint ARUpdateUserLastSeen_get_HEADER();
#define ARUpdateUserLastSeen_HEADER 9
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdateUserLastSeen, HEADER, jint)

FOUNDATION_EXPORT ARUpdateUserLastSeen *ARUpdateUserLastSeen_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateUserLastSeen_initWithInt_withLong_withARApiDeviceType_withNSString_(ARUpdateUserLastSeen *self, jint uid, jlong date, ARApiDeviceType *deviceType, NSString *deviceCategory);

FOUNDATION_EXPORT ARUpdateUserLastSeen *new_ARUpdateUserLastSeen_initWithInt_withLong_withARApiDeviceType_withNSString_(jint uid, jlong date, ARApiDeviceType *deviceType, NSString *deviceCategory) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateUserLastSeen *create_ARUpdateUserLastSeen_initWithInt_withLong_withARApiDeviceType_withNSString_(jint uid, jlong date, ARApiDeviceType *deviceType, NSString *deviceCategory);

FOUNDATION_EXPORT void ARUpdateUserLastSeen_init(ARUpdateUserLastSeen *self);

FOUNDATION_EXPORT ARUpdateUserLastSeen *new_ARUpdateUserLastSeen_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateUserLastSeen *create_ARUpdateUserLastSeen_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateUserLastSeen)

@compatibility_alias ImActorCoreApiUpdatesUpdateUserLastSeen ARUpdateUserLastSeen;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdateUserLastSeen")
