//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/updates/UpdateTyping.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdateTyping")
#ifdef RESTRICT_ImActorCoreApiUpdatesUpdateTyping
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdateTyping 0
#else
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdateTyping 1
#endif
#undef RESTRICT_ImActorCoreApiUpdatesUpdateTyping

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdateTyping_) && (INCLUDE_ALL_ImActorCoreApiUpdatesUpdateTyping || defined(INCLUDE_ARUpdateTyping))
#define ARUpdateTyping_

#define RESTRICT_ImActorCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/actor/core/network/parser/Update.h"

@class ARApiPeer;
@class ARApiTypingType;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARUpdateTyping : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiPeer:(ARApiPeer * __nonnull)peer
                          withInt:(jint)uid
              withARApiTypingType:(ARApiTypingType * __nonnull)typingType;

+ (ARUpdateTyping *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (ARApiPeer * __nonnull)getPeer;

- (ARApiTypingType * __nonnull)getTypingType;

- (jint)getUid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateTyping)

inline jint ARUpdateTyping_get_HEADER();
#define ARUpdateTyping_HEADER 6
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdateTyping, HEADER, jint)

FOUNDATION_EXPORT ARUpdateTyping *ARUpdateTyping_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateTyping_initWithARApiPeer_withInt_withARApiTypingType_(ARUpdateTyping *self, ARApiPeer *peer, jint uid, ARApiTypingType *typingType);

FOUNDATION_EXPORT ARUpdateTyping *new_ARUpdateTyping_initWithARApiPeer_withInt_withARApiTypingType_(ARApiPeer *peer, jint uid, ARApiTypingType *typingType) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateTyping *create_ARUpdateTyping_initWithARApiPeer_withInt_withARApiTypingType_(ARApiPeer *peer, jint uid, ARApiTypingType *typingType);

FOUNDATION_EXPORT void ARUpdateTyping_init(ARUpdateTyping *self);

FOUNDATION_EXPORT ARUpdateTyping *new_ARUpdateTyping_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateTyping *create_ARUpdateTyping_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateTyping)

@compatibility_alias ImActorCoreApiUpdatesUpdateTyping ARUpdateTyping;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdateTyping")
