//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/updates/UpdateGroupOnline.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdateGroupOnline")
#ifdef RESTRICT_ImActorCoreApiUpdatesUpdateGroupOnline
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdateGroupOnline 0
#else
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdateGroupOnline 1
#endif
#undef RESTRICT_ImActorCoreApiUpdatesUpdateGroupOnline

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdateGroupOnline_) && (INCLUDE_ALL_ImActorCoreApiUpdatesUpdateGroupOnline || defined(INCLUDE_ARUpdateGroupOnline))
#define ARUpdateGroupOnline_

#define RESTRICT_ImActorCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/actor/core/network/parser/Update.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARUpdateGroupOnline : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)groupId
                    withInt:(jint)count;

+ (ARUpdateGroupOnline *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getCount;

- (jint)getGroupId;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateGroupOnline)

inline jint ARUpdateGroupOnline_get_HEADER();
#define ARUpdateGroupOnline_HEADER 33
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdateGroupOnline, HEADER, jint)

FOUNDATION_EXPORT ARUpdateGroupOnline *ARUpdateGroupOnline_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateGroupOnline_initWithInt_withInt_(ARUpdateGroupOnline *self, jint groupId, jint count);

FOUNDATION_EXPORT ARUpdateGroupOnline *new_ARUpdateGroupOnline_initWithInt_withInt_(jint groupId, jint count) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateGroupOnline *create_ARUpdateGroupOnline_initWithInt_withInt_(jint groupId, jint count);

FOUNDATION_EXPORT void ARUpdateGroupOnline_init(ARUpdateGroupOnline *self);

FOUNDATION_EXPORT ARUpdateGroupOnline *new_ARUpdateGroupOnline_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateGroupOnline *create_ARUpdateGroupOnline_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateGroupOnline)

@compatibility_alias ImActorCoreApiUpdatesUpdateGroupOnline ARUpdateGroupOnline;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdateGroupOnline")
