//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/updates/UpdatePublicKeyGroupRemoved.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved")
#ifdef RESTRICT_ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved 0
#else
#define INCLUDE_ALL_ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved 1
#endif
#undef RESTRICT_ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdatePublicKeyGroupRemoved_) && (INCLUDE_ALL_ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved || defined(INCLUDE_ARUpdatePublicKeyGroupRemoved))
#define ARUpdatePublicKeyGroupRemoved_

#define RESTRICT_ImActorCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/actor/core/network/parser/Update.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARUpdatePublicKeyGroupRemoved : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)uid
                    withInt:(jint)keyGroupId;

+ (ARUpdatePublicKeyGroupRemoved *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (jint)getKeyGroupId;

- (jint)getUid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdatePublicKeyGroupRemoved)

inline jint ARUpdatePublicKeyGroupRemoved_get_HEADER();
#define ARUpdatePublicKeyGroupRemoved_HEADER 105
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdatePublicKeyGroupRemoved, HEADER, jint)

FOUNDATION_EXPORT ARUpdatePublicKeyGroupRemoved *ARUpdatePublicKeyGroupRemoved_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdatePublicKeyGroupRemoved_initWithInt_withInt_(ARUpdatePublicKeyGroupRemoved *self, jint uid, jint keyGroupId);

FOUNDATION_EXPORT ARUpdatePublicKeyGroupRemoved *new_ARUpdatePublicKeyGroupRemoved_initWithInt_withInt_(jint uid, jint keyGroupId) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdatePublicKeyGroupRemoved *create_ARUpdatePublicKeyGroupRemoved_initWithInt_withInt_(jint uid, jint keyGroupId);

FOUNDATION_EXPORT void ARUpdatePublicKeyGroupRemoved_init(ARUpdatePublicKeyGroupRemoved *self);

FOUNDATION_EXPORT ARUpdatePublicKeyGroupRemoved *new_ARUpdatePublicKeyGroupRemoved_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdatePublicKeyGroupRemoved *create_ARUpdatePublicKeyGroupRemoved_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdatePublicKeyGroupRemoved)

@compatibility_alias ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved ARUpdatePublicKeyGroupRemoved;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiUpdatesUpdatePublicKeyGroupRemoved")
