//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/HTTP.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeHTTP")
#ifdef RESTRICT_ImActorRuntimeHTTP
#define INCLUDE_ALL_ImActorRuntimeHTTP 0
#else
#define INCLUDE_ALL_ImActorRuntimeHTTP 1
#endif
#undef RESTRICT_ImActorRuntimeHTTP

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARHTTP_) && (INCLUDE_ALL_ImActorRuntimeHTTP || defined(INCLUDE_ARHTTP))
#define ARHTTP_

@class IOSByteArray;
@protocol ARFileDownloadCallback;
@protocol ARFileUploadCallback;

@interface ARHTTP : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)getMethodWithNSString:(NSString *)url
                      withInt:(jint)startOffset
                      withInt:(jint)size
                      withInt:(jint)totalSize
   withARFileDownloadCallback:(id<ARFileDownloadCallback>)callback;

+ (void)putMethodWithNSString:(NSString *)url
                withByteArray:(IOSByteArray *)contents
     withARFileUploadCallback:(id<ARFileUploadCallback>)callback;

@end

J2OBJC_STATIC_INIT(ARHTTP)

FOUNDATION_EXPORT void ARHTTP_getMethodWithNSString_withInt_withInt_withInt_withARFileDownloadCallback_(NSString *url, jint startOffset, jint size, jint totalSize, id<ARFileDownloadCallback> callback);

FOUNDATION_EXPORT void ARHTTP_putMethodWithNSString_withByteArray_withARFileUploadCallback_(NSString *url, IOSByteArray *contents, id<ARFileUploadCallback> callback);

FOUNDATION_EXPORT void ARHTTP_init(ARHTTP *self);

FOUNDATION_EXPORT ARHTTP *new_ARHTTP_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARHTTP *create_ARHTTP_init();

J2OBJC_TYPE_LITERAL_HEADER(ARHTTP)

@compatibility_alias ImActorRuntimeHTTP ARHTTP;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeHTTP")
