//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/actors/dispatch/queue/QueueCollectionListener.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueueCollectionListener")
#ifdef RESTRICT_ImActorRuntimeActorsDispatchQueueQueueCollectionListener
#define INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueueCollectionListener 0
#else
#define INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueueCollectionListener 1
#endif
#undef RESTRICT_ImActorRuntimeActorsDispatchQueueQueueCollectionListener

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeActorsDispatchQueueQueueCollectionListener_) && (INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueueCollectionListener || defined(INCLUDE_ImActorRuntimeActorsDispatchQueueQueueCollectionListener))
#define ImActorRuntimeActorsDispatchQueueQueueCollectionListener_

@protocol ImActorRuntimeActorsDispatchQueueQueueCollectionListener < NSObject, JavaObject >

- (void)onChanged;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeActorsDispatchQueueQueueCollectionListener)

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeActorsDispatchQueueQueueCollectionListener)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueueCollectionListener")
