//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/actors/dispatch/queue/Queue.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueue")
#ifdef RESTRICT_ImActorRuntimeActorsDispatchQueueQueue
#define INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueue 0
#else
#define INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueue 1
#endif
#undef RESTRICT_ImActorRuntimeActorsDispatchQueueQueue

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeActorsDispatchQueueQueue_) && (INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueue || defined(INCLUDE_ImActorRuntimeActorsDispatchQueueQueue))
#define ImActorRuntimeActorsDispatchQueueQueue_

@class JavaUtilLinkedList;

@interface ImActorRuntimeActorsDispatchQueueQueue : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)id_;

- (jint)getId;

- (JavaUtilLinkedList *)getQueue;

- (jboolean)isLocked;

- (void)setIsLockedWithBoolean:(jboolean)isLocked;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeActorsDispatchQueueQueue)

FOUNDATION_EXPORT void ImActorRuntimeActorsDispatchQueueQueue_initWithInt_(ImActorRuntimeActorsDispatchQueueQueue *self, jint id_);

FOUNDATION_EXPORT ImActorRuntimeActorsDispatchQueueQueue *new_ImActorRuntimeActorsDispatchQueueQueue_initWithInt_(jint id_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeActorsDispatchQueueQueue *create_ImActorRuntimeActorsDispatchQueueQueue_initWithInt_(jint id_);

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeActorsDispatchQueueQueue)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeActorsDispatchQueueQueue")
