//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/primitives/digest/KeyDigest.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestKeyDigest")
#ifdef RESTRICT_ImActorRuntimeCryptoPrimitivesDigestKeyDigest
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestKeyDigest 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestKeyDigest 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoPrimitivesDigestKeyDigest

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoPrimitivesDigestKeyDigest_) && (INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestKeyDigest || defined(INCLUDE_ImActorRuntimeCryptoPrimitivesDigestKeyDigest))
#define ImActorRuntimeCryptoPrimitivesDigestKeyDigest_

#define RESTRICT_ImActorRuntimeCryptoDigest 1
#define INCLUDE_ARDigest 1
#include "../../../../../../im/actor/runtime/crypto/Digest.h"

@class IOSByteArray;

/*!
 @brief Truncated SHA256 for public keys
 */
@interface ImActorRuntimeCryptoPrimitivesDigestKeyDigest : NSObject < ARDigest >

#pragma mark Public

- (instancetype)init;

- (void)doFinal:(IOSByteArray *)dest
     withOffset:(jint)destOffset;

- (jint)getDigestSize;

- (void)reset;

- (void)update:(IOSByteArray *)src
    withOffset:(jint)offset
    withLength:(jint)length;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoPrimitivesDigestKeyDigest)

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesDigestKeyDigest_init(ImActorRuntimeCryptoPrimitivesDigestKeyDigest *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesDigestKeyDigest *new_ImActorRuntimeCryptoPrimitivesDigestKeyDigest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesDigestKeyDigest *create_ImActorRuntimeCryptoPrimitivesDigestKeyDigest_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoPrimitivesDigestKeyDigest)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestKeyDigest")
