//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/primitives/digest/MD5.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestMD5")
#ifdef RESTRICT_ImActorRuntimeCryptoPrimitivesDigestMD5
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestMD5 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestMD5 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoPrimitivesDigestMD5

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoPrimitivesDigestMD5_) && (INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestMD5 || defined(INCLUDE_ImActorRuntimeCryptoPrimitivesDigestMD5))
#define ImActorRuntimeCryptoPrimitivesDigestMD5_

#define RESTRICT_ImActorRuntimeCryptoDigest 1
#define INCLUDE_ARDigest 1
#include "../../../../../../im/actor/runtime/crypto/Digest.h"

@class IOSByteArray;

@interface ImActorRuntimeCryptoPrimitivesDigestMD5 : NSObject < ARDigest >

#pragma mark Public

- (instancetype)init;

- (void)doFinal:(IOSByteArray *)dest
     withOffset:(jint)destOffset;

- (jint)getDigestSize;

- (void)reset;

- (void)update:(IOSByteArray *)src
    withOffset:(jint)offset
    withLength:(jint)length;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoPrimitivesDigestMD5)

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesDigestMD5_init(ImActorRuntimeCryptoPrimitivesDigestMD5 *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesDigestMD5 *new_ImActorRuntimeCryptoPrimitivesDigestMD5_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesDigestMD5 *create_ImActorRuntimeCryptoPrimitivesDigestMD5_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoPrimitivesDigestMD5)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesDigestMD5")
