//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-generic/src/main/java/im/actor/runtime/generic/network/AsyncTcpConnectionFactory.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory")
#ifdef RESTRICT_ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory
#define INCLUDE_ALL_ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory 0
#else
#define INCLUDE_ALL_ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory 1
#endif
#undef RESTRICT_ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARAsyncTcpConnectionFactory_) && (INCLUDE_ALL_ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory || defined(INCLUDE_ARAsyncTcpConnectionFactory))
#define ARAsyncTcpConnectionFactory_

#define RESTRICT_ImActorRuntimeMtprotoAsyncConnectionFactory 1
#define INCLUDE_ARAsyncConnectionFactory 1
#include "../../../../../im/actor/runtime/mtproto/AsyncConnectionFactory.h"

@class ARAsyncConnection;
@class ARConnectionEndpoint;
@protocol ARAsyncConnectionInterface;

@interface ARAsyncTcpConnectionFactory : NSObject < ARAsyncConnectionFactory >

#pragma mark Public

- (instancetype)init;

- (ARAsyncConnection *)createConnectionWithConnectionId:(jint)connectionId
                                           withEndpoint:(ARConnectionEndpoint *)endpoint
                                          withInterface:(id<ARAsyncConnectionInterface>)connectionInterface;

@end

J2OBJC_EMPTY_STATIC_INIT(ARAsyncTcpConnectionFactory)

FOUNDATION_EXPORT void ARAsyncTcpConnectionFactory_init(ARAsyncTcpConnectionFactory *self);

FOUNDATION_EXPORT ARAsyncTcpConnectionFactory *new_ARAsyncTcpConnectionFactory_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARAsyncTcpConnectionFactory *create_ARAsyncTcpConnectionFactory_init();

J2OBJC_TYPE_LITERAL_HEADER(ARAsyncTcpConnectionFactory)

@compatibility_alias ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory ARAsyncTcpConnectionFactory;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeGenericNetworkAsyncTcpConnectionFactory")
