//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/entity/signals/OfferSignal.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEntitySignalsOfferSignal")
#ifdef RESTRICT_ImActorCoreEntitySignalsOfferSignal
#define INCLUDE_ALL_ImActorCoreEntitySignalsOfferSignal 0
#else
#define INCLUDE_ALL_ImActorCoreEntitySignalsOfferSignal 1
#endif
#undef RESTRICT_ImActorCoreEntitySignalsOfferSignal

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreEntitySignalsOfferSignal_) && (INCLUDE_ALL_ImActorCoreEntitySignalsOfferSignal || defined(INCLUDE_ImActorCoreEntitySignalsOfferSignal))
#define ImActorCoreEntitySignalsOfferSignal_

#define RESTRICT_ImActorCoreEntitySignalsAbsSignal 1
#define INCLUDE_ImActorCoreEntitySignalsAbsSignal 1
#include "../../../../../im/actor/core/entity/signals/AbsSignal.h"

@class ARBserValues;
@class ARBserWriter;

@interface ImActorCoreEntitySignalsOfferSignal : ImActorCoreEntitySignalsAbsSignal

+ (NSString *)TYPE;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)sdp;

- (NSString *)getSdp;

- (NSString *)getType;

- (void)parseSignalWithARBserValues:(ARBserValues *)values;

- (void)serializeSignalWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreEntitySignalsOfferSignal)

inline NSString *ImActorCoreEntitySignalsOfferSignal_get_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ImActorCoreEntitySignalsOfferSignal_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ImActorCoreEntitySignalsOfferSignal, TYPE, NSString *)

FOUNDATION_EXPORT void ImActorCoreEntitySignalsOfferSignal_initWithNSString_(ImActorCoreEntitySignalsOfferSignal *self, NSString *sdp);

FOUNDATION_EXPORT ImActorCoreEntitySignalsOfferSignal *new_ImActorCoreEntitySignalsOfferSignal_initWithNSString_(NSString *sdp) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreEntitySignalsOfferSignal *create_ImActorCoreEntitySignalsOfferSignal_initWithNSString_(NSString *sdp);

FOUNDATION_EXPORT void ImActorCoreEntitySignalsOfferSignal_init(ImActorCoreEntitySignalsOfferSignal *self);

FOUNDATION_EXPORT ImActorCoreEntitySignalsOfferSignal *new_ImActorCoreEntitySignalsOfferSignal_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreEntitySignalsOfferSignal *create_ImActorCoreEntitySignalsOfferSignal_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreEntitySignalsOfferSignal)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEntitySignalsOfferSignal")
