//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/sequence/internal/GetDiffCombiner.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesSequenceInternalGetDiffCombiner")
#ifdef RESTRICT_ImActorCoreModulesSequenceInternalGetDiffCombiner
#define INCLUDE_ALL_ImActorCoreModulesSequenceInternalGetDiffCombiner 0
#else
#define INCLUDE_ALL_ImActorCoreModulesSequenceInternalGetDiffCombiner 1
#endif
#undef RESTRICT_ImActorCoreModulesSequenceInternalGetDiffCombiner

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesSequenceInternalGetDiffCombiner_) && (INCLUDE_ALL_ImActorCoreModulesSequenceInternalGetDiffCombiner || defined(INCLUDE_ImActorCoreModulesSequenceInternalGetDiffCombiner))
#define ImActorCoreModulesSequenceInternalGetDiffCombiner_

@class ImActorCoreModulesSequenceInternalCombinedDifference;
@protocol JavaUtilList;

@interface ImActorCoreModulesSequenceInternalGetDiffCombiner : NSObject

#pragma mark Public

- (instancetype)init;

+ (ImActorCoreModulesSequenceInternalCombinedDifference *)buildDiffWithJavaUtilList:(id<JavaUtilList>)updates;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesSequenceInternalGetDiffCombiner)

FOUNDATION_EXPORT ImActorCoreModulesSequenceInternalCombinedDifference *ImActorCoreModulesSequenceInternalGetDiffCombiner_buildDiffWithJavaUtilList_(id<JavaUtilList> updates);

FOUNDATION_EXPORT void ImActorCoreModulesSequenceInternalGetDiffCombiner_init(ImActorCoreModulesSequenceInternalGetDiffCombiner *self);

FOUNDATION_EXPORT ImActorCoreModulesSequenceInternalGetDiffCombiner *new_ImActorCoreModulesSequenceInternalGetDiffCombiner_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesSequenceInternalGetDiffCombiner *create_ImActorCoreModulesSequenceInternalGetDiffCombiner_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesSequenceInternalGetDiffCombiner)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesSequenceInternalGetDiffCombiner")
