//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/sequence/internal/HandlerRelatedResponse.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesSequenceInternalHandlerRelatedResponse")
#ifdef RESTRICT_ImActorCoreModulesSequenceInternalHandlerRelatedResponse
#define INCLUDE_ALL_ImActorCoreModulesSequenceInternalHandlerRelatedResponse 0
#else
#define INCLUDE_ALL_ImActorCoreModulesSequenceInternalHandlerRelatedResponse 1
#endif
#undef RESTRICT_ImActorCoreModulesSequenceInternalHandlerRelatedResponse

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesSequenceInternalHandlerRelatedResponse_) && (INCLUDE_ALL_ImActorCoreModulesSequenceInternalHandlerRelatedResponse || defined(INCLUDE_ImActorCoreModulesSequenceInternalHandlerRelatedResponse))
#define ImActorCoreModulesSequenceInternalHandlerRelatedResponse_

#define RESTRICT_ImActorRuntimeActorsAskAskMessage 1
#define INCLUDE_ImActorRuntimeActorsAskAskMessage 1
#include "../../../../../../im/actor/runtime/actors/ask/AskMessage.h"

@protocol JavaUtilList;

@interface ImActorCoreModulesSequenceInternalHandlerRelatedResponse : NSObject < ImActorRuntimeActorsAskAskMessage >

#pragma mark Public

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)relatedUsers
                    withJavaUtilList:(id<JavaUtilList>)relatedGroups;

- (id<JavaUtilList>)getRelatedGroups;

- (id<JavaUtilList>)getRelatedUsers;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesSequenceInternalHandlerRelatedResponse)

FOUNDATION_EXPORT void ImActorCoreModulesSequenceInternalHandlerRelatedResponse_initWithJavaUtilList_withJavaUtilList_(ImActorCoreModulesSequenceInternalHandlerRelatedResponse *self, id<JavaUtilList> relatedUsers, id<JavaUtilList> relatedGroups);

FOUNDATION_EXPORT ImActorCoreModulesSequenceInternalHandlerRelatedResponse *new_ImActorCoreModulesSequenceInternalHandlerRelatedResponse_initWithJavaUtilList_withJavaUtilList_(id<JavaUtilList> relatedUsers, id<JavaUtilList> relatedGroups) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesSequenceInternalHandlerRelatedResponse *create_ImActorCoreModulesSequenceInternalHandlerRelatedResponse_initWithJavaUtilList_withJavaUtilList_(id<JavaUtilList> relatedUsers, id<JavaUtilList> relatedGroups);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesSequenceInternalHandlerRelatedResponse)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesSequenceInternalHandlerRelatedResponse")
