//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/RequestSubscribeToGroupOnline.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestSubscribeToGroupOnline")
#ifdef RESTRICT_ImActorCoreApiRpcRequestSubscribeToGroupOnline
#define INCLUDE_ALL_ImActorCoreApiRpcRequestSubscribeToGroupOnline 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcRequestSubscribeToGroupOnline 1
#endif
#undef RESTRICT_ImActorCoreApiRpcRequestSubscribeToGroupOnline

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestSubscribeToGroupOnline_) && (INCLUDE_ALL_ImActorCoreApiRpcRequestSubscribeToGroupOnline || defined(INCLUDE_ARRequestSubscribeToGroupOnline))
#define ARRequestSubscribeToGroupOnline_

#define RESTRICT_ImActorCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@protocol JavaUtilList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestSubscribeToGroupOnline : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilList:(id<JavaUtilList> __nonnull)groups;

+ (ARRequestSubscribeToGroupOnline *)fromBytesWithByteArray:(IOSByteArray *)data;

- (id<JavaUtilList> __nonnull)getGroups;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestSubscribeToGroupOnline)

inline jint ARRequestSubscribeToGroupOnline_get_HEADER();
#define ARRequestSubscribeToGroupOnline_HEADER 74
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestSubscribeToGroupOnline, HEADER, jint)

FOUNDATION_EXPORT ARRequestSubscribeToGroupOnline *ARRequestSubscribeToGroupOnline_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestSubscribeToGroupOnline_initWithJavaUtilList_(ARRequestSubscribeToGroupOnline *self, id<JavaUtilList> groups);

FOUNDATION_EXPORT ARRequestSubscribeToGroupOnline *new_ARRequestSubscribeToGroupOnline_initWithJavaUtilList_(id<JavaUtilList> groups) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSubscribeToGroupOnline *create_ARRequestSubscribeToGroupOnline_initWithJavaUtilList_(id<JavaUtilList> groups);

FOUNDATION_EXPORT void ARRequestSubscribeToGroupOnline_init(ARRequestSubscribeToGroupOnline *self);

FOUNDATION_EXPORT ARRequestSubscribeToGroupOnline *new_ARRequestSubscribeToGroupOnline_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSubscribeToGroupOnline *create_ARRequestSubscribeToGroupOnline_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestSubscribeToGroupOnline)

@compatibility_alias ImActorCoreApiRpcRequestSubscribeToGroupOnline ARRequestSubscribeToGroupOnline;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestSubscribeToGroupOnline")
