//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/RequestRegisterApplePushToken.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePushToken")
#ifdef RESTRICT_ImActorCoreApiRpcRequestRegisterApplePushToken
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePushToken 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePushToken 1
#endif
#undef RESTRICT_ImActorCoreApiRpcRequestRegisterApplePushToken

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestRegisterApplePushToken_) && (INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePushToken || defined(INCLUDE_ARRequestRegisterApplePushToken))
#define ARRequestRegisterApplePushToken_

#define RESTRICT_ImActorCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestRegisterApplePushToken : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)bundleId
                    withNSString:(NSString * __nonnull)token;

+ (ARRequestRegisterApplePushToken *)fromBytesWithByteArray:(IOSByteArray *)data;

- (NSString * __nonnull)getBundleId;

- (jint)getHeaderKey;

- (NSString * __nonnull)getToken;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestRegisterApplePushToken)

inline jint ARRequestRegisterApplePushToken_get_HEADER();
#define ARRequestRegisterApplePushToken_HEADER 2593
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestRegisterApplePushToken, HEADER, jint)

FOUNDATION_EXPORT ARRequestRegisterApplePushToken *ARRequestRegisterApplePushToken_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestRegisterApplePushToken_initWithNSString_withNSString_(ARRequestRegisterApplePushToken *self, NSString *bundleId, NSString *token);

FOUNDATION_EXPORT ARRequestRegisterApplePushToken *new_ARRequestRegisterApplePushToken_initWithNSString_withNSString_(NSString *bundleId, NSString *token) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRegisterApplePushToken *create_ARRequestRegisterApplePushToken_initWithNSString_withNSString_(NSString *bundleId, NSString *token);

FOUNDATION_EXPORT void ARRequestRegisterApplePushToken_init(ARRequestRegisterApplePushToken *self);

FOUNDATION_EXPORT ARRequestRegisterApplePushToken *new_ARRequestRegisterApplePushToken_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRegisterApplePushToken *create_ARRequestRegisterApplePushToken_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestRegisterApplePushToken)

@compatibility_alias ImActorCoreApiRpcRequestRegisterApplePushToken ARRequestRegisterApplePushToken;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePushToken")
