//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/RequestRegisterGooglePush.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterGooglePush")
#ifdef RESTRICT_ImActorCoreApiRpcRequestRegisterGooglePush
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterGooglePush 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterGooglePush 1
#endif
#undef RESTRICT_ImActorCoreApiRpcRequestRegisterGooglePush

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestRegisterGooglePush_) && (INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterGooglePush || defined(INCLUDE_ARRequestRegisterGooglePush))
#define ARRequestRegisterGooglePush_

#define RESTRICT_ImActorCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestRegisterGooglePush : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)projectId
                withNSString:(NSString * __nonnull)token;

+ (ARRequestRegisterGooglePush *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (jlong)getProjectId;

- (NSString * __nonnull)getToken;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestRegisterGooglePush)

inline jint ARRequestRegisterGooglePush_get_HEADER();
#define ARRequestRegisterGooglePush_HEADER 51
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestRegisterGooglePush, HEADER, jint)

FOUNDATION_EXPORT ARRequestRegisterGooglePush *ARRequestRegisterGooglePush_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestRegisterGooglePush_initWithLong_withNSString_(ARRequestRegisterGooglePush *self, jlong projectId, NSString *token);

FOUNDATION_EXPORT ARRequestRegisterGooglePush *new_ARRequestRegisterGooglePush_initWithLong_withNSString_(jlong projectId, NSString *token) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRegisterGooglePush *create_ARRequestRegisterGooglePush_initWithLong_withNSString_(jlong projectId, NSString *token);

FOUNDATION_EXPORT void ARRequestRegisterGooglePush_init(ARRequestRegisterGooglePush *self);

FOUNDATION_EXPORT ARRequestRegisterGooglePush *new_ARRequestRegisterGooglePush_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRegisterGooglePush *create_ARRequestRegisterGooglePush_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestRegisterGooglePush)

@compatibility_alias ImActorCoreApiRpcRequestRegisterGooglePush ARRequestRegisterGooglePush;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterGooglePush")
