//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/RequestRemoveGroupAvatar.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRemoveGroupAvatar")
#ifdef RESTRICT_ImActorCoreApiRpcRequestRemoveGroupAvatar
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRemoveGroupAvatar 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRemoveGroupAvatar 1
#endif
#undef RESTRICT_ImActorCoreApiRpcRequestRemoveGroupAvatar

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestRemoveGroupAvatar_) && (INCLUDE_ALL_ImActorCoreApiRpcRequestRemoveGroupAvatar || defined(INCLUDE_ARRequestRemoveGroupAvatar))
#define ARRequestRemoveGroupAvatar_

#define RESTRICT_ImActorCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/actor/core/network/parser/Request.h"

@class ARApiGroupOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestRemoveGroupAvatar : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiGroupOutPeer:(ARApiGroupOutPeer * __nonnull)groupPeer
                                 withLong:(jlong)rid;

+ (ARRequestRemoveGroupAvatar *)fromBytesWithByteArray:(IOSByteArray *)data;

- (ARApiGroupOutPeer * __nonnull)getGroupPeer;

- (jint)getHeaderKey;

- (jlong)getRid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestRemoveGroupAvatar)

inline jint ARRequestRemoveGroupAvatar_get_HEADER();
#define ARRequestRemoveGroupAvatar_HEADER 101
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestRemoveGroupAvatar, HEADER, jint)

FOUNDATION_EXPORT ARRequestRemoveGroupAvatar *ARRequestRemoveGroupAvatar_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestRemoveGroupAvatar_initWithARApiGroupOutPeer_withLong_(ARRequestRemoveGroupAvatar *self, ARApiGroupOutPeer *groupPeer, jlong rid);

FOUNDATION_EXPORT ARRequestRemoveGroupAvatar *new_ARRequestRemoveGroupAvatar_initWithARApiGroupOutPeer_withLong_(ARApiGroupOutPeer *groupPeer, jlong rid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRemoveGroupAvatar *create_ARRequestRemoveGroupAvatar_initWithARApiGroupOutPeer_withLong_(ARApiGroupOutPeer *groupPeer, jlong rid);

FOUNDATION_EXPORT void ARRequestRemoveGroupAvatar_init(ARRequestRemoveGroupAvatar *self);

FOUNDATION_EXPORT ARRequestRemoveGroupAvatar *new_ARRequestRemoveGroupAvatar_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRemoveGroupAvatar *create_ARRequestRemoveGroupAvatar_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestRemoveGroupAvatar)

@compatibility_alias ImActorCoreApiRpcRequestRemoveGroupAvatar ARRequestRemoveGroupAvatar;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRemoveGroupAvatar")
