//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/RequestLoadOwnStickers.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestLoadOwnStickers")
#ifdef RESTRICT_ImActorCoreApiRpcRequestLoadOwnStickers
#define INCLUDE_ALL_ImActorCoreApiRpcRequestLoadOwnStickers 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcRequestLoadOwnStickers 1
#endif
#undef RESTRICT_ImActorCoreApiRpcRequestLoadOwnStickers

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestLoadOwnStickers_) && (INCLUDE_ALL_ImActorCoreApiRpcRequestLoadOwnStickers || defined(INCLUDE_ARRequestLoadOwnStickers))
#define ARRequestLoadOwnStickers_

#define RESTRICT_ImActorCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARRequestLoadOwnStickers : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

+ (ARRequestLoadOwnStickers *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestLoadOwnStickers)

inline jint ARRequestLoadOwnStickers_get_HEADER();
#define ARRequestLoadOwnStickers_HEADER 238
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestLoadOwnStickers, HEADER, jint)

FOUNDATION_EXPORT ARRequestLoadOwnStickers *ARRequestLoadOwnStickers_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestLoadOwnStickers_init(ARRequestLoadOwnStickers *self);

FOUNDATION_EXPORT ARRequestLoadOwnStickers *new_ARRequestLoadOwnStickers_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestLoadOwnStickers *create_ARRequestLoadOwnStickers_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestLoadOwnStickers)

@compatibility_alias ImActorCoreApiRpcRequestLoadOwnStickers ARRequestLoadOwnStickers;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestLoadOwnStickers")
