//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/RequestDisableFeature.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestDisableFeature")
#ifdef RESTRICT_ImActorCoreApiRpcRequestDisableFeature
#define INCLUDE_ALL_ImActorCoreApiRpcRequestDisableFeature 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcRequestDisableFeature 1
#endif
#undef RESTRICT_ImActorCoreApiRpcRequestDisableFeature

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestDisableFeature_) && (INCLUDE_ALL_ImActorCoreApiRpcRequestDisableFeature || defined(INCLUDE_ARRequestDisableFeature))
#define ARRequestDisableFeature_

#define RESTRICT_ImActorCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestDisableFeature : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)featureName;

+ (ARRequestDisableFeature *)fromBytesWithByteArray:(IOSByteArray *)data;

- (NSString * __nonnull)getFeatureName;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestDisableFeature)

inline jint ARRequestDisableFeature_get_HEADER();
#define ARRequestDisableFeature_HEADER 2589
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestDisableFeature, HEADER, jint)

FOUNDATION_EXPORT ARRequestDisableFeature *ARRequestDisableFeature_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestDisableFeature_initWithNSString_(ARRequestDisableFeature *self, NSString *featureName);

FOUNDATION_EXPORT ARRequestDisableFeature *new_ARRequestDisableFeature_initWithNSString_(NSString *featureName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestDisableFeature *create_ARRequestDisableFeature_initWithNSString_(NSString *featureName);

FOUNDATION_EXPORT void ARRequestDisableFeature_init(ARRequestDisableFeature *self);

FOUNDATION_EXPORT ARRequestDisableFeature *new_ARRequestDisableFeature_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestDisableFeature *create_ARRequestDisableFeature_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestDisableFeature)

@compatibility_alias ImActorCoreApiRpcRequestDisableFeature ARRequestDisableFeature;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestDisableFeature")
