//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/RequestRegisterApplePush.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePush")
#ifdef RESTRICT_ImActorCoreApiRpcRequestRegisterApplePush
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePush 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePush 1
#endif
#undef RESTRICT_ImActorCoreApiRpcRequestRegisterApplePush

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestRegisterApplePush_) && (INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePush || defined(INCLUDE_ARRequestRegisterApplePush))
#define ARRequestRegisterApplePush_

#define RESTRICT_ImActorCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestRegisterApplePush : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)apnsKey
               withNSString:(NSString * __nonnull)token;

+ (ARRequestRegisterApplePush *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getApnsKey;

- (jint)getHeaderKey;

- (NSString * __nonnull)getToken;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestRegisterApplePush)

inline jint ARRequestRegisterApplePush_get_HEADER();
#define ARRequestRegisterApplePush_HEADER 76
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestRegisterApplePush, HEADER, jint)

FOUNDATION_EXPORT ARRequestRegisterApplePush *ARRequestRegisterApplePush_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestRegisterApplePush_initWithInt_withNSString_(ARRequestRegisterApplePush *self, jint apnsKey, NSString *token);

FOUNDATION_EXPORT ARRequestRegisterApplePush *new_ARRequestRegisterApplePush_initWithInt_withNSString_(jint apnsKey, NSString *token) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRegisterApplePush *create_ARRequestRegisterApplePush_initWithInt_withNSString_(jint apnsKey, NSString *token);

FOUNDATION_EXPORT void ARRequestRegisterApplePush_init(ARRequestRegisterApplePush *self);

FOUNDATION_EXPORT ARRequestRegisterApplePush *new_ARRequestRegisterApplePush_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestRegisterApplePush *create_ARRequestRegisterApplePush_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestRegisterApplePush)

@compatibility_alias ImActorCoreApiRpcRequestRegisterApplePush ARRequestRegisterApplePush;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcRequestRegisterApplePush")
