//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/ResponseCreateNewKeyGroup.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcResponseCreateNewKeyGroup")
#ifdef RESTRICT_ImActorCoreApiRpcResponseCreateNewKeyGroup
#define INCLUDE_ALL_ImActorCoreApiRpcResponseCreateNewKeyGroup 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcResponseCreateNewKeyGroup 1
#endif
#undef RESTRICT_ImActorCoreApiRpcResponseCreateNewKeyGroup

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseCreateNewKeyGroup_) && (INCLUDE_ALL_ImActorCoreApiRpcResponseCreateNewKeyGroup || defined(INCLUDE_ARResponseCreateNewKeyGroup))
#define ARResponseCreateNewKeyGroup_

#define RESTRICT_ImActorCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/actor/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARResponseCreateNewKeyGroup : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)keyGroupId;

+ (ARResponseCreateNewKeyGroup *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (jint)getKeyGroupId;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseCreateNewKeyGroup)

inline jint ARResponseCreateNewKeyGroup_get_HEADER();
#define ARResponseCreateNewKeyGroup_HEADER 2610
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseCreateNewKeyGroup, HEADER, jint)

FOUNDATION_EXPORT ARResponseCreateNewKeyGroup *ARResponseCreateNewKeyGroup_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseCreateNewKeyGroup_initWithInt_(ARResponseCreateNewKeyGroup *self, jint keyGroupId);

FOUNDATION_EXPORT ARResponseCreateNewKeyGroup *new_ARResponseCreateNewKeyGroup_initWithInt_(jint keyGroupId) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseCreateNewKeyGroup *create_ARResponseCreateNewKeyGroup_initWithInt_(jint keyGroupId);

FOUNDATION_EXPORT void ARResponseCreateNewKeyGroup_init(ARResponseCreateNewKeyGroup *self);

FOUNDATION_EXPORT ARResponseCreateNewKeyGroup *new_ARResponseCreateNewKeyGroup_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseCreateNewKeyGroup *create_ARResponseCreateNewKeyGroup_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseCreateNewKeyGroup)

@compatibility_alias ImActorCoreApiRpcResponseCreateNewKeyGroup ARResponseCreateNewKeyGroup;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcResponseCreateNewKeyGroup")
