//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/ResponseCompleteWebaction.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcResponseCompleteWebaction")
#ifdef RESTRICT_ImActorCoreApiRpcResponseCompleteWebaction
#define INCLUDE_ALL_ImActorCoreApiRpcResponseCompleteWebaction 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcResponseCompleteWebaction 1
#endif
#undef RESTRICT_ImActorCoreApiRpcResponseCompleteWebaction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseCompleteWebaction_) && (INCLUDE_ALL_ImActorCoreApiRpcResponseCompleteWebaction || defined(INCLUDE_ARResponseCompleteWebaction))
#define ARResponseCompleteWebaction_

#define RESTRICT_ImActorCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/actor/core/network/parser/Response.h"

@class ARApiMapValue;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARResponseCompleteWebaction : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiMapValue:(ARApiMapValue * __nonnull)result;

+ (ARResponseCompleteWebaction *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (ARApiMapValue * __nonnull)getResult;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseCompleteWebaction)

inline jint ARResponseCompleteWebaction_get_HEADER();
#define ARResponseCompleteWebaction_HEADER 124
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseCompleteWebaction, HEADER, jint)

FOUNDATION_EXPORT ARResponseCompleteWebaction *ARResponseCompleteWebaction_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseCompleteWebaction_initWithARApiMapValue_(ARResponseCompleteWebaction *self, ARApiMapValue *result);

FOUNDATION_EXPORT ARResponseCompleteWebaction *new_ARResponseCompleteWebaction_initWithARApiMapValue_(ARApiMapValue *result) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseCompleteWebaction *create_ARResponseCompleteWebaction_initWithARApiMapValue_(ARApiMapValue *result);

FOUNDATION_EXPORT void ARResponseCompleteWebaction_init(ARResponseCompleteWebaction *self);

FOUNDATION_EXPORT ARResponseCompleteWebaction *new_ARResponseCompleteWebaction_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseCompleteWebaction *create_ARResponseCompleteWebaction_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseCompleteWebaction)

@compatibility_alias ImActorCoreApiRpcResponseCompleteWebaction ARResponseCompleteWebaction;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcResponseCompleteWebaction")
