//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/rpc/ResponseSendAuthCodeObsolete.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiRpcResponseSendAuthCodeObsolete")
#ifdef RESTRICT_ImActorCoreApiRpcResponseSendAuthCodeObsolete
#define INCLUDE_ALL_ImActorCoreApiRpcResponseSendAuthCodeObsolete 0
#else
#define INCLUDE_ALL_ImActorCoreApiRpcResponseSendAuthCodeObsolete 1
#endif
#undef RESTRICT_ImActorCoreApiRpcResponseSendAuthCodeObsolete

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseSendAuthCodeObsolete_) && (INCLUDE_ALL_ImActorCoreApiRpcResponseSendAuthCodeObsolete || defined(INCLUDE_ARResponseSendAuthCodeObsolete))
#define ARResponseSendAuthCodeObsolete_

#define RESTRICT_ImActorCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/actor/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARResponseSendAuthCodeObsolete : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)smsHash
                     withBoolean:(jboolean)isRegistered;

+ (ARResponseSendAuthCodeObsolete *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (NSString * __nonnull)getSmsHash;

- (jboolean)isRegistered;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseSendAuthCodeObsolete)

inline jint ARResponseSendAuthCodeObsolete_get_HEADER();
#define ARResponseSendAuthCodeObsolete_HEADER 2
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseSendAuthCodeObsolete, HEADER, jint)

FOUNDATION_EXPORT ARResponseSendAuthCodeObsolete *ARResponseSendAuthCodeObsolete_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseSendAuthCodeObsolete_initWithNSString_withBoolean_(ARResponseSendAuthCodeObsolete *self, NSString *smsHash, jboolean isRegistered);

FOUNDATION_EXPORT ARResponseSendAuthCodeObsolete *new_ARResponseSendAuthCodeObsolete_initWithNSString_withBoolean_(NSString *smsHash, jboolean isRegistered) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseSendAuthCodeObsolete *create_ARResponseSendAuthCodeObsolete_initWithNSString_withBoolean_(NSString *smsHash, jboolean isRegistered);

FOUNDATION_EXPORT void ARResponseSendAuthCodeObsolete_init(ARResponseSendAuthCodeObsolete *self);

FOUNDATION_EXPORT ARResponseSendAuthCodeObsolete *new_ARResponseSendAuthCodeObsolete_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseSendAuthCodeObsolete *create_ARResponseSendAuthCodeObsolete_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseSendAuthCodeObsolete)

@compatibility_alias ImActorCoreApiRpcResponseSendAuthCodeObsolete ARResponseSendAuthCodeObsolete;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiRpcResponseSendAuthCodeObsolete")
