//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-cocoa/src/main/java/im/actor/runtime/cocoa/CocoaMainThreadProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCocoaCocoaMainThreadProvider")
#ifdef RESTRICT_ImActorRuntimeCocoaCocoaMainThreadProvider
#define INCLUDE_ALL_ImActorRuntimeCocoaCocoaMainThreadProvider 0
#else
#define INCLUDE_ALL_ImActorRuntimeCocoaCocoaMainThreadProvider 1
#endif
#undef RESTRICT_ImActorRuntimeCocoaCocoaMainThreadProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARCocoaMainThreadProvider_) && (INCLUDE_ALL_ImActorRuntimeCocoaCocoaMainThreadProvider || defined(INCLUDE_ARCocoaMainThreadProvider))
#define ARCocoaMainThreadProvider_

#define RESTRICT_ImActorRuntimeMainThreadRuntime 1
#define INCLUDE_ARMainThreadRuntime 1
#include "../../../../im/actor/runtime/MainThreadRuntime.h"

@protocol JavaLangRunnable;

@interface ARCocoaMainThreadProvider : NSObject < ARMainThreadRuntime >

#pragma mark Public

- (instancetype)init;

- (jboolean)isMainThread;

- (jboolean)isSingleThread;

- (void)postToMainThreadWithRunnable:(id<JavaLangRunnable>)runnable;

@end

J2OBJC_EMPTY_STATIC_INIT(ARCocoaMainThreadProvider)

FOUNDATION_EXPORT void ARCocoaMainThreadProvider_init(ARCocoaMainThreadProvider *self);

FOUNDATION_EXPORT ARCocoaMainThreadProvider *new_ARCocoaMainThreadProvider_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARCocoaMainThreadProvider *create_ARCocoaMainThreadProvider_init();

J2OBJC_TYPE_LITERAL_HEADER(ARCocoaMainThreadProvider)

@compatibility_alias ImActorRuntimeCocoaCocoaMainThreadProvider ARCocoaMainThreadProvider;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCocoaCocoaMainThreadProvider")
