//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/entity/content/FileRemoteSource.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEntityContentFileRemoteSource")
#ifdef RESTRICT_ImActorCoreEntityContentFileRemoteSource
#define INCLUDE_ALL_ImActorCoreEntityContentFileRemoteSource 0
#else
#define INCLUDE_ALL_ImActorCoreEntityContentFileRemoteSource 1
#endif
#undef RESTRICT_ImActorCoreEntityContentFileRemoteSource

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACFileRemoteSource_) && (INCLUDE_ALL_ImActorCoreEntityContentFileRemoteSource || defined(INCLUDE_ACFileRemoteSource))
#define ACFileRemoteSource_

#define RESTRICT_ImActorCoreEntityContentFileSource 1
#define INCLUDE_ACFileSource 1
#include "../../../../../im/actor/core/entity/content/FileSource.h"

@class ACFileReference;

@interface ACFileRemoteSource : ACFileSource

#pragma mark Public

- (instancetype)initWithACFileReference:(ACFileReference *)fileReference;

- (NSString *)getFileName;

- (ACFileReference *)getFileReference;

- (jint)getSize;

@end

J2OBJC_EMPTY_STATIC_INIT(ACFileRemoteSource)

FOUNDATION_EXPORT void ACFileRemoteSource_initWithACFileReference_(ACFileRemoteSource *self, ACFileReference *fileReference);

FOUNDATION_EXPORT ACFileRemoteSource *new_ACFileRemoteSource_initWithACFileReference_(ACFileReference *fileReference) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACFileRemoteSource *create_ACFileRemoteSource_initWithACFileReference_(ACFileReference *fileReference);

J2OBJC_TYPE_LITERAL_HEADER(ACFileRemoteSource)

@compatibility_alias ImActorCoreEntityContentFileRemoteSource ACFileRemoteSource;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEntityContentFileRemoteSource")
