//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/entity/content/ServiceGroupAboutChanged.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEntityContentServiceGroupAboutChanged")
#ifdef RESTRICT_ImActorCoreEntityContentServiceGroupAboutChanged
#define INCLUDE_ALL_ImActorCoreEntityContentServiceGroupAboutChanged 0
#else
#define INCLUDE_ALL_ImActorCoreEntityContentServiceGroupAboutChanged 1
#endif
#undef RESTRICT_ImActorCoreEntityContentServiceGroupAboutChanged

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACServiceGroupAboutChanged_) && (INCLUDE_ALL_ImActorCoreEntityContentServiceGroupAboutChanged || defined(INCLUDE_ACServiceGroupAboutChanged))
#define ACServiceGroupAboutChanged_

#define RESTRICT_ImActorCoreEntityContentServiceContent 1
#define INCLUDE_ACServiceContent 1
#include "../../../../../im/actor/core/entity/content/ServiceContent.h"

@class ACContentRemoteContainer;

@interface ACServiceGroupAboutChanged : ACServiceContent

#pragma mark Public

- (instancetype)initWithACContentRemoteContainer:(ACContentRemoteContainer *)remoteContainer;

+ (ACServiceGroupAboutChanged *)createWithNSString:(NSString *)title;

- (NSString *)getNewAbout;

@end

J2OBJC_EMPTY_STATIC_INIT(ACServiceGroupAboutChanged)

FOUNDATION_EXPORT ACServiceGroupAboutChanged *ACServiceGroupAboutChanged_createWithNSString_(NSString *title);

FOUNDATION_EXPORT void ACServiceGroupAboutChanged_initWithACContentRemoteContainer_(ACServiceGroupAboutChanged *self, ACContentRemoteContainer *remoteContainer);

FOUNDATION_EXPORT ACServiceGroupAboutChanged *new_ACServiceGroupAboutChanged_initWithACContentRemoteContainer_(ACContentRemoteContainer *remoteContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACServiceGroupAboutChanged *create_ACServiceGroupAboutChanged_initWithACContentRemoteContainer_(ACContentRemoteContainer *remoteContainer);

J2OBJC_TYPE_LITERAL_HEADER(ACServiceGroupAboutChanged)

@compatibility_alias ImActorCoreEntityContentServiceGroupAboutChanged ACServiceGroupAboutChanged;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEntityContentServiceGroupAboutChanged")
