//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/eventbus/EventBusActor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor")
#ifdef RESTRICT_ImActorCoreModulesEventbusEventBusActor
#define INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor 0
#else
#define INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor 1
#endif
#undef RESTRICT_ImActorCoreModulesEventbusEventBusActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesEventbusEventBusActor_) && (INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor || defined(INCLUDE_ImActorCoreModulesEventbusEventBusActor))
#define ImActorCoreModulesEventbusEventBusActor_

#define RESTRICT_ImActorCoreModulesModuleActor 1
#define INCLUDE_ACModuleActor 1
#include "../../../../../im/actor/core/modules/ModuleActor.h"

@class IOSByteArray;
@class JavaLangInteger;
@class JavaLangLong;
@class JavaUtilArrayList;
@protocol ACModuleContext;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ImActorCoreModulesEventbusEventBusActor : ACModuleActor

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)connectBusWithNSString:(NSString *)busId
                      withLong:(jlong)deviceId
                   withBoolean:(jboolean)isJoined;

- (void)connectBusWithNSString:(NSString *)busId
                      withLong:(jlong)deviceId
                      withLong:(jlong)timeout
                   withBoolean:(jboolean)isJoined;

- (void)createBus;

- (void)createBusWithLong:(jlong)timeout;

- (void)dispose;

- (NSString *)getBusId;

- (jlong)getDeviceId;

- (void)joinBusWithNSString:(NSString *)busId;

- (void)joinBusWithNSString:(NSString *)busId
                   withLong:(jlong)timeout;

- (void)onBusCreated;

- (void)onBusDisposed;

- (void)onBusJoined;

- (void)onBusShutdown;

- (void)onBusStarted;

- (void)onBusStopped;

- (void)onDeviceConnectedWithInt:(jint)uid
                        withLong:(jlong)deviceId;

- (void)onDeviceDisconnectedWithInt:(jint)uid
                           withLong:(jlong)deviceId;

- (void)onMessageReceivedWithJavaLangInteger:(JavaLangInteger * __nullable)senderId
                            withJavaLangLong:(JavaLangLong * __nullable)senderDeviceId
                               withByteArray:(IOSByteArray *)data;

- (void)onReceiveWithId:(id)message;

- (void)postStop;

- (void)sendMessageWithJavaUtilArrayList:(JavaUtilArrayList *)deviceIds
                           withByteArray:(IOSByteArray *)data;

- (void)sendMessageWithByteArray:(IOSByteArray *)data;

- (void)sendMessageWithLong:(jlong)deviceId
              withByteArray:(IOSByteArray *)data;

- (void)shutdown;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesEventbusEventBusActor)

FOUNDATION_EXPORT void ImActorCoreModulesEventbusEventBusActor_initWithACModuleContext_(ImActorCoreModulesEventbusEventBusActor *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor *new_ImActorCoreModulesEventbusEventBusActor_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor *create_ImActorCoreModulesEventbusEventBusActor_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEventbusEventBusActor)

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif

#if !defined (ImActorCoreModulesEventbusEventBusActor_EventBusShutdown_) && (INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor || defined(INCLUDE_ImActorCoreModulesEventbusEventBusActor_EventBusShutdown))
#define ImActorCoreModulesEventbusEventBusActor_EventBusShutdown_

@interface ImActorCoreModulesEventbusEventBusActor_EventBusShutdown : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesEventbusEventBusActor_EventBusShutdown)

FOUNDATION_EXPORT void ImActorCoreModulesEventbusEventBusActor_EventBusShutdown_init(ImActorCoreModulesEventbusEventBusActor_EventBusShutdown *self);

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusShutdown *new_ImActorCoreModulesEventbusEventBusActor_EventBusShutdown_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusShutdown *create_ImActorCoreModulesEventbusEventBusActor_EventBusShutdown_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEventbusEventBusActor_EventBusShutdown)

#endif

#if !defined (ImActorCoreModulesEventbusEventBusActor_EventBusDisposed_) && (INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor || defined(INCLUDE_ImActorCoreModulesEventbusEventBusActor_EventBusDisposed))
#define ImActorCoreModulesEventbusEventBusActor_EventBusDisposed_

@interface ImActorCoreModulesEventbusEventBusActor_EventBusDisposed : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesEventbusEventBusActor_EventBusDisposed)

FOUNDATION_EXPORT void ImActorCoreModulesEventbusEventBusActor_EventBusDisposed_init(ImActorCoreModulesEventbusEventBusActor_EventBusDisposed *self);

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusDisposed *new_ImActorCoreModulesEventbusEventBusActor_EventBusDisposed_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusDisposed *create_ImActorCoreModulesEventbusEventBusActor_EventBusDisposed_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEventbusEventBusActor_EventBusDisposed)

#endif

#if !defined (ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected_) && (INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor || defined(INCLUDE_ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected))
#define ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected_

@interface ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)uid
                   withLong:(jlong)deviceId;

- (jlong)getDeviceId;

- (jint)getUid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected)

FOUNDATION_EXPORT void ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected_initWithInt_withLong_(ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected *self, jint uid, jlong deviceId);

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected *new_ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected_initWithInt_withLong_(jint uid, jlong deviceId) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected *create_ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected_initWithInt_withLong_(jint uid, jlong deviceId);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEventbusEventBusActor_EventBusDeviceConnected)

#endif

#if !defined (ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected_) && (INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor || defined(INCLUDE_ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected))
#define ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected_

@interface ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)uid
                   withLong:(jlong)deviceId;

- (jlong)getDeviceId;

- (jint)getUid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected)

FOUNDATION_EXPORT void ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected_initWithInt_withLong_(ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected *self, jint uid, jlong deviceId);

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected *new_ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected_initWithInt_withLong_(jint uid, jlong deviceId) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected *create_ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected_initWithInt_withLong_(jint uid, jlong deviceId);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEventbusEventBusActor_EventBusDeviceDisconnected)

#endif

#if !defined (ImActorCoreModulesEventbusEventBusActor_EventBusMessage_) && (INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor || defined(INCLUDE_ImActorCoreModulesEventbusEventBusActor_EventBusMessage))
#define ImActorCoreModulesEventbusEventBusActor_EventBusMessage_

@class IOSByteArray;
@class JavaLangInteger;
@class JavaLangLong;

@interface ImActorCoreModulesEventbusEventBusActor_EventBusMessage : NSObject

#pragma mark Public

- (instancetype)initWithJavaLangInteger:(JavaLangInteger *)senderId
                       withJavaLangLong:(JavaLangLong *)senderDeviceId
                          withByteArray:(IOSByteArray *)message;

- (IOSByteArray *)getMessage;

- (JavaLangLong *)getSenderDeviceId;

- (JavaLangInteger *)getSenderId;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesEventbusEventBusActor_EventBusMessage)

FOUNDATION_EXPORT void ImActorCoreModulesEventbusEventBusActor_EventBusMessage_initWithJavaLangInteger_withJavaLangLong_withByteArray_(ImActorCoreModulesEventbusEventBusActor_EventBusMessage *self, JavaLangInteger *senderId, JavaLangLong *senderDeviceId, IOSByteArray *message);

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusMessage *new_ImActorCoreModulesEventbusEventBusActor_EventBusMessage_initWithJavaLangInteger_withJavaLangLong_withByteArray_(JavaLangInteger *senderId, JavaLangLong *senderDeviceId, IOSByteArray *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesEventbusEventBusActor_EventBusMessage *create_ImActorCoreModulesEventbusEventBusActor_EventBusMessage_initWithJavaLangInteger_withJavaLangLong_withByteArray_(JavaLangInteger *senderId, JavaLangLong *senderDeviceId, IOSByteArray *message);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEventbusEventBusActor_EventBusMessage)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesEventbusEventBusActor")
