//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-cocoa/src/main/java/im/actor/runtime/cocoa/crypto/CocoaCryptoProxyProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider")
#ifdef RESTRICT_ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider
#define INCLUDE_ALL_ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider 0
#else
#define INCLUDE_ALL_ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider 1
#endif
#undef RESTRICT_ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARCocoaCryptoProxyProvider_) && (INCLUDE_ALL_ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider || defined(INCLUDE_ARCocoaCryptoProxyProvider))
#define ARCocoaCryptoProxyProvider_

@class IOSByteArray;
@protocol ARBlockCipher;
@protocol ARDigest;

@protocol ARCocoaCryptoProxyProvider < NSObject, JavaObject >

- (id<ARDigest>)createSHA256;

- (id<ARBlockCipher>)createAES128WithKey:(IOSByteArray *)key;

@end

J2OBJC_EMPTY_STATIC_INIT(ARCocoaCryptoProxyProvider)

J2OBJC_TYPE_LITERAL_HEADER(ARCocoaCryptoProxyProvider)

#define ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider ARCocoaCryptoProxyProvider

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCocoaCryptoCocoaCryptoProxyProvider")
