//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/ratchet/RatchetMessageKey.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoRatchetRatchetMessageKey")
#ifdef RESTRICT_ImActorRuntimeCryptoRatchetRatchetMessageKey
#define INCLUDE_ALL_ImActorRuntimeCryptoRatchetRatchetMessageKey 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoRatchetRatchetMessageKey 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoRatchetRatchetMessageKey

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoRatchetRatchetMessageKey_) && (INCLUDE_ALL_ImActorRuntimeCryptoRatchetRatchetMessageKey || defined(INCLUDE_ImActorRuntimeCryptoRatchetRatchetMessageKey))
#define ImActorRuntimeCryptoRatchetRatchetMessageKey_

@class IOSByteArray;
@class ImActorRuntimeCryptoBoxActorBoxKey;

@interface ImActorRuntimeCryptoRatchetRatchetMessageKey : NSObject

#pragma mark Public

- (instancetype)init;

+ (ImActorRuntimeCryptoBoxActorBoxKey *)buildKeyWithByteArray:(IOSByteArray *)rootChainKey
                                                      withInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoRatchetRatchetMessageKey)

FOUNDATION_EXPORT ImActorRuntimeCryptoBoxActorBoxKey *ImActorRuntimeCryptoRatchetRatchetMessageKey_buildKeyWithByteArray_withInt_(IOSByteArray *rootChainKey, jint index);

FOUNDATION_EXPORT void ImActorRuntimeCryptoRatchetRatchetMessageKey_init(ImActorRuntimeCryptoRatchetRatchetMessageKey *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoRatchetRatchetMessageKey *new_ImActorRuntimeCryptoRatchetRatchetMessageKey_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoRatchetRatchetMessageKey *create_ImActorRuntimeCryptoRatchetRatchetMessageKey_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoRatchetRatchetMessageKey)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoRatchetRatchetMessageKey")
