//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/storage/StorageModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesStorageStorageModule")
#ifdef RESTRICT_ImActorCoreModulesStorageStorageModule
#define INCLUDE_ALL_ImActorCoreModulesStorageStorageModule 0
#else
#define INCLUDE_ALL_ImActorCoreModulesStorageStorageModule 1
#endif
#undef RESTRICT_ImActorCoreModulesStorageStorageModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesStorageStorageModule_) && (INCLUDE_ALL_ImActorCoreModulesStorageStorageModule || defined(INCLUDE_ImActorCoreModulesStorageStorageModule))
#define ImActorCoreModulesStorageStorageModule_

#define RESTRICT_ImActorCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/actor/core/modules/AbsModule.h"

@protocol ACModuleContext;
@protocol ARKeyValueStorage;

@interface ImActorCoreModulesStorageStorageModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (id<ARKeyValueStorage>)getBlobStorage;

- (void)runWithBoolean:(jboolean)isFirst;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesStorageStorageModule)

FOUNDATION_EXPORT void ImActorCoreModulesStorageStorageModule_initWithACModuleContext_(ImActorCoreModulesStorageStorageModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImActorCoreModulesStorageStorageModule *new_ImActorCoreModulesStorageStorageModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesStorageStorageModule *create_ImActorCoreModulesStorageStorageModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesStorageStorageModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesStorageStorageModule")
