//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/mtproto/CreateConnectionCallback.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeMtprotoCreateConnectionCallback")
#ifdef RESTRICT_ImActorRuntimeMtprotoCreateConnectionCallback
#define INCLUDE_ALL_ImActorRuntimeMtprotoCreateConnectionCallback 0
#else
#define INCLUDE_ALL_ImActorRuntimeMtprotoCreateConnectionCallback 1
#endif
#undef RESTRICT_ImActorRuntimeMtprotoCreateConnectionCallback

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARCreateConnectionCallback_) && (INCLUDE_ALL_ImActorRuntimeMtprotoCreateConnectionCallback || defined(INCLUDE_ARCreateConnectionCallback))
#define ARCreateConnectionCallback_

@protocol ARConnection;

@protocol ARCreateConnectionCallback < NSObject, JavaObject >

- (void)onConnectionCreatedWithConnection:(id<ARConnection>)connection;

- (void)onConnectionCreateError;

@end

J2OBJC_EMPTY_STATIC_INIT(ARCreateConnectionCallback)

J2OBJC_TYPE_LITERAL_HEADER(ARCreateConnectionCallback)

#define ImActorRuntimeMtprotoCreateConnectionCallback ARCreateConnectionCallback

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeMtprotoCreateConnectionCallback")
