//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/mtproto/ManagedConnectionCreateCallback.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeMtprotoManagedConnectionCreateCallback")
#ifdef RESTRICT_ImActorRuntimeMtprotoManagedConnectionCreateCallback
#define INCLUDE_ALL_ImActorRuntimeMtprotoManagedConnectionCreateCallback 0
#else
#define INCLUDE_ALL_ImActorRuntimeMtprotoManagedConnectionCreateCallback 1
#endif
#undef RESTRICT_ImActorRuntimeMtprotoManagedConnectionCreateCallback

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARManagedConnectionCreateCallback_) && (INCLUDE_ALL_ImActorRuntimeMtprotoManagedConnectionCreateCallback || defined(INCLUDE_ARManagedConnectionCreateCallback))
#define ARManagedConnectionCreateCallback_

@class ARManagedConnection;

@protocol ARManagedConnectionCreateCallback < NSObject, JavaObject >

- (void)onConnectionCreated:(ARManagedConnection *)connection;

- (void)onConnectionCreateError:(ARManagedConnection *)connection;

@end

J2OBJC_EMPTY_STATIC_INIT(ARManagedConnectionCreateCallback)

J2OBJC_TYPE_LITERAL_HEADER(ARManagedConnectionCreateCallback)

#define ImActorRuntimeMtprotoManagedConnectionCreateCallback ARManagedConnectionCreateCallback

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeMtprotoManagedConnectionCreateCallback")
