//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/mtproto/ManagedNetworkProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeMtprotoManagedNetworkProvider")
#ifdef RESTRICT_ImActorRuntimeMtprotoManagedNetworkProvider
#define INCLUDE_ALL_ImActorRuntimeMtprotoManagedNetworkProvider 0
#else
#define INCLUDE_ALL_ImActorRuntimeMtprotoManagedNetworkProvider 1
#endif
#undef RESTRICT_ImActorRuntimeMtprotoManagedNetworkProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARManagedNetworkProvider_) && (INCLUDE_ALL_ImActorRuntimeMtprotoManagedNetworkProvider || defined(INCLUDE_ARManagedNetworkProvider))
#define ARManagedNetworkProvider_

#define RESTRICT_ImActorRuntimeNetworkRuntime 1
#define INCLUDE_ARNetworkRuntime 1
#include "../../../../im/actor/runtime/NetworkRuntime.h"

@class ARConnectionEndpoint;
@protocol ARAsyncConnectionFactory;
@protocol ARConnectionCallback;
@protocol ARCreateConnectionCallback;

@interface ARManagedNetworkProvider : NSObject < ARNetworkRuntime >

#pragma mark Public

- (instancetype)initWithFactory:(id<ARAsyncConnectionFactory>)factory;

- (void)createConnectionWithId:(jint)connectionId
                 withMTVersion:(jint)mtprotoVersion
                  withApiMajor:(jint)apiMajorVersion
                  withApiMinor:(jint)apiMinorVersion
                  withEndpoint:(ARConnectionEndpoint *)endpoint
                  withCallback:(id<ARConnectionCallback>)callback
            withCreateCallback:(id<ARCreateConnectionCallback>)createCallback;

@end

J2OBJC_EMPTY_STATIC_INIT(ARManagedNetworkProvider)

FOUNDATION_EXPORT void ARManagedNetworkProvider_initWithFactory_(ARManagedNetworkProvider *self, id<ARAsyncConnectionFactory> factory);

FOUNDATION_EXPORT ARManagedNetworkProvider *new_ARManagedNetworkProvider_initWithFactory_(id<ARAsyncConnectionFactory> factory) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARManagedNetworkProvider *create_ARManagedNetworkProvider_initWithFactory_(id<ARAsyncConnectionFactory> factory);

J2OBJC_TYPE_LITERAL_HEADER(ARManagedNetworkProvider)

@compatibility_alias ImActorRuntimeMtprotoManagedNetworkProvider ARManagedNetworkProvider;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeMtprotoManagedNetworkProvider")
