//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/entity/AvatarImage.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEntityAvatarImage")
#ifdef RESTRICT_ImActorCoreEntityAvatarImage
#define INCLUDE_ALL_ImActorCoreEntityAvatarImage 0
#else
#define INCLUDE_ALL_ImActorCoreEntityAvatarImage 1
#endif
#undef RESTRICT_ImActorCoreEntityAvatarImage

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACAvatarImage_) && (INCLUDE_ALL_ImActorCoreEntityAvatarImage || defined(INCLUDE_ACAvatarImage))
#define ACAvatarImage_

#define RESTRICT_ImActorCoreEntityWrapperEntity 1
#define INCLUDE_ACWrapperEntity 1
#include "../../../../im/actor/core/entity/WrapperEntity.h"

@class ACFileReference;
@class ARApiAvatarImage;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ACAvatarImage : ACWrapperEntity
@property (readonly, nonatomic, getter=getWidth) jint width;
@property (readonly, nonatomic, getter=getHeight) jint height;
@property (readonly, nonatomic, getter=getFileReference) ACFileReference *fileReference;

#pragma mark Public

- (instancetype)initWithARApiAvatarImage:(ARApiAvatarImage * __nonnull)wrapped;

- (instancetype)initWithByteArray:(IOSByteArray * __nonnull)data;

- (jboolean)isEqual:(id)o;

- (ACFileReference * __nonnull)getFileReference;

- (jint)getHeight;

- (jint)getWidth;

- (NSUInteger)hash;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

#pragma mark Protected

- (void)applyWrappedWithARBserObject:(ARApiAvatarImage * __nonnull)wrapped;

- (ARApiAvatarImage * __nonnull)createInstance;

@end

J2OBJC_EMPTY_STATIC_INIT(ACAvatarImage)

FOUNDATION_EXPORT void ACAvatarImage_initWithARApiAvatarImage_(ACAvatarImage *self, ARApiAvatarImage *wrapped);

FOUNDATION_EXPORT ACAvatarImage *new_ACAvatarImage_initWithARApiAvatarImage_(ARApiAvatarImage *wrapped) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACAvatarImage *create_ACAvatarImage_initWithARApiAvatarImage_(ARApiAvatarImage *wrapped);

FOUNDATION_EXPORT void ACAvatarImage_initWithByteArray_(ACAvatarImage *self, IOSByteArray *data);

FOUNDATION_EXPORT ACAvatarImage *new_ACAvatarImage_initWithByteArray_(IOSByteArray *data) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACAvatarImage *create_ACAvatarImage_initWithByteArray_(IOSByteArray *data);

J2OBJC_TYPE_LITERAL_HEADER(ACAvatarImage)

@compatibility_alias ImActorCoreEntityAvatarImage ACAvatarImage;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEntityAvatarImage")
