//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/entity/FileReference.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEntityFileReference")
#ifdef RESTRICT_ImActorCoreEntityFileReference
#define INCLUDE_ALL_ImActorCoreEntityFileReference 0
#else
#define INCLUDE_ALL_ImActorCoreEntityFileReference 1
#endif
#undef RESTRICT_ImActorCoreEntityFileReference

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACFileReference_) && (INCLUDE_ALL_ImActorCoreEntityFileReference || defined(INCLUDE_ACFileReference))
#define ACFileReference_

#define RESTRICT_ImActorCoreEntityWrapperEntity 1
#define INCLUDE_ACWrapperEntity 1
#include "../../../../im/actor/core/entity/WrapperEntity.h"

@class ARApiFileLocation;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ACFileReference : ACWrapperEntity
@property (readonly, nonatomic, getter=getFileSize) jint fileSize;
@property (readonly, copy, nonatomic, getter=getFileName) NSString *fileName;

#pragma mark Public

- (instancetype)initWithARApiFileLocation:(ARApiFileLocation *)fileLocation
                             withNSString:(NSString *)fileName
                                  withInt:(jint)fileSize;

- (instancetype)initWithByteArray:(IOSByteArray *)data;

- (jboolean)isEqual:(id)o;

- (jlong)getAccessHash;

- (jlong)getFileId;

- (ARApiFileLocation *)getFileLocation;

- (NSString *)getFileName;

- (jint)getFileSize;

- (NSUInteger)hash;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

#pragma mark Protected

- (ARApiFileLocation * __nonnull)createInstance;

@end

J2OBJC_EMPTY_STATIC_INIT(ACFileReference)

FOUNDATION_EXPORT void ACFileReference_initWithARApiFileLocation_withNSString_withInt_(ACFileReference *self, ARApiFileLocation *fileLocation, NSString *fileName, jint fileSize);

FOUNDATION_EXPORT ACFileReference *new_ACFileReference_initWithARApiFileLocation_withNSString_withInt_(ARApiFileLocation *fileLocation, NSString *fileName, jint fileSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACFileReference *create_ACFileReference_initWithARApiFileLocation_withNSString_withInt_(ARApiFileLocation *fileLocation, NSString *fileName, jint fileSize);

FOUNDATION_EXPORT void ACFileReference_initWithByteArray_(ACFileReference *self, IOSByteArray *data);

FOUNDATION_EXPORT ACFileReference *new_ACFileReference_initWithByteArray_(IOSByteArray *data) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACFileReference *create_ACFileReference_initWithByteArray_(IOSByteArray *data);

J2OBJC_TYPE_LITERAL_HEADER(ACFileReference)

@compatibility_alias ImActorCoreEntityFileReference ACFileReference;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEntityFileReference")
