//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/entity/PhoneBookContact.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEntityPhoneBookContact")
#ifdef RESTRICT_ImActorCoreEntityPhoneBookContact
#define INCLUDE_ALL_ImActorCoreEntityPhoneBookContact 0
#else
#define INCLUDE_ALL_ImActorCoreEntityPhoneBookContact 1
#endif
#undef RESTRICT_ImActorCoreEntityPhoneBookContact

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACPhoneBookContact_) && (INCLUDE_ALL_ImActorCoreEntityPhoneBookContact || defined(INCLUDE_ACPhoneBookContact))
#define ACPhoneBookContact_

#define RESTRICT_ImActorRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/actor/runtime/bser/BserObject.h"

#define RESTRICT_ImActorRuntimeStorageListEngineItem 1
#define INCLUDE_ARListEngineItem 1
#include "../../../../im/actor/runtime/storage/ListEngineItem.h"

@class ARBserValues;
@class ARBserWriter;
@protocol ARBserCreator;
@protocol JavaUtilList;

@interface ACPhoneBookContact : ARBserObject < ARListEngineItem >
@property (readonly, nonatomic, getter=getContactId) jlong contactId;
@property (readonly, nonatomic) jlong sortId;
@property (readonly, copy, nonatomic, getter=getName) NSString *name;
@property (readonly, nonatomic, getter=getPhones) id<JavaUtilList> phones;
@property (readonly, nonatomic, getter=getEmails) id<JavaUtilList> emails;

+ (NSString *)ENTITY_NAME;

+ (id<ARBserCreator>)CREATOR;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)contactId
                withNSString:(NSString *)name
            withJavaUtilList:(id<JavaUtilList>)phones
            withJavaUtilList:(id<JavaUtilList>)emails;

- (instancetype)initWithLong:(jlong)contactId
                withNSString:(NSString *)name
            withJavaUtilList:(id<JavaUtilList>)phones
            withJavaUtilList:(id<JavaUtilList>)emails
                    withLong:(jlong)sortId;

- (jlong)getContactId;

- (id<JavaUtilList>)getEmails;

- (jlong)getEngineId;

- (NSString *)getEngineSearch;

- (jlong)getEngineSort;

- (NSString *)getName;

- (id<JavaUtilList>)getPhones;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (ACPhoneBookContact *)setSortIdWithLong:(jlong)sortId;

@end

J2OBJC_STATIC_INIT(ACPhoneBookContact)

inline NSString *ACPhoneBookContact_get_ENTITY_NAME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ACPhoneBookContact_ENTITY_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ACPhoneBookContact, ENTITY_NAME, NSString *)

inline id<ARBserCreator> ACPhoneBookContact_get_CREATOR();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<ARBserCreator> ACPhoneBookContact_CREATOR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ACPhoneBookContact, CREATOR, id<ARBserCreator>)

FOUNDATION_EXPORT void ACPhoneBookContact_initWithLong_withNSString_withJavaUtilList_withJavaUtilList_(ACPhoneBookContact *self, jlong contactId, NSString *name, id<JavaUtilList> phones, id<JavaUtilList> emails);

FOUNDATION_EXPORT ACPhoneBookContact *new_ACPhoneBookContact_initWithLong_withNSString_withJavaUtilList_withJavaUtilList_(jlong contactId, NSString *name, id<JavaUtilList> phones, id<JavaUtilList> emails) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhoneBookContact *create_ACPhoneBookContact_initWithLong_withNSString_withJavaUtilList_withJavaUtilList_(jlong contactId, NSString *name, id<JavaUtilList> phones, id<JavaUtilList> emails);

FOUNDATION_EXPORT void ACPhoneBookContact_initWithLong_withNSString_withJavaUtilList_withJavaUtilList_withLong_(ACPhoneBookContact *self, jlong contactId, NSString *name, id<JavaUtilList> phones, id<JavaUtilList> emails, jlong sortId);

FOUNDATION_EXPORT ACPhoneBookContact *new_ACPhoneBookContact_initWithLong_withNSString_withJavaUtilList_withJavaUtilList_withLong_(jlong contactId, NSString *name, id<JavaUtilList> phones, id<JavaUtilList> emails, jlong sortId) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhoneBookContact *create_ACPhoneBookContact_initWithLong_withNSString_withJavaUtilList_withJavaUtilList_withLong_(jlong contactId, NSString *name, id<JavaUtilList> phones, id<JavaUtilList> emails, jlong sortId);

FOUNDATION_EXPORT void ACPhoneBookContact_init(ACPhoneBookContact *self);

FOUNDATION_EXPORT ACPhoneBookContact *new_ACPhoneBookContact_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhoneBookContact *create_ACPhoneBookContact_init();

J2OBJC_TYPE_LITERAL_HEADER(ACPhoneBookContact)

@compatibility_alias ImActorCoreEntityPhoneBookContact ACPhoneBookContact;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEntityPhoneBookContact")
