//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/entity/PhoneBookPhone.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreEntityPhoneBookPhone")
#ifdef RESTRICT_ImActorCoreEntityPhoneBookPhone
#define INCLUDE_ALL_ImActorCoreEntityPhoneBookPhone 0
#else
#define INCLUDE_ALL_ImActorCoreEntityPhoneBookPhone 1
#endif
#undef RESTRICT_ImActorCoreEntityPhoneBookPhone

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACPhoneBookPhone_) && (INCLUDE_ALL_ImActorCoreEntityPhoneBookPhone || defined(INCLUDE_ACPhoneBookPhone))
#define ACPhoneBookPhone_

#define RESTRICT_ImActorRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/actor/runtime/bser/BserObject.h"

@class ARBserValues;
@class ARBserWriter;

@interface ACPhoneBookPhone : ARBserObject
@property (readonly, nonatomic) jlong id_;
@property (readonly, nonatomic, getter=getNumber) jlong number;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)id_
                    withLong:(jlong)number;

- (jlong)getId;

- (jlong)getNumber;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPhoneBookPhone)

FOUNDATION_EXPORT void ACPhoneBookPhone_initWithLong_withLong_(ACPhoneBookPhone *self, jlong id_, jlong number);

FOUNDATION_EXPORT ACPhoneBookPhone *new_ACPhoneBookPhone_initWithLong_withLong_(jlong id_, jlong number) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhoneBookPhone *create_ACPhoneBookPhone_initWithLong_withLong_(jlong id_, jlong number);

FOUNDATION_EXPORT void ACPhoneBookPhone_init(ACPhoneBookPhone *self);

FOUNDATION_EXPORT ACPhoneBookPhone *new_ACPhoneBookPhone_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhoneBookPhone *create_ACPhoneBookPhone_init();

J2OBJC_TYPE_LITERAL_HEADER(ACPhoneBookPhone)

@compatibility_alias ImActorCoreEntityPhoneBookPhone ACPhoneBookPhone;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreEntityPhoneBookPhone")
