//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/primitives/curve25519/fe_copy.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy")
#ifdef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoPrimitivesCurve25519fe_copy_) && (INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy || defined(INCLUDE_ImActorRuntimeCryptoPrimitivesCurve25519fe_copy))
#define ImActorRuntimeCryptoPrimitivesCurve25519fe_copy_

@class IOSIntArray;

@interface ImActorRuntimeCryptoPrimitivesCurve25519fe_copy : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)fe_copyWithIntArray:(IOSIntArray *)h
               withIntArray:(IOSIntArray *)f;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoPrimitivesCurve25519fe_copy)

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519fe_copy_fe_copyWithIntArray_withIntArray_(IOSIntArray *h, IOSIntArray *f);

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519fe_copy_init(ImActorRuntimeCryptoPrimitivesCurve25519fe_copy *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519fe_copy *new_ImActorRuntimeCryptoPrimitivesCurve25519fe_copy_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519fe_copy *create_ImActorRuntimeCryptoPrimitivesCurve25519fe_copy_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoPrimitivesCurve25519fe_copy)

@compatibility_alias ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy ImActorRuntimeCryptoPrimitivesCurve25519fe_copy;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_copy")
