//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/primitives/curve25519/fe_pow22523.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523")
#ifdef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523_) && (INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523 || defined(INCLUDE_ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523))
#define ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523_

@class IOSIntArray;

@interface ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523 : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)fe_pow22523WithIntArray:(IOSIntArray *)outArg
                   withIntArray:(IOSIntArray *)z;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523)

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523_fe_pow22523WithIntArray_withIntArray_(IOSIntArray *outArg, IOSIntArray *z);

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523_init(ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523 *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523 *new_ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523 *create_ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523)

@compatibility_alias ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523 ImActorRuntimeCryptoPrimitivesCurve25519fe_pow22523;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Fe_pow22523")
