//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/primitives/curve25519/ge_p2.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2")
#ifdef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoPrimitivesCurve25519ge_p2_) && (INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2 || defined(INCLUDE_ImActorRuntimeCryptoPrimitivesCurve25519ge_p2))
#define ImActorRuntimeCryptoPrimitivesCurve25519ge_p2_

@class IOSIntArray;

@interface ImActorRuntimeCryptoPrimitivesCurve25519ge_p2 : NSObject {
 @public
  IOSIntArray *X_;
  IOSIntArray *Y_;
  IOSIntArray *Z_;
}

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoPrimitivesCurve25519ge_p2)

J2OBJC_FIELD_SETTER(ImActorRuntimeCryptoPrimitivesCurve25519ge_p2, X_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ImActorRuntimeCryptoPrimitivesCurve25519ge_p2, Y_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ImActorRuntimeCryptoPrimitivesCurve25519ge_p2, Z_, IOSIntArray *)

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519ge_p2_init(ImActorRuntimeCryptoPrimitivesCurve25519ge_p2 *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519ge_p2 *new_ImActorRuntimeCryptoPrimitivesCurve25519ge_p2_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519ge_p2 *create_ImActorRuntimeCryptoPrimitivesCurve25519ge_p2_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoPrimitivesCurve25519ge_p2)

@compatibility_alias ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2 ImActorRuntimeCryptoPrimitivesCurve25519ge_p2;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_p2")
