//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/primitives/curve25519/ge_sub.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub")
#ifdef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoPrimitivesCurve25519ge_sub_) && (INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub || defined(INCLUDE_ImActorRuntimeCryptoPrimitivesCurve25519ge_sub))
#define ImActorRuntimeCryptoPrimitivesCurve25519ge_sub_

@class ImActorRuntimeCryptoPrimitivesCurve25519ge_cached;
@class ImActorRuntimeCryptoPrimitivesCurve25519ge_p1p1;
@class ImActorRuntimeCryptoPrimitivesCurve25519ge_p3;

@interface ImActorRuntimeCryptoPrimitivesCurve25519ge_sub : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)ge_subWithImActorRuntimeCryptoPrimitivesCurve25519ge_p1p1:(ImActorRuntimeCryptoPrimitivesCurve25519ge_p1p1 *)r
                withImActorRuntimeCryptoPrimitivesCurve25519ge_p3:(ImActorRuntimeCryptoPrimitivesCurve25519ge_p3 *)p
            withImActorRuntimeCryptoPrimitivesCurve25519ge_cached:(ImActorRuntimeCryptoPrimitivesCurve25519ge_cached *)q;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoPrimitivesCurve25519ge_sub)

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519ge_sub_ge_subWithImActorRuntimeCryptoPrimitivesCurve25519ge_p1p1_withImActorRuntimeCryptoPrimitivesCurve25519ge_p3_withImActorRuntimeCryptoPrimitivesCurve25519ge_cached_(ImActorRuntimeCryptoPrimitivesCurve25519ge_p1p1 *r, ImActorRuntimeCryptoPrimitivesCurve25519ge_p3 *p, ImActorRuntimeCryptoPrimitivesCurve25519ge_cached *q);

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519ge_sub_init(ImActorRuntimeCryptoPrimitivesCurve25519ge_sub *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519ge_sub *new_ImActorRuntimeCryptoPrimitivesCurve25519ge_sub_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519ge_sub *create_ImActorRuntimeCryptoPrimitivesCurve25519ge_sub_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoPrimitivesCurve25519ge_sub)

@compatibility_alias ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub ImActorRuntimeCryptoPrimitivesCurve25519ge_sub;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Ge_sub")
