//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/crypto/primitives/curve25519/scalarmult.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult")
#ifdef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult 0
#else
#define INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult 1
#endif
#undef RESTRICT_ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeCryptoPrimitivesCurve25519scalarmult_) && (INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult || defined(INCLUDE_ImActorRuntimeCryptoPrimitivesCurve25519scalarmult))
#define ImActorRuntimeCryptoPrimitivesCurve25519scalarmult_

@class IOSByteArray;

@interface ImActorRuntimeCryptoPrimitivesCurve25519scalarmult : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)crypto_scalarmultWithByteArray:(IOSByteArray *)q
                         withByteArray:(IOSByteArray *)n
                         withByteArray:(IOSByteArray *)p;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeCryptoPrimitivesCurve25519scalarmult)

FOUNDATION_EXPORT jint ImActorRuntimeCryptoPrimitivesCurve25519scalarmult_crypto_scalarmultWithByteArray_withByteArray_withByteArray_(IOSByteArray *q, IOSByteArray *n, IOSByteArray *p);

FOUNDATION_EXPORT void ImActorRuntimeCryptoPrimitivesCurve25519scalarmult_init(ImActorRuntimeCryptoPrimitivesCurve25519scalarmult *self);

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519scalarmult *new_ImActorRuntimeCryptoPrimitivesCurve25519scalarmult_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorRuntimeCryptoPrimitivesCurve25519scalarmult *create_ImActorRuntimeCryptoPrimitivesCurve25519scalarmult_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeCryptoPrimitivesCurve25519scalarmult)

@compatibility_alias ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult ImActorRuntimeCryptoPrimitivesCurve25519scalarmult;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCryptoPrimitivesCurve25519Scalarmult")
