//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/util/ActorTrace.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreUtilActorTrace")
#ifdef RESTRICT_ImActorCoreUtilActorTrace
#define INCLUDE_ALL_ImActorCoreUtilActorTrace 0
#else
#define INCLUDE_ALL_ImActorCoreUtilActorTrace 1
#endif
#undef RESTRICT_ImActorCoreUtilActorTrace

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACActorTrace_) && (INCLUDE_ALL_ImActorCoreUtilActorTrace || defined(INCLUDE_ACActorTrace))
#define ACActorTrace_

#define RESTRICT_ImActorRuntimeActorsTraceInterface 1
#define INCLUDE_ARTraceInterface 1
#include "../../../../im/actor/runtime/actors/TraceInterface.h"

@class ARActor;
@class ARActorRef;
@class ImActorRuntimeActorsDispatchEnvelope;
@class JavaLangException;

/*!
 @brief Actor System Trace Interface implementation for logging problems
 */
@interface ACActorTrace : NSObject < ARTraceInterface >

#pragma mark Public

- (instancetype)init;

- (void)onActorDieWithARActorRef:(ARActorRef *)ref
withImActorRuntimeActorsDispatchEnvelope:(ImActorRuntimeActorsDispatchEnvelope *)envelope
           withJavaLangException:(JavaLangException *)e;

- (void)onDeadLetterWithARActorRef:(ARActorRef *)receiver
                            withId:(id)message;

- (void)onDropWithARActorRef:(ARActorRef *)sender
                      withId:(id)message
                 withARActor:(ARActor *)actor;

- (void)onEnvelopeDeliveredWithImActorRuntimeActorsDispatchEnvelope:(ImActorRuntimeActorsDispatchEnvelope *)envelope;

- (void)onEnvelopeProcessedWithImActorRuntimeActorsDispatchEnvelope:(ImActorRuntimeActorsDispatchEnvelope *)envelope
                                                           withLong:(jlong)duration;

- (void)onMessageSentWithARActorRef:(ARActorRef *)ref
                             withId:(id)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ACActorTrace)

FOUNDATION_EXPORT void ACActorTrace_init(ACActorTrace *self);

FOUNDATION_EXPORT ACActorTrace *new_ACActorTrace_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACActorTrace *create_ACActorTrace_init();

J2OBJC_TYPE_LITERAL_HEADER(ACActorTrace)

@compatibility_alias ImActorCoreUtilActorTrace ACActorTrace;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreUtilActorTrace")
