//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/util/StringUtil.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreUtilStringUtil")
#ifdef RESTRICT_ImActorCoreUtilStringUtil
#define INCLUDE_ALL_ImActorCoreUtilStringUtil 0
#else
#define INCLUDE_ALL_ImActorCoreUtilStringUtil 1
#endif
#undef RESTRICT_ImActorCoreUtilStringUtil

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACStringUtil_) && (INCLUDE_ALL_ImActorCoreUtilStringUtil || defined(INCLUDE_ACStringUtil))
#define ACStringUtil_

@interface ACStringUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)ellipsizeWithNSString:(NSString *)src
                            withInt:(jint)maxLength;

+ (jboolean)isNullOrEmptyWithNSString:(NSString *)src;

@end

J2OBJC_EMPTY_STATIC_INIT(ACStringUtil)

FOUNDATION_EXPORT jboolean ACStringUtil_isNullOrEmptyWithNSString_(NSString *src);

FOUNDATION_EXPORT NSString *ACStringUtil_ellipsizeWithNSString_withInt_(NSString *src, jint maxLength);

FOUNDATION_EXPORT void ACStringUtil_init(ACStringUtil *self);

FOUNDATION_EXPORT ACStringUtil *new_ACStringUtil_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACStringUtil *create_ACStringUtil_init();

J2OBJC_TYPE_LITERAL_HEADER(ACStringUtil)

@compatibility_alias ImActorCoreUtilStringUtil ACStringUtil;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreUtilStringUtil")
