//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/util/Timing.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreUtilTiming")
#ifdef RESTRICT_ImActorCoreUtilTiming
#define INCLUDE_ALL_ImActorCoreUtilTiming 0
#else
#define INCLUDE_ALL_ImActorCoreUtilTiming 1
#endif
#undef RESTRICT_ImActorCoreUtilTiming

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACTiming_) && (INCLUDE_ALL_ImActorCoreUtilTiming || defined(INCLUDE_ACTiming))
#define ACTiming_

/*!
 @brief Calculation of execution duration
 */
@interface ACTiming : NSObject

#pragma mark Public

/*!
 @brief Create Timing
 @param tag tag for result log
 */
- (instancetype)initWithNSString:(NSString *)tag;

/*!
 @brief Mark section end
 */
- (void)end;

/*!
 @brief Mark new section start
 @param sectionName section name
 */
- (void)sectionWithNSString:(NSString *)sectionName;

@end

J2OBJC_EMPTY_STATIC_INIT(ACTiming)

FOUNDATION_EXPORT void ACTiming_initWithNSString_(ACTiming *self, NSString *tag);

FOUNDATION_EXPORT ACTiming *new_ACTiming_initWithNSString_(NSString *tag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACTiming *create_ACTiming_initWithNSString_(NSString *tag);

J2OBJC_TYPE_LITERAL_HEADER(ACTiming)

@compatibility_alias ImActorCoreUtilTiming ACTiming;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreUtilTiming")
