//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-cocoa/src/main/java/im/actor/runtime/cocoa/threading/CocoaDispatcherProxy.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeCocoaThreadingCocoaDispatcherProxy")
#ifdef RESTRICT_ImActorRuntimeCocoaThreadingCocoaDispatcherProxy
#define INCLUDE_ALL_ImActorRuntimeCocoaThreadingCocoaDispatcherProxy 0
#else
#define INCLUDE_ALL_ImActorRuntimeCocoaThreadingCocoaDispatcherProxy 1
#endif
#undef RESTRICT_ImActorRuntimeCocoaThreadingCocoaDispatcherProxy

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARCocoaDispatcherProxy_) && (INCLUDE_ALL_ImActorRuntimeCocoaThreadingCocoaDispatcherProxy || defined(INCLUDE_ARCocoaDispatcherProxy))
#define ARCocoaDispatcherProxy_

@protocol ARDispatchCancel;
@protocol JavaLangRunnable;

@protocol ARCocoaDispatcherProxy < NSObject, JavaObject >

- (id<ARDispatchCancel>)dispatchOnBackground:(id<JavaLangRunnable>)runnable
                                   withDelay:(jlong)delay;

@end

J2OBJC_EMPTY_STATIC_INIT(ARCocoaDispatcherProxy)

J2OBJC_TYPE_LITERAL_HEADER(ARCocoaDispatcherProxy)

#define ImActorRuntimeCocoaThreadingCocoaDispatcherProxy ARCocoaDispatcherProxy

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeCocoaThreadingCocoaDispatcherProxy")
