//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/actors/messages/StartActor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeActorsMessagesStartActor")
#ifdef RESTRICT_ImActorRuntimeActorsMessagesStartActor
#define INCLUDE_ALL_ImActorRuntimeActorsMessagesStartActor 0
#else
#define INCLUDE_ALL_ImActorRuntimeActorsMessagesStartActor 1
#endif
#undef RESTRICT_ImActorRuntimeActorsMessagesStartActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARStartActor_) && (INCLUDE_ALL_ImActorRuntimeActorsMessagesStartActor || defined(INCLUDE_ARStartActor))
#define ARStartActor_

/*!
 @brief Message for starting actors
 */
@interface ARStartActor : NSObject

+ (ARStartActor *)INSTANCE;

#pragma mark Public

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(ARStartActor)

inline ARStartActor *ARStartActor_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ARStartActor *ARStartActor_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ARStartActor, INSTANCE, ARStartActor *)

J2OBJC_TYPE_LITERAL_HEADER(ARStartActor)

@compatibility_alias ImActorRuntimeActorsMessagesStartActor ARStartActor;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeActorsMessagesStartActor")
