//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/messaging/history/DialogsHistoryActor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesMessagingHistoryDialogsHistoryActor")
#ifdef RESTRICT_ImActorCoreModulesMessagingHistoryDialogsHistoryActor
#define INCLUDE_ALL_ImActorCoreModulesMessagingHistoryDialogsHistoryActor 0
#else
#define INCLUDE_ALL_ImActorCoreModulesMessagingHistoryDialogsHistoryActor 1
#endif
#undef RESTRICT_ImActorCoreModulesMessagingHistoryDialogsHistoryActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesMessagingHistoryDialogsHistoryActor_) && (INCLUDE_ALL_ImActorCoreModulesMessagingHistoryDialogsHistoryActor || defined(INCLUDE_ImActorCoreModulesMessagingHistoryDialogsHistoryActor))
#define ImActorCoreModulesMessagingHistoryDialogsHistoryActor_

#define RESTRICT_ImActorCoreModulesModuleActor 1
#define INCLUDE_ACModuleActor 1
#include "../../../../../../im/actor/core/modules/ModuleActor.h"

@protocol ACModuleContext;

@interface ImActorCoreModulesMessagingHistoryDialogsHistoryActor : ACModuleActor

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)onReceiveWithId:(id)message;

- (void)preStart;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesMessagingHistoryDialogsHistoryActor)

FOUNDATION_EXPORT void ImActorCoreModulesMessagingHistoryDialogsHistoryActor_initWithACModuleContext_(ImActorCoreModulesMessagingHistoryDialogsHistoryActor *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImActorCoreModulesMessagingHistoryDialogsHistoryActor *new_ImActorCoreModulesMessagingHistoryDialogsHistoryActor_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesMessagingHistoryDialogsHistoryActor *create_ImActorCoreModulesMessagingHistoryDialogsHistoryActor_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesMessagingHistoryDialogsHistoryActor)

#endif

#if !defined (ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore_) && (INCLUDE_ALL_ImActorCoreModulesMessagingHistoryDialogsHistoryActor || defined(INCLUDE_ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore))
#define ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore_

@interface ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore)

FOUNDATION_EXPORT void ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore_init(ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore *self);

FOUNDATION_EXPORT ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore *new_ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore *create_ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore_init();

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesMessagingHistoryDialogsHistoryActor_LoadMore)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesMessagingHistoryDialogsHistoryActor")
