//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/markdown/MDText.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeMarkdownMDText")
#ifdef RESTRICT_ImActorRuntimeMarkdownMDText
#define INCLUDE_ALL_ImActorRuntimeMarkdownMDText 0
#else
#define INCLUDE_ALL_ImActorRuntimeMarkdownMDText 1
#endif
#undef RESTRICT_ImActorRuntimeMarkdownMDText

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARMDText_) && (INCLUDE_ALL_ImActorRuntimeMarkdownMDText || defined(INCLUDE_ARMDText))
#define ARMDText_

@interface ARMDText : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)toMarkdown;

@end

J2OBJC_EMPTY_STATIC_INIT(ARMDText)

FOUNDATION_EXPORT void ARMDText_init(ARMDText *self);

J2OBJC_TYPE_LITERAL_HEADER(ARMDText)

@compatibility_alias ImActorRuntimeMarkdownMDText ARMDText;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeMarkdownMDText")
