//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/stickers/StickersActor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesStickersStickersActor")
#ifdef RESTRICT_ImActorCoreModulesStickersStickersActor
#define INCLUDE_ALL_ImActorCoreModulesStickersStickersActor 0
#else
#define INCLUDE_ALL_ImActorCoreModulesStickersStickersActor 1
#endif
#undef RESTRICT_ImActorCoreModulesStickersStickersActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesStickersStickersActor_) && (INCLUDE_ALL_ImActorCoreModulesStickersStickersActor || defined(INCLUDE_ImActorCoreModulesStickersStickersActor))
#define ImActorCoreModulesStickersStickersActor_

#define RESTRICT_ImActorCoreModulesModuleActor 1
#define INCLUDE_ACModuleActor 1
#include "../../../../../im/actor/core/modules/ModuleActor.h"

@protocol ACModuleContext;

@interface ImActorCoreModulesStickersStickersActor : ACModuleActor

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)onReceiveWithId:(id)message;

- (void)preStart;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesStickersStickersActor)

FOUNDATION_EXPORT void ImActorCoreModulesStickersStickersActor_initWithACModuleContext_(ImActorCoreModulesStickersStickersActor *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersActor *new_ImActorCoreModulesStickersStickersActor_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersActor *create_ImActorCoreModulesStickersStickersActor_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesStickersStickersActor)

#endif

#if !defined (ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged_) && (INCLUDE_ALL_ImActorCoreModulesStickersStickersActor || defined(INCLUDE_ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged))
#define ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged_

@protocol JavaUtilList;

@interface ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged : NSObject

#pragma mark Public

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)ownStickers;

- (id<JavaUtilList>)getOwnStickers;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged)

FOUNDATION_EXPORT void ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged_initWithJavaUtilList_(ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged *self, id<JavaUtilList> ownStickers);

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged *new_ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged_initWithJavaUtilList_(id<JavaUtilList> ownStickers) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged *create_ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged_initWithJavaUtilList_(id<JavaUtilList> ownStickers);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesStickersStickersActor_OwnStickerCollectionsChanged)

#endif

#if !defined (ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged_) && (INCLUDE_ALL_ImActorCoreModulesStickersStickersActor || defined(INCLUDE_ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged))
#define ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged_

@protocol JavaUtilList;

@interface ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged : NSObject

#pragma mark Public

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)updated;

- (id<JavaUtilList>)getUpdated;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged)

FOUNDATION_EXPORT void ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged_initWithJavaUtilList_(ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged *self, id<JavaUtilList> updated);

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged *new_ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged_initWithJavaUtilList_(id<JavaUtilList> updated) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged *create_ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged_initWithJavaUtilList_(id<JavaUtilList> updated);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesStickersStickersActor_StickerCollectionsChanged)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesStickersStickersActor")
