//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/stickers/StickersProcessor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesStickersStickersProcessor")
#ifdef RESTRICT_ImActorCoreModulesStickersStickersProcessor
#define INCLUDE_ALL_ImActorCoreModulesStickersStickersProcessor 0
#else
#define INCLUDE_ALL_ImActorCoreModulesStickersStickersProcessor 1
#endif
#undef RESTRICT_ImActorCoreModulesStickersStickersProcessor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesStickersStickersProcessor_) && (INCLUDE_ALL_ImActorCoreModulesStickersStickersProcessor || defined(INCLUDE_ImActorCoreModulesStickersStickersProcessor))
#define ImActorCoreModulesStickersStickersProcessor_

#define RESTRICT_ImActorCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/actor/core/modules/AbsModule.h"

#define RESTRICT_ImActorCoreModulesSequenceProcessorSequenceProcessor 1
#define INCLUDE_ImActorCoreModulesSequenceProcessorSequenceProcessor 1
#include "../../../../../im/actor/core/modules/sequence/processor/SequenceProcessor.h"

@class ACUpdate;
@protocol ACModuleContext;
@protocol JavaUtilList;

@interface ImActorCoreModulesStickersStickersProcessor : ACAbsModule < ImActorCoreModulesSequenceProcessorSequenceProcessor >

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)modules;

- (void)onOwnStickerCollectionsChangedWithJavaUtilList:(id<JavaUtilList>)updated;

- (void)onStickerCollectionsChangedWithJavaUtilList:(id<JavaUtilList>)updated;

- (jboolean)processWithACUpdate:(ACUpdate *)update;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesStickersStickersProcessor)

FOUNDATION_EXPORT void ImActorCoreModulesStickersStickersProcessor_initWithACModuleContext_(ImActorCoreModulesStickersStickersProcessor *self, id<ACModuleContext> modules);

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersProcessor *new_ImActorCoreModulesStickersStickersProcessor_initWithACModuleContext_(id<ACModuleContext> modules) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesStickersStickersProcessor *create_ImActorCoreModulesStickersStickersProcessor_initWithACModuleContext_(id<ACModuleContext> modules);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesStickersStickersProcessor)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesStickersStickersProcessor")
