//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/network/mtp/entity/rpc/RpcFloodWait.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreNetworkMtpEntityRpcRpcFloodWait")
#ifdef RESTRICT_ImActorCoreNetworkMtpEntityRpcRpcFloodWait
#define INCLUDE_ALL_ImActorCoreNetworkMtpEntityRpcRpcFloodWait 0
#else
#define INCLUDE_ALL_ImActorCoreNetworkMtpEntityRpcRpcFloodWait 1
#endif
#undef RESTRICT_ImActorCoreNetworkMtpEntityRpcRpcFloodWait

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACRpcFloodWait_) && (INCLUDE_ALL_ImActorCoreNetworkMtpEntityRpcRpcFloodWait || defined(INCLUDE_ACRpcFloodWait))
#define ACRpcFloodWait_

#define RESTRICT_ImActorCoreNetworkMtpEntityProtoStruct 1
#define INCLUDE_ACProtoStruct 1
#include "../../../../../../../im/actor/core/network/mtp/entity/ProtoStruct.h"

@class ARDataInput;
@class ARDataOutput;

@interface ACRpcFloodWait : ACProtoStruct

+ (jbyte)HEADER;

#pragma mark Public

- (instancetype)initWithARDataInput:(ARDataInput *)stream;

- (instancetype)initWithInt:(jint)delay;

- (jint)getDelay;

#pragma mark Protected

- (jbyte)getHeader;

- (void)readBodyWithARDataInput:(ARDataInput *)bs;

- (void)writeBodyWithARDataOutput:(ARDataOutput *)bs;

@end

J2OBJC_EMPTY_STATIC_INIT(ACRpcFloodWait)

inline jbyte ACRpcFloodWait_get_HEADER();
#define ACRpcFloodWait_HEADER 3
J2OBJC_STATIC_FIELD_CONSTANT(ACRpcFloodWait, HEADER, jbyte)

FOUNDATION_EXPORT void ACRpcFloodWait_initWithARDataInput_(ACRpcFloodWait *self, ARDataInput *stream);

FOUNDATION_EXPORT ACRpcFloodWait *new_ACRpcFloodWait_initWithARDataInput_(ARDataInput *stream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACRpcFloodWait *create_ACRpcFloodWait_initWithARDataInput_(ARDataInput *stream);

FOUNDATION_EXPORT void ACRpcFloodWait_initWithInt_(ACRpcFloodWait *self, jint delay);

FOUNDATION_EXPORT ACRpcFloodWait *new_ACRpcFloodWait_initWithInt_(jint delay) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACRpcFloodWait *create_ACRpcFloodWait_initWithInt_(jint delay);

J2OBJC_TYPE_LITERAL_HEADER(ACRpcFloodWait)

@compatibility_alias ImActorCoreNetworkMtpEntityRpcRpcFloodWait ACRpcFloodWait;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreNetworkMtpEntityRpcRpcFloodWait")
