//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/annotations/MainThread.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeAnnotationsMainThread")
#ifdef RESTRICT_ImActorRuntimeAnnotationsMainThread
#define INCLUDE_ALL_ImActorRuntimeAnnotationsMainThread 0
#else
#define INCLUDE_ALL_ImActorRuntimeAnnotationsMainThread 1
#endif
#undef RESTRICT_ImActorRuntimeAnnotationsMainThread

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARMainThread_) && (INCLUDE_ALL_ImActorRuntimeAnnotationsMainThread || defined(INCLUDE_ARMainThread))
#define ARMainThread_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
@import j2objc;

@protocol ARMainThread < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ARMainThread)

J2OBJC_TYPE_LITERAL_HEADER(ARMainThread)

#define ImActorRuntimeAnnotationsMainThread ARMainThread

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeAnnotationsMainThread")
