//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/annotations/Stable.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeAnnotationsStable")
#ifdef RESTRICT_ImActorRuntimeAnnotationsStable
#define INCLUDE_ALL_ImActorRuntimeAnnotationsStable 0
#else
#define INCLUDE_ALL_ImActorRuntimeAnnotationsStable 1
#endif
#undef RESTRICT_ImActorRuntimeAnnotationsStable

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARStable_) && (INCLUDE_ALL_ImActorRuntimeAnnotationsStable || defined(INCLUDE_ARStable))
#define ARStable_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
@import j2objc;

/*!
 @brief Annotation about stable interfaces
 */
@protocol ARStable < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ARStable)

J2OBJC_TYPE_LITERAL_HEADER(ARStable)

#define ImActorRuntimeAnnotationsStable ARStable

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeAnnotationsStable")
