//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/encryption/entity/SessionId.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesEncryptionEntitySessionId")
#ifdef RESTRICT_ImActorCoreModulesEncryptionEntitySessionId
#define INCLUDE_ALL_ImActorCoreModulesEncryptionEntitySessionId 0
#else
#define INCLUDE_ALL_ImActorCoreModulesEncryptionEntitySessionId 1
#endif
#undef RESTRICT_ImActorCoreModulesEncryptionEntitySessionId

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesEncryptionEntitySessionId_) && (INCLUDE_ALL_ImActorCoreModulesEncryptionEntitySessionId || defined(INCLUDE_ImActorCoreModulesEncryptionEntitySessionId))
#define ImActorCoreModulesEncryptionEntitySessionId_

@interface ImActorCoreModulesEncryptionEntitySessionId : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)ownKeyGroupId
                   withLong:(jlong)ownKeyId0
                    withInt:(jint)theirKeyGroupId
                   withLong:(jlong)theirKeyId0;

- (jboolean)isEqual:(id)o;

- (jint)getOwnKeyGroupId;

- (jlong)getOwnKeyId0;

- (jint)getTheirKeyGroupId;

- (jlong)getTheirKeyId0;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesEncryptionEntitySessionId)

FOUNDATION_EXPORT void ImActorCoreModulesEncryptionEntitySessionId_initWithInt_withLong_withInt_withLong_(ImActorCoreModulesEncryptionEntitySessionId *self, jint ownKeyGroupId, jlong ownKeyId0, jint theirKeyGroupId, jlong theirKeyId0);

FOUNDATION_EXPORT ImActorCoreModulesEncryptionEntitySessionId *new_ImActorCoreModulesEncryptionEntitySessionId_initWithInt_withLong_withInt_withLong_(jint ownKeyGroupId, jlong ownKeyId0, jint theirKeyGroupId, jlong theirKeyId0) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesEncryptionEntitySessionId *create_ImActorCoreModulesEncryptionEntitySessionId_initWithInt_withLong_withInt_withLong_(jint ownKeyGroupId, jlong ownKeyId0, jint theirKeyGroupId, jlong theirKeyId0);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEncryptionEntitySessionId)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesEncryptionEntitySessionId")
