//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/api/PreferenceApiStorage.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesApiPreferenceApiStorage")
#ifdef RESTRICT_ImActorCoreModulesApiPreferenceApiStorage
#define INCLUDE_ALL_ImActorCoreModulesApiPreferenceApiStorage 0
#else
#define INCLUDE_ALL_ImActorCoreModulesApiPreferenceApiStorage 1
#endif
#undef RESTRICT_ImActorCoreModulesApiPreferenceApiStorage

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesApiPreferenceApiStorage_) && (INCLUDE_ALL_ImActorCoreModulesApiPreferenceApiStorage || defined(INCLUDE_ImActorCoreModulesApiPreferenceApiStorage))
#define ImActorCoreModulesApiPreferenceApiStorage_

#define RESTRICT_ImActorCoreNetworkAuthKeyStorage 1
#define INCLUDE_ACAuthKeyStorage 1
#include "../../../../../im/actor/core/network/AuthKeyStorage.h"

@class IOSByteArray;
@protocol ARPreferencesStorage;

@interface ImActorCoreModulesApiPreferenceApiStorage : NSObject < ACAuthKeyStorage >

#pragma mark Public

- (instancetype)initWithARPreferencesStorage:(id<ARPreferencesStorage>)preferencesStorage;

- (jlong)getAuthKey;

- (IOSByteArray *)getAuthMasterKey;

- (void)saveAuthKey:(jlong)key;

- (void)saveMasterKey:(IOSByteArray *)masterKey;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesApiPreferenceApiStorage)

FOUNDATION_EXPORT void ImActorCoreModulesApiPreferenceApiStorage_initWithARPreferencesStorage_(ImActorCoreModulesApiPreferenceApiStorage *self, id<ARPreferencesStorage> preferencesStorage);

FOUNDATION_EXPORT ImActorCoreModulesApiPreferenceApiStorage *new_ImActorCoreModulesApiPreferenceApiStorage_initWithARPreferencesStorage_(id<ARPreferencesStorage> preferencesStorage) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesApiPreferenceApiStorage *create_ImActorCoreModulesApiPreferenceApiStorage_initWithARPreferencesStorage_(id<ARPreferencesStorage> preferencesStorage);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesApiPreferenceApiStorage)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesApiPreferenceApiStorage")
