//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/eventbus/BusSubscriber.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeEventbusBusSubscriber")
#ifdef RESTRICT_ImActorRuntimeEventbusBusSubscriber
#define INCLUDE_ALL_ImActorRuntimeEventbusBusSubscriber 0
#else
#define INCLUDE_ALL_ImActorRuntimeEventbusBusSubscriber 1
#endif
#undef RESTRICT_ImActorRuntimeEventbusBusSubscriber

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeEventbusBusSubscriber_) && (INCLUDE_ALL_ImActorRuntimeEventbusBusSubscriber || defined(INCLUDE_ImActorRuntimeEventbusBusSubscriber))
#define ImActorRuntimeEventbusBusSubscriber_

@class ImActorRuntimeEventbusEvent;

@protocol ImActorRuntimeEventbusBusSubscriber < NSObject, JavaObject >

/*!
 @brief Handling event.
 Unsubscribing during calling this method is unsupported.
 @param event event value
 */
- (void)onBusEventWithImActorRuntimeEventbusEvent:(ImActorRuntimeEventbusEvent *)event;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeEventbusBusSubscriber)

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeEventbusBusSubscriber)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeEventbusBusSubscriber")
