//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java/im/actor/runtime/eventbus/Event.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeEventbusEvent")
#ifdef RESTRICT_ImActorRuntimeEventbusEvent
#define INCLUDE_ALL_ImActorRuntimeEventbusEvent 0
#else
#define INCLUDE_ALL_ImActorRuntimeEventbusEvent 1
#endif
#undef RESTRICT_ImActorRuntimeEventbusEvent

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorRuntimeEventbusEvent_) && (INCLUDE_ALL_ImActorRuntimeEventbusEvent || defined(INCLUDE_ImActorRuntimeEventbusEvent))
#define ImActorRuntimeEventbusEvent_

@interface ImActorRuntimeEventbusEvent : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)getType;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeEventbusEvent)

FOUNDATION_EXPORT void ImActorRuntimeEventbusEvent_init(ImActorRuntimeEventbusEvent *self);

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeEventbusEvent)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeEventbusEvent")
