//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/misc/DeviceInfoModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesMiscDeviceInfoModule")
#ifdef RESTRICT_ImActorCoreModulesMiscDeviceInfoModule
#define INCLUDE_ALL_ImActorCoreModulesMiscDeviceInfoModule 0
#else
#define INCLUDE_ALL_ImActorCoreModulesMiscDeviceInfoModule 1
#endif
#undef RESTRICT_ImActorCoreModulesMiscDeviceInfoModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesMiscDeviceInfoModule_) && (INCLUDE_ALL_ImActorCoreModulesMiscDeviceInfoModule || defined(INCLUDE_ImActorCoreModulesMiscDeviceInfoModule))
#define ImActorCoreModulesMiscDeviceInfoModule_

#define RESTRICT_ImActorCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/actor/core/modules/AbsModule.h"

@protocol ACModuleContext;

@interface ImActorCoreModulesMiscDeviceInfoModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesMiscDeviceInfoModule)

FOUNDATION_EXPORT void ImActorCoreModulesMiscDeviceInfoModule_initWithACModuleContext_(ImActorCoreModulesMiscDeviceInfoModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImActorCoreModulesMiscDeviceInfoModule *new_ImActorCoreModulesMiscDeviceInfoModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesMiscDeviceInfoModule *create_ImActorCoreModulesMiscDeviceInfoModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesMiscDeviceInfoModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesMiscDeviceInfoModule")
