//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/viewmodel/generics/AvatarValueModel.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreViewmodelGenericsAvatarValueModel")
#ifdef RESTRICT_ImActorCoreViewmodelGenericsAvatarValueModel
#define INCLUDE_ALL_ImActorCoreViewmodelGenericsAvatarValueModel 0
#else
#define INCLUDE_ALL_ImActorCoreViewmodelGenericsAvatarValueModel 1
#endif
#undef RESTRICT_ImActorCoreViewmodelGenericsAvatarValueModel

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACAvatarValueModel_) && (INCLUDE_ALL_ImActorCoreViewmodelGenericsAvatarValueModel || defined(INCLUDE_ACAvatarValueModel))
#define ACAvatarValueModel_

#define RESTRICT_ImActorRuntimeMvvmValueModel 1
#define INCLUDE_ARValueModel 1
#include "../../../../../im/actor/runtime/mvvm/ValueModel.h"

@class ACAvatar;

@interface ACAvatarValueModel : ARValueModel

#pragma mark Public

/*!
 @brief Create ValueModel
 @param name         name of variable
 @param defaultValue default value
 */
- (instancetype)initWithNSString:(NSString *)name
                    withACAvatar:(ACAvatar *)defaultValue;

- (ACAvatar *)get;

@end

J2OBJC_EMPTY_STATIC_INIT(ACAvatarValueModel)

FOUNDATION_EXPORT void ACAvatarValueModel_initWithNSString_withACAvatar_(ACAvatarValueModel *self, NSString *name, ACAvatar *defaultValue);

FOUNDATION_EXPORT ACAvatarValueModel *new_ACAvatarValueModel_initWithNSString_withACAvatar_(NSString *name, ACAvatar *defaultValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACAvatarValueModel *create_ACAvatarValueModel_initWithNSString_withACAvatar_(NSString *name, ACAvatar *defaultValue);

J2OBJC_TYPE_LITERAL_HEADER(ACAvatarValueModel)

@compatibility_alias ImActorCoreViewmodelGenericsAvatarValueModel ACAvatarValueModel;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreViewmodelGenericsAvatarValueModel")
