//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/viewmodel/generics/IntValueModel.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreViewmodelGenericsIntValueModel")
#ifdef RESTRICT_ImActorCoreViewmodelGenericsIntValueModel
#define INCLUDE_ALL_ImActorCoreViewmodelGenericsIntValueModel 0
#else
#define INCLUDE_ALL_ImActorCoreViewmodelGenericsIntValueModel 1
#endif
#undef RESTRICT_ImActorCoreViewmodelGenericsIntValueModel

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACIntValueModel_) && (INCLUDE_ALL_ImActorCoreViewmodelGenericsIntValueModel || defined(INCLUDE_ACIntValueModel))
#define ACIntValueModel_

#define RESTRICT_ImActorRuntimeMvvmValueModel 1
#define INCLUDE_ARValueModel 1
#include "../../../../../im/actor/runtime/mvvm/ValueModel.h"

@class JavaLangInteger;

@interface ACIntValueModel : ARValueModel

#pragma mark Public

/*!
 @brief Create ValueModel
 @param name         name of variable
 @param defaultValue default value
 */
- (instancetype)initWithNSString:(NSString *)name
             withJavaLangInteger:(JavaLangInteger *)defaultValue;

- (JavaLangInteger *)get;

@end

J2OBJC_EMPTY_STATIC_INIT(ACIntValueModel)

FOUNDATION_EXPORT void ACIntValueModel_initWithNSString_withJavaLangInteger_(ACIntValueModel *self, NSString *name, JavaLangInteger *defaultValue);

FOUNDATION_EXPORT ACIntValueModel *new_ACIntValueModel_initWithNSString_withJavaLangInteger_(NSString *name, JavaLangInteger *defaultValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACIntValueModel *create_ACIntValueModel_initWithNSString_withJavaLangInteger_(NSString *name, JavaLangInteger *defaultValue);

J2OBJC_TYPE_LITERAL_HEADER(ACIntValueModel)

@compatibility_alias ImActorCoreViewmodelGenericsIntValueModel ACIntValueModel;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreViewmodelGenericsIntValueModel")
