//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/runtime/runtime-generic/src/main/java/im/actor/runtime/generic/mvvm/alg/Modification.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorRuntimeGenericMvvmAlgModification")
#ifdef RESTRICT_ImActorRuntimeGenericMvvmAlgModification
#define INCLUDE_ALL_ImActorRuntimeGenericMvvmAlgModification 0
#else
#define INCLUDE_ALL_ImActorRuntimeGenericMvvmAlgModification 1
#endif
#undef RESTRICT_ImActorRuntimeGenericMvvmAlgModification

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARModification_) && (INCLUDE_ALL_ImActorRuntimeGenericMvvmAlgModification || defined(INCLUDE_ARModification))
#define ARModification_

@class JavaUtilArrayList;
@protocol JavaUtilList;

@protocol ARModification < NSObject, JavaObject >

- (id<JavaUtilList>)modifyWithJavaUtilArrayList:(JavaUtilArrayList *)sourceList;

@end

J2OBJC_EMPTY_STATIC_INIT(ARModification)

J2OBJC_TYPE_LITERAL_HEADER(ARModification)

#define ImActorRuntimeGenericMvvmAlgModification ARModification

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorRuntimeGenericMvvmAlgModification")
