//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/messaging/router/entity/RouterChangedReactions.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions")
#ifdef RESTRICT_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions
#define INCLUDE_ALL_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions 0
#else
#define INCLUDE_ALL_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions 1
#endif
#undef RESTRICT_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesMessagingRouterEntityRouterChangedReactions_) && (INCLUDE_ALL_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions || defined(INCLUDE_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions))
#define ImActorCoreModulesMessagingRouterEntityRouterChangedReactions_

#define RESTRICT_ImActorCoreModulesMessagingRouterEntityRouterMessageOnlyActive 1
#define INCLUDE_ImActorCoreModulesMessagingRouterEntityRouterMessageOnlyActive 1
#include "../../../../../../../im/actor/core/modules/messaging/router/entity/RouterMessageOnlyActive.h"

@class ACPeer;
@protocol JavaUtilList;

@interface ImActorCoreModulesMessagingRouterEntityRouterChangedReactions : NSObject < ImActorCoreModulesMessagingRouterEntityRouterMessageOnlyActive >

#pragma mark Public

- (instancetype)initWithACPeer:(ACPeer *)peer
                      withLong:(jlong)rid
              withJavaUtilList:(id<JavaUtilList>)reactions;

- (ACPeer *)getPeer;

- (id<JavaUtilList>)getReactions;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesMessagingRouterEntityRouterChangedReactions)

FOUNDATION_EXPORT void ImActorCoreModulesMessagingRouterEntityRouterChangedReactions_initWithACPeer_withLong_withJavaUtilList_(ImActorCoreModulesMessagingRouterEntityRouterChangedReactions *self, ACPeer *peer, jlong rid, id<JavaUtilList> reactions);

FOUNDATION_EXPORT ImActorCoreModulesMessagingRouterEntityRouterChangedReactions *new_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions_initWithACPeer_withLong_withJavaUtilList_(ACPeer *peer, jlong rid, id<JavaUtilList> reactions) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesMessagingRouterEntityRouterChangedReactions *create_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions_initWithACPeer_withLong_withJavaUtilList_(ACPeer *peer, jlong rid, id<JavaUtilList> reactions);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesMessagingRouterEntityRouterChangedReactions)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesMessagingRouterEntityRouterChangedReactions")
