//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/encryption/Configuration.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesEncryptionConfiguration")
#ifdef RESTRICT_ImActorCoreModulesEncryptionConfiguration
#define INCLUDE_ALL_ImActorCoreModulesEncryptionConfiguration 0
#else
#define INCLUDE_ALL_ImActorCoreModulesEncryptionConfiguration 1
#endif
#undef RESTRICT_ImActorCoreModulesEncryptionConfiguration

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesEncryptionConfiguration_) && (INCLUDE_ALL_ImActorCoreModulesEncryptionConfiguration || defined(INCLUDE_ImActorCoreModulesEncryptionConfiguration))
#define ImActorCoreModulesEncryptionConfiguration_

@class JavaUtilArrayList;

@interface ImActorCoreModulesEncryptionConfiguration : NSObject

+ (jint)EPHEMERAL_KEYS_COUNT;

+ (JavaUtilArrayList *)SUPPORTED;

@end

J2OBJC_STATIC_INIT(ImActorCoreModulesEncryptionConfiguration)

inline jint ImActorCoreModulesEncryptionConfiguration_get_EPHEMERAL_KEYS_COUNT();
#define ImActorCoreModulesEncryptionConfiguration_EPHEMERAL_KEYS_COUNT 100
J2OBJC_STATIC_FIELD_CONSTANT(ImActorCoreModulesEncryptionConfiguration, EPHEMERAL_KEYS_COUNT, jint)

inline JavaUtilArrayList *ImActorCoreModulesEncryptionConfiguration_get_SUPPORTED();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaUtilArrayList *ImActorCoreModulesEncryptionConfiguration_SUPPORTED;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ImActorCoreModulesEncryptionConfiguration, SUPPORTED, JavaUtilArrayList *)

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesEncryptionConfiguration)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesEncryptionConfiguration")
