//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/viewmodel/UploadFileVMCallback.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreViewmodelUploadFileVMCallback")
#ifdef RESTRICT_ImActorCoreViewmodelUploadFileVMCallback
#define INCLUDE_ALL_ImActorCoreViewmodelUploadFileVMCallback 0
#else
#define INCLUDE_ALL_ImActorCoreViewmodelUploadFileVMCallback 1
#endif
#undef RESTRICT_ImActorCoreViewmodelUploadFileVMCallback

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACUploadFileVMCallback_) && (INCLUDE_ALL_ImActorCoreViewmodelUploadFileVMCallback || defined(INCLUDE_ACUploadFileVMCallback))
#define ACUploadFileVMCallback_

/*!
 @brief Upload file View Model callback.
 Methods always called on Main thread.
 */
@protocol ACUploadFileVMCallback < NSObject, JavaObject >

/*!
 @brief On File not uploading
 */
- (void)onNotUploaded;

/*!
 @brief On File upload in progress
 @param progress progress value in [0..1]
 */
- (void)onUploading:(jfloat)progress;

/*!
 @brief On file uploaded
 */
- (void)onUploaded;

@end

J2OBJC_EMPTY_STATIC_INIT(ACUploadFileVMCallback)

J2OBJC_TYPE_LITERAL_HEADER(ACUploadFileVMCallback)

#define ImActorCoreViewmodelUploadFileVMCallback ACUploadFileVMCallback

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreViewmodelUploadFileVMCallback")
