//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/security/SecurityModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesSecuritySecurityModule")
#ifdef RESTRICT_ImActorCoreModulesSecuritySecurityModule
#define INCLUDE_ALL_ImActorCoreModulesSecuritySecurityModule 0
#else
#define INCLUDE_ALL_ImActorCoreModulesSecuritySecurityModule 1
#endif
#undef RESTRICT_ImActorCoreModulesSecuritySecurityModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesSecuritySecurityModule_) && (INCLUDE_ALL_ImActorCoreModulesSecuritySecurityModule || defined(INCLUDE_ImActorCoreModulesSecuritySecurityModule))
#define ImActorCoreModulesSecuritySecurityModule_

#define RESTRICT_ImActorCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/actor/core/modules/AbsModule.h"

@class ARPromise;
@protocol ACModuleContext;

@interface ImActorCoreModulesSecuritySecurityModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (ARPromise *)loadSessions;

- (ARPromise *)terminateAllSessions;

- (ARPromise *)terminateSessionWithInt:(jint)id_;

@end

J2OBJC_STATIC_INIT(ImActorCoreModulesSecuritySecurityModule)

FOUNDATION_EXPORT void ImActorCoreModulesSecuritySecurityModule_initWithACModuleContext_(ImActorCoreModulesSecuritySecurityModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImActorCoreModulesSecuritySecurityModule *new_ImActorCoreModulesSecuritySecurityModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesSecuritySecurityModule *create_ImActorCoreModulesSecuritySecurityModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesSecuritySecurityModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesSecuritySecurityModule")
