//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/settings/SettingsModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesSettingsSettingsModule")
#ifdef RESTRICT_ImActorCoreModulesSettingsSettingsModule
#define INCLUDE_ALL_ImActorCoreModulesSettingsSettingsModule 0
#else
#define INCLUDE_ALL_ImActorCoreModulesSettingsSettingsModule 1
#endif
#undef RESTRICT_ImActorCoreModulesSettingsSettingsModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesSettingsSettingsModule_) && (INCLUDE_ALL_ImActorCoreModulesSettingsSettingsModule || defined(INCLUDE_ImActorCoreModulesSettingsSettingsModule))
#define ImActorCoreModulesSettingsSettingsModule_

#define RESTRICT_ImActorCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/actor/core/modules/AbsModule.h"

@class ACPeer;
@protocol ACModuleContext;

@interface ImActorCoreModulesSettingsSettingsModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)changeConversationTonesEnabledWithBoolean:(jboolean)val;

- (void)changeGroupNotificationsEnabledWithBoolean:(jboolean)val;

- (void)changeGroupNotificationsOnlyMentionsEnabledWithBoolean:(jboolean)val;

- (void)changeInAppEnabledWithBoolean:(jboolean)val;

- (void)changeInAppSoundEnabledWithBoolean:(jboolean)val;

- (void)changeInAppVibrationEnabledWithBoolean:(jboolean)val;

- (void)changeMarkdownWithBoolean:(jboolean)val;

- (void)changeNotificationsEnabledWithBoolean:(jboolean)val;

- (void)changeNotificationsEnabledWithACPeer:(ACPeer *)peer
                                 withBoolean:(jboolean)val;

- (void)changeNotificationSoundWithACPeer:(ACPeer *)peer
                             withNSString:(NSString *)sound;

- (void)changeNotificationSoundWithNSString:(NSString *)sound;

- (void)changeNotificationSoundEnabledWithBoolean:(jboolean)val;

- (void)changeNotificationVibrationEnabledWithBoolean:(jboolean)val;

- (void)changeSelectedWallpapperWithNSString:(NSString *)uri;

- (void)changeSendByEnterWithBoolean:(jboolean)val;

- (void)changeShowNotificationTextEnabledWithBoolean:(jboolean)val;

- (void)changeTextSizeWithInt:(jint)textSize;

- (jboolean)getBooleanValueWithNSString:(NSString *)key;

- (jboolean)getBooleanValueWithNSString:(NSString *)key
                            withBoolean:(jboolean)defaultVal;

- (NSString *)getNotificationSound;

- (NSString *)getNotificationSoundWithACPeer:(ACPeer *)peer;

- (NSString *)getPrivacy;

- (NSString *)getSelectedWallpapper;

- (NSString *)getStringValueWithNSString:(NSString *)key;

- (NSString *)getStringValueWithNSString:(NSString *)key
                            withNSString:(NSString *)defaultVal;

- (jint)getTextSize;

- (jboolean)isConversationTonesEnabled;

- (jboolean)isGroupNotificationsEnabled;

- (jboolean)isGroupNotificationsOnlyMentionsEnabled;

- (jboolean)isInAppEnabled;

- (jboolean)isInAppSoundEnabled;

- (jboolean)isInAppVibrationEnabled;

- (jboolean)isMarkdownEnabled;

- (jboolean)isNotificationsEnabled;

- (jboolean)isNotificationsEnabledWithACPeer:(ACPeer *)peer;

- (jboolean)isNotificationSoundEnabled;

- (jboolean)isRenameHintShown;

- (jboolean)isSendByEnterEnabled;

- (jboolean)isShowNotificationsText;

- (jboolean)isVibrationEnabled;

- (void)onUpdatedSettingWithNSString:(NSString *)key
                        withNSString:(NSString *)value;

- (void)resetModule;

- (void)run;

- (void)setBooleanValueWithNSString:(NSString *)key
                        withBoolean:(jboolean)val;

- (void)setPrivacyWithNSString:(NSString *)privacy;

- (void)setStringValueWithNSString:(NSString *)key
                      withNSString:(NSString *)val;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesSettingsSettingsModule)

FOUNDATION_EXPORT void ImActorCoreModulesSettingsSettingsModule_initWithACModuleContext_(ImActorCoreModulesSettingsSettingsModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImActorCoreModulesSettingsSettingsModule *new_ImActorCoreModulesSettingsSettingsModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesSettingsSettingsModule *create_ImActorCoreModulesSettingsSettingsModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesSettingsSettingsModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesSettingsSettingsModule")
