//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/settings/SettingsProcessor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesSettingsSettingsProcessor")
#ifdef RESTRICT_ImActorCoreModulesSettingsSettingsProcessor
#define INCLUDE_ALL_ImActorCoreModulesSettingsSettingsProcessor 0
#else
#define INCLUDE_ALL_ImActorCoreModulesSettingsSettingsProcessor 1
#endif
#undef RESTRICT_ImActorCoreModulesSettingsSettingsProcessor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesSettingsSettingsProcessor_) && (INCLUDE_ALL_ImActorCoreModulesSettingsSettingsProcessor || defined(INCLUDE_ImActorCoreModulesSettingsSettingsProcessor))
#define ImActorCoreModulesSettingsSettingsProcessor_

#define RESTRICT_ImActorCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/actor/core/modules/AbsModule.h"

#define RESTRICT_ImActorCoreModulesSequenceProcessorSequenceProcessor 1
#define INCLUDE_ImActorCoreModulesSequenceProcessorSequenceProcessor 1
#include "../../../../../im/actor/core/modules/sequence/processor/SequenceProcessor.h"

@class ACUpdate;
@protocol ACModuleContext;

@interface ImActorCoreModulesSettingsSettingsProcessor : ACAbsModule < ImActorCoreModulesSequenceProcessorSequenceProcessor >

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)modules;

- (void)onSettingsChangedWithNSString:(NSString *)key
                         withNSString:(NSString *)value;

- (jboolean)processWithACUpdate:(ACUpdate *)update;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesSettingsSettingsProcessor)

FOUNDATION_EXPORT void ImActorCoreModulesSettingsSettingsProcessor_initWithACModuleContext_(ImActorCoreModulesSettingsSettingsProcessor *self, id<ACModuleContext> modules);

FOUNDATION_EXPORT ImActorCoreModulesSettingsSettingsProcessor *new_ImActorCoreModulesSettingsSettingsProcessor_initWithACModuleContext_(id<ACModuleContext> modules) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesSettingsSettingsProcessor *create_ImActorCoreModulesSettingsSettingsProcessor_initWithACModuleContext_(id<ACModuleContext> modules);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesSettingsSettingsProcessor)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesSettingsSettingsProcessor")
