//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/presence/OwnPresenceActor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesPresenceOwnPresenceActor")
#ifdef RESTRICT_ImActorCoreModulesPresenceOwnPresenceActor
#define INCLUDE_ALL_ImActorCoreModulesPresenceOwnPresenceActor 0
#else
#define INCLUDE_ALL_ImActorCoreModulesPresenceOwnPresenceActor 1
#endif
#undef RESTRICT_ImActorCoreModulesPresenceOwnPresenceActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesPresenceOwnPresenceActor_) && (INCLUDE_ALL_ImActorCoreModulesPresenceOwnPresenceActor || defined(INCLUDE_ImActorCoreModulesPresenceOwnPresenceActor))
#define ImActorCoreModulesPresenceOwnPresenceActor_

#define RESTRICT_ImActorCoreModulesModuleActor 1
#define INCLUDE_ACModuleActor 1
#include "../../../../../im/actor/core/modules/ModuleActor.h"

#define RESTRICT_ImActorRuntimeEventbusBusSubscriber 1
#define INCLUDE_ImActorRuntimeEventbusBusSubscriber 1
#include "../../../../../im/actor/runtime/eventbus/BusSubscriber.h"

@class ACModules;
@class ImActorRuntimeEventbusEvent;

/*!
 @brief Actor for processing current user's online status.
 TODO: Implement correct request timeout
 */
@interface ImActorCoreModulesPresenceOwnPresenceActor : ACModuleActor < ImActorRuntimeEventbusBusSubscriber >

#pragma mark Public

- (instancetype)initWithACModules:(ACModules *)messenger;

- (void)onBusEventWithImActorRuntimeEventbusEvent:(ImActorRuntimeEventbusEvent *)event;

- (void)onReceiveWithId:(id)message;

- (void)preStart;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesPresenceOwnPresenceActor)

FOUNDATION_EXPORT void ImActorCoreModulesPresenceOwnPresenceActor_initWithACModules_(ImActorCoreModulesPresenceOwnPresenceActor *self, ACModules *messenger);

FOUNDATION_EXPORT ImActorCoreModulesPresenceOwnPresenceActor *new_ImActorCoreModulesPresenceOwnPresenceActor_initWithACModules_(ACModules *messenger) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImActorCoreModulesPresenceOwnPresenceActor *create_ImActorCoreModulesPresenceOwnPresenceActor_initWithACModules_(ACModules *messenger);

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesPresenceOwnPresenceActor)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesPresenceOwnPresenceActor")
