//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/modules/sequence/processor/WeakProcessor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreModulesSequenceProcessorWeakProcessor")
#ifdef RESTRICT_ImActorCoreModulesSequenceProcessorWeakProcessor
#define INCLUDE_ALL_ImActorCoreModulesSequenceProcessorWeakProcessor 0
#else
#define INCLUDE_ALL_ImActorCoreModulesSequenceProcessorWeakProcessor 1
#endif
#undef RESTRICT_ImActorCoreModulesSequenceProcessorWeakProcessor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImActorCoreModulesSequenceProcessorWeakProcessor_) && (INCLUDE_ALL_ImActorCoreModulesSequenceProcessorWeakProcessor || defined(INCLUDE_ImActorCoreModulesSequenceProcessorWeakProcessor))
#define ImActorCoreModulesSequenceProcessorWeakProcessor_

@class ACUpdate;

@protocol ImActorCoreModulesSequenceProcessorWeakProcessor < NSObject, JavaObject >

- (jboolean)processWithACUpdate:(ACUpdate *)update
                       withLong:(jlong)date;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorCoreModulesSequenceProcessorWeakProcessor)

J2OBJC_TYPE_LITERAL_HEADER(ImActorCoreModulesSequenceProcessorWeakProcessor)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreModulesSequenceProcessorWeakProcessor")
