//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/ApiColorUnsupported.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiApiColorUnsupported")
#ifdef RESTRICT_ImActorCoreApiApiColorUnsupported
#define INCLUDE_ALL_ImActorCoreApiApiColorUnsupported 0
#else
#define INCLUDE_ALL_ImActorCoreApiApiColorUnsupported 1
#endif
#undef RESTRICT_ImActorCoreApiApiColorUnsupported

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiColorUnsupported_) && (INCLUDE_ALL_ImActorCoreApiApiColorUnsupported || defined(INCLUDE_ARApiColorUnsupported))
#define ARApiColorUnsupported_

#define RESTRICT_ImActorCoreApiApiColor 1
#define INCLUDE_ARApiColor 1
#include "../../../../im/actor/core/api/ApiColor.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARApiColorUnsupported : ARApiColor

#pragma mark Public

- (instancetype)initWithInt:(jint)key
              withByteArray:(IOSByteArray *)content;

- (jint)getHeader;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiColorUnsupported)

FOUNDATION_EXPORT void ARApiColorUnsupported_initWithInt_withByteArray_(ARApiColorUnsupported *self, jint key, IOSByteArray *content);

FOUNDATION_EXPORT ARApiColorUnsupported *new_ARApiColorUnsupported_initWithInt_withByteArray_(jint key, IOSByteArray *content) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiColorUnsupported *create_ARApiColorUnsupported_initWithInt_withByteArray_(jint key, IOSByteArray *content);

J2OBJC_TYPE_LITERAL_HEADER(ARApiColorUnsupported)

@compatibility_alias ImActorCoreApiApiColorUnsupported ARApiColorUnsupported;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiApiColorUnsupported")
