//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/ApiDocumentEx.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiApiDocumentEx")
#ifdef RESTRICT_ImActorCoreApiApiDocumentEx
#define INCLUDE_ALL_ImActorCoreApiApiDocumentEx 0
#else
#define INCLUDE_ALL_ImActorCoreApiApiDocumentEx 1
#endif
#undef RESTRICT_ImActorCoreApiApiDocumentEx

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiDocumentEx_) && (INCLUDE_ALL_ImActorCoreApiApiDocumentEx || defined(INCLUDE_ARApiDocumentEx))
#define ARApiDocumentEx_

#define RESTRICT_ImActorRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/actor/runtime/bser/BserObject.h"

@class IOSByteArray;

@interface ARApiDocumentEx : ARBserObject

#pragma mark Public

- (instancetype)init;

- (IOSByteArray *)buildContainer;

+ (ARApiDocumentEx *)fromBytesWithByteArray:(IOSByteArray *)src;

- (jint)getHeader;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiDocumentEx)

FOUNDATION_EXPORT ARApiDocumentEx *ARApiDocumentEx_fromBytesWithByteArray_(IOSByteArray *src);

FOUNDATION_EXPORT void ARApiDocumentEx_init(ARApiDocumentEx *self);

J2OBJC_TYPE_LITERAL_HEADER(ARApiDocumentEx)

@compatibility_alias ImActorCoreApiApiDocumentEx ARApiDocumentEx;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiApiDocumentEx")
