//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/ApiEventRecord.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiApiEventRecord")
#ifdef RESTRICT_ImActorCoreApiApiEventRecord
#define INCLUDE_ALL_ImActorCoreApiApiEventRecord 0
#else
#define INCLUDE_ALL_ImActorCoreApiApiEventRecord 1
#endif
#undef RESTRICT_ImActorCoreApiApiEventRecord

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiEventRecord_) && (INCLUDE_ALL_ImActorCoreApiApiEventRecord || defined(INCLUDE_ARApiEventRecord))
#define ARApiEventRecord_

#define RESTRICT_ImActorRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/actor/runtime/bser/BserObject.h"

@class ARApiEvent;
@class ARBserValues;
@class ARBserWriter;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiEventRecord : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)date
              withARApiEvent:(ARApiEvent * __nonnull)event;

- (jlong)getDate;

- (ARApiEvent * __nonnull)getEvent;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiEventRecord)

FOUNDATION_EXPORT void ARApiEventRecord_initWithLong_withARApiEvent_(ARApiEventRecord *self, jlong date, ARApiEvent *event);

FOUNDATION_EXPORT ARApiEventRecord *new_ARApiEventRecord_initWithLong_withARApiEvent_(jlong date, ARApiEvent *event) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiEventRecord *create_ARApiEventRecord_initWithLong_withARApiEvent_(jlong date, ARApiEvent *event);

FOUNDATION_EXPORT void ARApiEventRecord_init(ARApiEventRecord *self);

FOUNDATION_EXPORT ARApiEventRecord *new_ARApiEventRecord_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiEventRecord *create_ARApiEventRecord_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiEventRecord)

@compatibility_alias ImActorCoreApiApiEventRecord ARApiEventRecord;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiApiEventRecord")
