//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/ApiServiceExChangedTopic.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiApiServiceExChangedTopic")
#ifdef RESTRICT_ImActorCoreApiApiServiceExChangedTopic
#define INCLUDE_ALL_ImActorCoreApiApiServiceExChangedTopic 0
#else
#define INCLUDE_ALL_ImActorCoreApiApiServiceExChangedTopic 1
#endif
#undef RESTRICT_ImActorCoreApiApiServiceExChangedTopic

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiServiceExChangedTopic_) && (INCLUDE_ALL_ImActorCoreApiApiServiceExChangedTopic || defined(INCLUDE_ARApiServiceExChangedTopic))
#define ARApiServiceExChangedTopic_

#define RESTRICT_ImActorCoreApiApiServiceEx 1
#define INCLUDE_ARApiServiceEx 1
#include "../../../../im/actor/core/api/ApiServiceEx.h"

@class ARBserValues;
@class ARBserWriter;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiServiceExChangedTopic : ARApiServiceEx

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nullable)topic;

- (jint)getHeader;

- (NSString * __nullable)getTopic;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiServiceExChangedTopic)

FOUNDATION_EXPORT void ARApiServiceExChangedTopic_initWithNSString_(ARApiServiceExChangedTopic *self, NSString *topic);

FOUNDATION_EXPORT ARApiServiceExChangedTopic *new_ARApiServiceExChangedTopic_initWithNSString_(NSString *topic) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiServiceExChangedTopic *create_ARApiServiceExChangedTopic_initWithNSString_(NSString *topic);

FOUNDATION_EXPORT void ARApiServiceExChangedTopic_init(ARApiServiceExChangedTopic *self);

FOUNDATION_EXPORT ARApiServiceExChangedTopic *new_ARApiServiceExChangedTopic_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiServiceExChangedTopic *create_ARApiServiceExChangedTopic_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiServiceExChangedTopic)

@compatibility_alias ImActorCoreApiApiServiceExChangedTopic ARApiServiceExChangedTopic;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiApiServiceExChangedTopic")
