//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/api/ApiServiceExChatRestored.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreApiApiServiceExChatRestored")
#ifdef RESTRICT_ImActorCoreApiApiServiceExChatRestored
#define INCLUDE_ALL_ImActorCoreApiApiServiceExChatRestored 0
#else
#define INCLUDE_ALL_ImActorCoreApiApiServiceExChatRestored 1
#endif
#undef RESTRICT_ImActorCoreApiApiServiceExChatRestored

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiServiceExChatRestored_) && (INCLUDE_ALL_ImActorCoreApiApiServiceExChatRestored || defined(INCLUDE_ARApiServiceExChatRestored))
#define ARApiServiceExChatRestored_

#define RESTRICT_ImActorCoreApiApiServiceEx 1
#define INCLUDE_ARApiServiceEx 1
#include "../../../../im/actor/core/api/ApiServiceEx.h"

@class ARBserValues;
@class ARBserWriter;

@interface ARApiServiceExChatRestored : ARApiServiceEx

#pragma mark Public

- (instancetype)init;

- (jint)getHeader;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiServiceExChatRestored)

FOUNDATION_EXPORT void ARApiServiceExChatRestored_init(ARApiServiceExChatRestored *self);

FOUNDATION_EXPORT ARApiServiceExChatRestored *new_ARApiServiceExChatRestored_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiServiceExChatRestored *create_ARApiServiceExChatRestored_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiServiceExChatRestored)

@compatibility_alias ImActorCoreApiApiServiceExChatRestored ARApiServiceExChatRestored;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreApiApiServiceExChatRestored")
