//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liruqi/Documents/github/actor-platform/actor-sdk/sdk-core/core/core-shared/src/main/java/im/actor/core/network/parser/HeaderBserObject.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImActorCoreNetworkParserHeaderBserObject")
#ifdef RESTRICT_ImActorCoreNetworkParserHeaderBserObject
#define INCLUDE_ALL_ImActorCoreNetworkParserHeaderBserObject 0
#else
#define INCLUDE_ALL_ImActorCoreNetworkParserHeaderBserObject 1
#endif
#undef RESTRICT_ImActorCoreNetworkParserHeaderBserObject

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACHeaderBserObject_) && (INCLUDE_ALL_ImActorCoreNetworkParserHeaderBserObject || defined(INCLUDE_ACHeaderBserObject))
#define ACHeaderBserObject_

#define RESTRICT_ImActorRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../../im/actor/runtime/bser/BserObject.h"

@interface ACHeaderBserObject : ARBserObject

#pragma mark Public

- (instancetype)init;

- (jint)getHeaderKey;

@end

J2OBJC_EMPTY_STATIC_INIT(ACHeaderBserObject)

FOUNDATION_EXPORT void ACHeaderBserObject_init(ACHeaderBserObject *self);

J2OBJC_TYPE_LITERAL_HEADER(ACHeaderBserObject)

@compatibility_alias ImActorCoreNetworkParserHeaderBserObject ACHeaderBserObject;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImActorCoreNetworkParserHeaderBserObject")
