// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import RSKImageCropper;
@import CoreGraphics;
@import j2objc;
@import ObjectiveC;
@import AVFoundation;
@import MessageUI;
@import AddressBookUI;
@import AddressBook;
@import Foundation;
@import CoreLocation;
@import MapKit;
@import VBFPopFlatButton;
@import PushKit;
@import SystemConfiguration;
#endif

#import <ActorSDK/ActorSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class ACPage;
@class ACUserVM;
@class ACGroupVM;
@class NSBundle;
@class NSCoder;
@class UIImage;
@class UIView;
@class RSKImageCropViewController;
@class UIImagePickerController;
@class UIPresentationController;

SWIFT_CLASS("_TtC8ActorSDK16AAViewController")
@interface AAViewController : UIViewController <UINavigationControllerDelegate, UIImagePickerControllerDelegate, RSKImageCropViewControllerDelegate, UIViewControllerTransitioningDelegate>
@property (nonatomic, strong) ACPage * _Nullable content;
@property (nonatomic) BOOL autoTrack;
@property (nonatomic, strong) ACUserVM * _Null_unspecified user;
@property (nonatomic, strong) ACGroupVM * _Null_unspecified group;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (void)showPlaceholderWithImage:(UIImage * _Nullable)image title:(NSString * _Nullable)title subtitle:(NSString * _Nullable)subtitle;
- (void)showPlaceholder;
- (void)hidePlaceholder;
- (void)shakeView:(UIView * _Nonnull)view originalX:(CGFloat)originalX;
- (void)pickAvatar:(BOOL)takePhoto closure:(void (^ _Nonnull)(UIImage * _Nonnull))closure;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)dismiss;
- (void)presentInNavigation:(UIViewController * _Nonnull)controller;
- (void)openUrl:(NSString * _Nonnull)url;
- (void)cropImage:(UIImage * _Nonnull)image;
- (void)imageCropViewController:(RSKImageCropViewController * _Nonnull)controller didCropImage:(UIImage * _Nonnull)croppedImage usingCropRect:(CGRect)cropRect;
- (void)imageCropViewControllerDidCancelCrop:(RSKImageCropViewController * _Nonnull)controller;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingImage:(UIImage * _Nonnull)image editingInfo:(NSDictionary<NSString *, id> * _Nullable)editingInfo;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *, id> * _Nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nonnull)presenting sourceViewController:(UIViewController * _Nonnull)source;
- (void)presentElegantViewController:(UIViewController * _Nonnull)controller;
@end

@class UITableView;

SWIFT_CLASS("_TtC8ActorSDK24AAManagedTableController")
@interface AAManagedTableController : AAViewController
@property (nonatomic, strong) UITableView * _Null_unspecified tableView;
@property (nonatomic) BOOL unbindOnDissapear;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK24AAContentTableController")
@interface AAContentTableController : AAManagedTableController
@property (nonatomic) BOOL autoSections;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)afterTableCreated;
- (void)tableWillLoad;
- (void)tableDidLoad;
- (void)managedTableWillLoad:(AAManagedTableController * _Nonnull)controller;
@end


SWIFT_CLASS("_TtC8ActorSDK31AAContactsListContentController")
@interface AAContactsListContentController : AAContentTableController
@property (nonatomic) BOOL isSearchAutoHide;
@property (nonatomic) BOOL searchEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
- (void)viewWillAppear:(BOOL)animated;
@end

@class ACContact;
@class AAContactCell;

SWIFT_CLASS("_TtC8ActorSDK30AAAddParticipantViewController")
@interface AAAddParticipantViewController : AAContactsListContentController
- (nonnull instancetype)initWithGid:(NSInteger)gid OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)contactDidBind:(AAContactsListContentController * _Nonnull)controller contact:(ACContact * _Nonnull)contact cell:(AAContactCell * _Nonnull)cell;
- (BOOL)contactDidTap:(AAContactsListContentController * _Nonnull)controller contact:(ACContact * _Nonnull)contact;
- (BOOL)isAlreadyMember:(jint)uid;
@end

@class ACCallVM;

SWIFT_CLASS("_TtC8ActorSDK14AAAudioManager")
@interface AAAudioManager : NSObject <AVAudioPlayerDelegate>
+ (AAAudioManager * _Nonnull)sharedAudio;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)appVisible;
- (void)appHidden;
- (void)callStart:(ACCallVM * _Nonnull)call;
- (void)callAnswered:(ACCallVM * _Nonnull)call;
- (void)callEnd:(ACCallVM * _Nonnull)call;
- (void)peerConnectionStarted;
- (void)peerConnectionEnded;
@end


SWIFT_CLASS("_TtC8ActorSDK17AAAuthCountryCell")
@interface AAAuthCountryCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setTitle:(NSString * _Nonnull)title;
- (void)setCode:(NSString * _Nonnull)code;
- (void)setSearchMode:(BOOL)searchMode;
@end

@class UIButton;

SWIFT_CLASS("_TtC8ActorSDK20AAAuthViewController")
@interface AAAuthViewController : AAViewController
@property (nonatomic, readonly, strong) UIButton * _Nonnull nextBarButton;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)animated;
- (void)keyboardWillAppear:(CGFloat)height;
- (void)keyboardWillDisappear;
- (void)viewWillDisappear:(BOOL)animated;

/// Call this method when authentication successful
- (void)onAuthenticated;
- (void)nextDidTap;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK25AAAuthEmailViewController")
@interface AAAuthEmailViewController : AAAuthViewController
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)usePhoneDidPressed;
- (void)nextDidTap;
- (void)keyboardWillAppear:(CGFloat)height;
- (void)keyboardWillDisappear;
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8ActorSDK25AAAuthLogInViewController")
@interface AAAuthLogInViewController : AAAuthViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)nextDidTap;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8ActorSDK24AAAuthNameViewController")
@interface AAAuthNameViewController : AAAuthViewController
- (nonnull instancetype)initWithTransactionHash:(NSString * _Nullable)transactionHash OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)nextDidTap;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8ActorSDK26AAAuthNavigationController")
@interface AAAuthNavigationController : UINavigationController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class MFMailComposeViewController;
@class NSError;

SWIFT_CLASS("_TtC8ActorSDK23AAAuthOTPViewController")
@interface AAAuthOTPViewController : AAAuthViewController <MFMailComposeViewControllerDelegate>
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email transactionHash:(NSString * _Nonnull)transactionHash OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email name:(NSString * _Nonnull)name transactionHash:(NSString * _Nonnull)transactionHash OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPhone:(NSString * _Nonnull)phone transactionHash:(NSString * _Nonnull)transactionHash OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPhone:(NSString * _Nonnull)phone name:(NSString * _Nonnull)name transactionHash:(NSString * _Nonnull)transactionHash OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
- (void)nextDidTap;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@end



SWIFT_CLASS("_TtC8ActorSDK15AATableViewCell")
@interface AATableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) CGFloat topSeparatorLeftInset;
@property (nonatomic) CGFloat bottomSeparatorLeftInset;
@property (nonatomic) BOOL topSeparatorVisible;
@property (nonatomic) BOOL bottomSeparatorVisible;
- (void)layoutSubviews;
- (void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end

@class UILabel;
@class AAAvatarView;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC8ActorSDK12AAAvatarCell")
@interface AAAvatarCell : AATableViewCell
@property (nonatomic, strong) UILabel * _Nonnull titleLabel;
@property (nonatomic, strong) UILabel * _Nonnull subtitleLabel;
@property (nonatomic, strong) AAAvatarView * _Nonnull avatarView;
@property (nonatomic, strong) UIActivityIndicatorView * _Nonnull progress;
@property (nonatomic, copy) void (^ _Nullable didTap)(UIView * _Nonnull);
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class NSIndexPath;

SWIFT_CLASS("_TtC8ActorSDK12AAManagedRow")
@interface AAManagedRow : NSObject
@property (nonatomic, copy) BOOL (^ _Nullable selectAction)(void);
@property (nonatomic, strong) NSIndexPath * _Nullable indexPath;
- (void)reload;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ACAvatar;
@class UIColor;

SWIFT_CLASS("_TtC8ActorSDK11AAAvatarRow")
@interface AAAvatarRow : AAManagedRow
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) ACAvatar * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable avatarPath;
@property (nonatomic) BOOL avatarLoading;
@property (nonatomic) BOOL subtitleHidden;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, strong) UIColor * _Nullable subtitleColor;
@property (nonatomic, copy) void (^ _Nullable bindAction)(AAAvatarRow * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable avatarDidTap)(UIView * _Nonnull);
- (void)bindCell:(AAAvatarCell * _Nonnull)res;
- (void)reload;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class YYAsyncLayerDisplayTask;

SWIFT_CLASS("_TtC8ActorSDK12AAAvatarView")
@interface AAAvatarView : UIView <YYAsyncLayerDelegate, ACFileEventCallback>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)onDownloadedWithLong:(jlong)fileId;
- (void)bind:(NSString * _Nonnull)title id:(NSInteger)id fileName:(NSString * _Nullable)fileName;
- (void)bind:(NSString * _Nonnull)title id:(NSInteger)id avatar:(ACAvatar * _Nullable)avatar;
- (void)unbind;
+ (Class _Nonnull)layerClass;
- (YYAsyncLayerDisplayTask * _Nonnull)newAsyncDisplayTask;
@end

@protocol UIViewControllerAnimatedTransitioning;

SWIFT_CLASS("_TtC8ActorSDK20AABigAlertController")
@interface AABigAlertController : UIViewController <UIViewControllerTransitioningDelegate>
- (nonnull instancetype)initWithAlertTitle:(NSString * _Nonnull)alertTitle alertMessage:(NSString * _Nonnull)alertMessage OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLoad;
- (void)closeController;
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nonnull)presenting sourceViewController:(UIViewController * _Nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed;
@end

@class UIImageView;
@class ACPeer;
@class ACMessage;
@class UICollectionViewLayoutAttributes;
@class AAConversationContentController;


/// Root class for bubble cells
SWIFT_CLASS("_TtC8ActorSDK12AABubbleCell")
@interface AABubbleCell : UICollectionViewCell
+ (CGFloat)bubbleContentTop;
+ (CGFloat)bubbleContentBottom;
+ (CGFloat)bubbleTop;
+ (CGFloat)bubbleTopCompact;
+ (CGFloat)bubbleBottom;
+ (CGFloat)bubbleBottomCompact;
+ (CGFloat)avatarPadding;
+ (CGFloat)dateSize;
+ (CGFloat)newMessageSize;
@property (nonatomic, readonly, strong) AAAvatarView * _Nonnull avatarView;
@property (nonatomic) BOOL avatarAdded;
@property (nonatomic, readonly, strong) UIImageView * _Nonnull bubble;
@property (nonatomic, readonly, strong) UIImageView * _Nonnull bubbleBorder;
@property (nonatomic) UIEdgeInsets contentInsets;
@property (nonatomic) UIEdgeInsets bubbleInsets;
@property (nonatomic, readonly) UIEdgeInsets fullContentInsets;
@property (nonatomic) BOOL needLayout;
@property (nonatomic, readonly) double groupContentInsetY;
@property (nonatomic, readonly) double groupContentInsetX;
@property (nonatomic) CGFloat bubbleVerticalSpacing;
@property (nonatomic, readonly) CGFloat bubblePadding;
@property (nonatomic, readonly) CGFloat bubbleMediaPadding;
@property (nonatomic, strong) ACPeer * _Null_unspecified peer;
@property (nonatomic, weak) AAConversationContentController * _Null_unspecified controller;
@property (nonatomic) BOOL isGroup;
@property (nonatomic, strong) ACMessage * _Nullable bindedMessage;
@property (nonatomic) BOOL isOut;
@property (nonatomic) BOOL isShowDate;
@property (nonatomic) BOOL isShowNewMessages;
- (nonnull instancetype)initWithFrame:(CGRect)frame isFullSize:(BOOL)isFullSize OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPerformAction:(SEL _Null_unspecified)action withSender:(id _Nullable)sender;
- (void)delete:(id _Nullable)sender;
- (void)layoutSubviews;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
- (void)layoutBubble:(CGFloat)contentWidth contentHeight:(CGFloat)contentHeight;
- (void)layoutBubble:(CGRect)frame;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes;
@end

@class ACFileReference;

SWIFT_CLASS("_TtC8ActorSDK20AABubbleBaseFileCell")
@interface AABubbleBaseFileCell : AABubbleCell
- (void)fileBind:(ACMessage * _Nonnull)message autoDownload:(BOOL)autoDownload;
- (void)bindFile:(ACFileReference * _Nonnull)fileReference autoDownload:(BOOL)autoDownload;
- (void)fileUploadPaused:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)fileUploading:(NSString * _Nonnull)reference progress:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileDownloadPaused:(NSInteger)selfGeneration;
- (void)fileDownloading:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileReady:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)runOnUiThread:(NSInteger)selfGeneration closure:(void (^ _Nonnull)(void))closure;
- (void)fileUnbind;
- (nonnull instancetype)initWithFrame:(CGRect)frame isFullSize:(BOOL)isFullSize OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@class ABNewPersonViewController;

SWIFT_CLASS("_TtC8ActorSDK19AABubbleContactCell")
@interface AABubbleContactCell : AABubbleCell <ABNewPersonViewControllerDelegate, MFMailComposeViewControllerDelegate, UINavigationControllerDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)newPersonViewController:(ABNewPersonViewController * _Nonnull)newPersonView didCompleteWithNewPerson:(ABRecordRef _Nullable)person;
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
@end

@class UIDocumentInteractionController;

SWIFT_CLASS("_TtC8ActorSDK20AABubbleDocumentCell")
@interface AABubbleDocumentCell : AABubbleBaseFileCell <UIDocumentInteractionControllerDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)documentDidTap;
- (void)fileUploadPaused:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)fileUploading:(NSString * _Nonnull)reference progress:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileDownloadPaused:(NSInteger)selfGeneration;
- (void)fileDownloading:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileReady:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
- (UIViewController * _Nonnull)documentInteractionControllerViewControllerForPreview:(UIDocumentInteractionController * _Nonnull)controller;
@end


SWIFT_CLASS("_TtC8ActorSDK20AABubbleLocationCell")
@interface AABubbleLocationCell : AABubbleCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
@end

@class NYTPhotosViewController;
@protocol NYTPhoto;

SWIFT_CLASS("_TtC8ActorSDK17AABubbleMediaCell")
@interface AABubbleMediaCell : AABubbleBaseFileCell <NYTPhotosViewControllerDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fileUploadPaused:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)fileUploading:(NSString * _Nonnull)reference progress:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileDownloadPaused:(NSInteger)selfGeneration;
- (void)fileDownloading:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileReady:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)bgLoadThumb:(NSInteger)selfGeneration;
- (void)bgLoadReference:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)setPreviewImage:(UIImage * _Nonnull)img fast:(BOOL)fast;
- (void)mediaDidTap;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
- (UIView * _Nullable)photosViewController:(NYTPhotosViewController * _Nonnull)photosViewController referenceViewForPhoto:(id <NYTPhoto> _Nonnull)photo;
- (void)photosViewControllerWillDismiss:(NYTPhotosViewController * _Nonnull)photosViewController;
@end


SWIFT_CLASS("_TtC8ActorSDK19AABubbleServiceCell")
@interface AABubbleServiceCell : AABubbleCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
@end


SWIFT_CLASS("_TtC8ActorSDK19AABubbleStickerCell")
@interface AABubbleStickerCell : AABubbleBaseFileCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fileReady:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)mediaDidTap;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
@end

@class NSURL;

SWIFT_CLASS("_TtC8ActorSDK16AABubbleTextCell")
@interface AABubbleTextCell : AABubbleCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)canPerformAction:(SEL _Null_unspecified)action withSender:(id _Nullable)sender;
- (void)copy:(id _Nullable)sender;
- (void)urlLongTap:(NSURL * _Nonnull)url;
- (void)openUrl:(NSURL * _Nonnull)url;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
@end


SWIFT_CLASS("_TtC8ActorSDK17AABubbleVideoCell")
@interface AABubbleVideoCell : AABubbleBaseFileCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fileUploadPaused:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)fileUploading:(NSString * _Nonnull)reference progress:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileDownloadPaused:(NSInteger)selfGeneration;
- (void)fileDownloading:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileReady:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)bgLoadThumb:(NSInteger)selfGeneration;
- (void)bgLoadReference:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)setPreviewImage:(UIImage * _Nonnull)img fast:(BOOL)fast;
- (void)mediaDidTap;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
@end


SWIFT_CLASS("_TtC8ActorSDK17AABubbleVoiceCell")
@interface AABubbleVoiceCell : AABubbleBaseFileCell <AAModernConversationAudioPlayerDelegate, AAModernViewInlineMediaContextDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fileUploadPaused:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)fileUploading:(NSString * _Nonnull)reference progress:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileDownloadPaused:(NSInteger)selfGeneration;
- (void)fileDownloading:(double)progress selfGeneration:(NSInteger)selfGeneration;
- (void)fileReady:(NSString * _Nonnull)reference selfGeneration:(NSInteger)selfGeneration;
- (void)mediaDidTap;
- (void)seekToNewAudioValue;
- (void)audioPlayerDidFinish;
- (void)inlineMediaPlaybackStateUpdated:(BOOL)isPaused playbackPosition:(float)playbackPosition timestamp:(NSTimeInterval)timestamp preciseDuration:(NSTimeInterval)preciseDuration;
- (void)layoutContent:(CGFloat)maxWidth offsetX:(CGFloat)offsetX;
@end

@class AACircleButton;

SWIFT_CLASS("_TtC8ActorSDK20AACallViewController")
@interface AACallViewController : AAViewController
@property (nonatomic, readonly) jlong callId;
@property (nonatomic, readonly, strong) ACCallVM * _Nonnull call;
@property (nonatomic, readonly, strong) AAAvatarView * _Nonnull senderAvatar;
@property (nonatomic, readonly, strong) UILabel * _Nonnull peerTitle;
@property (nonatomic, readonly, strong) UILabel * _Nonnull callState;
@property (nonatomic, readonly, strong) UIButton * _Nonnull answerCallButton;
@property (nonatomic, readonly, strong) UILabel * _Nonnull answerCallButtonText;
@property (nonatomic, readonly, strong) UIButton * _Nonnull declineCallButton;
@property (nonatomic, readonly, strong) UILabel * _Nonnull declineCallButtonText;
@property (nonatomic, readonly, strong) AACircleButton * _Nonnull muteButton;
@property (nonatomic, readonly, strong) AACircleButton * _Nonnull speakerButton;
@property (nonatomic, readonly, strong) AACircleButton * _Nonnull videoButton;
- (nonnull instancetype)initWithCallId:(jlong)callId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8ActorSDK14AACircleButton")
@interface AACircleButton : UIView
@property (nonatomic, readonly, strong) UIButton * _Nonnull button;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic) BOOL filled;
@property (nonatomic) BOOL enabled;
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
- (nonnull instancetype)initWithSize:(CGFloat)size OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK23AACodePreviewController")
@interface AACodePreviewController : AAViewController
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
@end

@class UICollectionView;
@class UICollectionViewLayout;

SWIFT_CLASS("_TtC8ActorSDK26AACollectionViewController")
@interface AACollectionViewController : AAViewController <UICollectionViewDelegate, UICollectionViewDataSource>
@property (nonatomic, strong) UICollectionView * _Null_unspecified collectionView;
- (nonnull instancetype)initWithCollectionLayout:(UICollectionViewLayout * _Nonnull)collectionLayout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewWillLayoutSubviews;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class JavaLangException;

SWIFT_CLASS("_TtC8ActorSDK17AACommandCallback")
@interface AACommandCallback : NSObject <ACCommandCallback>
@property (nonatomic, copy) void (^ _Nullable resultClosure)(id _Null_unspecified);
@property (nonatomic, copy) void (^ _Nullable errorClosure)(JavaLangException * _Null_unspecified);
- (void)onResult:(id _Null_unspecified)res;
- (void)onError:(JavaLangException * _Null_unspecified)e;
@end


SWIFT_CLASS("_TtC8ActorSDK12AACommonCell")
@interface AACommonCell : AATableViewCell
@property (nonatomic, copy) void (^ _Nullable switchBlock)(BOOL);
@property (nonatomic) CGFloat contentInset;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setContent:(NSString * _Nullable)content;
- (void)setHint:(NSString * _Nullable)hint;
- (void)setSwitcherOn:(BOOL)on;
- (void)setSwitcherOn:(BOOL)on animated:(BOOL)animated;
- (void)setSwitcherEnabled:(BOOL)enabled;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK11AACommonRow")
@interface AACommonRow : AAManagedRow
@property (nonatomic, copy) NSString * _Nullable hint;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) BOOL switchOn;
@property (nonatomic, copy) void (^ _Nullable switchAction)(BOOL);
@property (nonatomic, copy) void (^ _Nullable bindAction)(AACommonRow * _Nonnull);
@property (nonatomic) CGFloat contentInset;
- (void)bindCell:(AACommonCell * _Nonnull)res;
- (void)reload;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK19AAComposeController")
@interface AAComposeController : AAContactsListContentController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)contactDidTap:(AAContactsListContentController * _Nonnull)controller contact:(ACContact * _Nonnull)contact;
@end

@class YYLabel;

SWIFT_CLASS("_TtC8ActorSDK19AAContactActionCell")
@interface AAContactActionCell : AATableViewCell
@property (nonatomic, readonly, strong) YYLabel * _Nonnull titleView;
@property (nonatomic, readonly, strong) UIImageView * _Nonnull iconView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)bind:(NSString * _Nonnull)icon actionTitle:(NSString * _Nonnull)actionTitle;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK13AAContactCell")
@interface AAContactCell : AATableViewCell
+ (CGFloat)bindedCellHeight:(ACContact * _Nonnull)item;
@property (nonatomic, readonly, strong) AAAvatarView * _Nonnull avatarView;
@property (nonatomic, readonly, strong) YYLabel * _Nonnull shortNameView;
@property (nonatomic, readonly, strong) YYLabel * _Nonnull titleView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)bind:(ACContact * _Nonnull)item search:(NSString * _Nullable)search;
- (void)layoutSubviews;
@end



@class PHAsset;
@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC8ActorSDK17AAConvActionSheet")
@interface AAConvActionSheet : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)presentInController:(UIViewController * _Nonnull)controller;
- (void)dismiss;
- (void)thumbnailSelectedUpdated:(NSArray<PHAsset *> * _Nonnull)selectedAssets;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end

@class AAModernConversationAudioPlayer;
@class AAModernViewInlineMediaContext;
@class ARAppleListUpdate;
@protocol UIViewControllerTransitionCoordinator;

SWIFT_CLASS("_TtC8ActorSDK31AAConversationContentController")
@interface AAConversationContentController : SLKTextViewController <ARDisplayList_AppleChangeListener>
@property (nonatomic, readonly, strong) ACPeer * _Nonnull peer;
@property (nonatomic, strong) AAModernConversationAudioPlayer * _Null_unspecified voicePlayer;
@property (nonatomic, strong) AAModernViewInlineMediaContext * _Null_unspecified voiceContext;
@property (nonatomic) jlong currentAudioFileId;
- (nonnull instancetype)initWithPeer:(ACPeer * _Nonnull)peer OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithCoder:(NSCoder * _Null_unspecified)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (UICollectionViewCell * _Nonnull)buildCell:(UICollectionView * _Nonnull)collectionView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)bindCell:(UICollectionView * _Nonnull)collectionView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath cell:(UICollectionViewCell * _Nonnull)cell;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView canPerformAction:(SEL _Null_unspecified)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Null_unspecified)sender;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldShowMenuForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView performAction:(SEL _Null_unspecified)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Null_unspecified)sender;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)viewDidDisappear:(BOOL)animated;
- (id _Nullable)objectAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (id _Nullable)objectAtIndex:(NSInteger)index;
- (NSInteger)getCount;
- (void)onCollectionChangedWithChanges:(ARAppleListUpdate * _Null_unspecified)modification;
- (void)willUpdate;
- (void)didUpdate;
- (void)onBubbleAvatarTap:(UIView * _Nonnull)view uid:(jint)uid;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
@end


SWIFT_CLASS("_TtC8ActorSDK21AATableViewController")
@interface AATableViewController : AAViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, readonly, strong) UITableView * _Nonnull tableView;
@property (nonatomic, readonly) UITableViewStyle tableViewStyle;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
- (void)setEditing:(BOOL)editing animated:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC8ActorSDK23AACountryViewController")
@interface AACountryViewController : AATableViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSArray * _Null_unspecified)sectionIndexTitlesForTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView sectionForSectionIndexTitle:(NSString * _Nonnull)title atIndex:(NSInteger)index;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8ActorSDK12AADialogCell")
@interface AADialogCell : AATableViewCell
@property (nonatomic, readonly, strong) AAAvatarView * _Nonnull avatarView;
@property (nonatomic, readonly, strong) YYLabel * _Nonnull titleView;
@property (nonatomic, readonly, strong) YYLabel * _Nonnull messageView;
@property (nonatomic, readonly, strong) YYLabel * _Nonnull dateView;
@property (nonatomic, readonly, strong) UIImageView * _Nonnull statusView;
@property (nonatomic, readonly, strong) YYLabel * _Nonnull counterView;
@property (nonatomic, readonly, strong) UIImageView * _Nonnull counterViewBg;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willTransitionToState:(UITableViewCellStateMask)state;
- (void)layoutSubviews;
@end

@class ACSearchEntity;

SWIFT_CLASS("_TtC8ActorSDK18AADialogSearchCell")
@interface AADialogSearchCell : AATableViewCell
+ (CGFloat)bindedCellHeight:(ACSearchEntity * _Nonnull)item;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)bind:(ACSearchEntity * _Nonnull)item search:(NSString * _Nullable)search;
- (void)prepareForReuse;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK30AADialogsListContentController")
@interface AADialogsListContentController : AAContentTableController <UISearchBarDelegate, UISearchDisplayDelegate>
@property (nonatomic) BOOL enableDeletion;
@property (nonatomic) BOOL enableSearch;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
- (void)viewWillAppear:(BOOL)animated;
@end

@class UITextField;

SWIFT_CLASS("_TtC8ActorSDK10AAEditCell")
@interface AAEditCell : AATableViewCell
@property (nonatomic, readonly, strong) UITextField * _Nonnull textField;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class AAEditRow;

SWIFT_CLASS("_TtC8ActorSDK21AAEditFieldController")
@interface AAEditFieldController : AAContentTableController
@property (nonatomic, strong) AAEditRow * _Null_unspecified fieldCell;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8ActorSDK9AAEditRow")
@interface AAEditRow : AAManagedRow <UITextFieldDelegate>
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic) UIReturnKeyType returnKeyType;
@property (nonatomic) UITextAutocorrectionType autocorrectionType;
@property (nonatomic) UITextAutocapitalizationType autocapitalizationType;
@property (nonatomic, copy) void (^ _Nullable returnAction)(void);
- (void)textFieldDidChange:(UITextField * _Nonnull)textField;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK20AAEditTextController")
@interface AAEditTextController : AAViewController
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)doSave;
- (void)doCancel;
- (void)viewDidLayoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK27AAGroupCreateViewController")
@interface AAGroupCreateViewController : AAViewController <UITextFieldDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)photoTap;
- (void)viewWillAppear:(BOOL)animated;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
- (void)doNext;
@end


SWIFT_CLASS("_TtC8ActorSDK17AAGroupMemberCell")
@interface AAGroupMemberCell : AATableViewCell
@property (nonatomic, strong) UILabel * _Nonnull nameLabel;
@property (nonatomic, strong) UILabel * _Nonnull onlineLabel;
@property (nonatomic, strong) AAAvatarView * _Nonnull avatarView;
@property (nonatomic, strong) UILabel * _Nonnull adminLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setUsername:(NSString * _Nonnull)username;
- (void)bind:(ACUserVM * _Nonnull)user isAdmin:(BOOL)isAdmin;
- (void)prepareForReuse;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK21AAGroupViewController")
@interface AAGroupViewController : AAContentTableController
@property (nonatomic, strong) AAAvatarRow * _Null_unspecified headerRow;
- (nonnull instancetype)initWithGid:(NSInteger)gid OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
@end


SWIFT_CLASS("_TtC8ActorSDK12AAHeaderCell")
@interface AAHeaderCell : AATableViewCell
@property (nonatomic, strong) UILabel * _Nonnull titleView;
@property (nonatomic, strong) UIImageView * _Nonnull iconView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK11AAHeaderRow")
@interface AAHeaderRow : AAManagedRow
@property (nonatomic) CGFloat height;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) UIImage * _Nullable icon;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK23AAImagePickerController")
@interface AAImagePickerController : UIImagePickerController
- (UIStatusBarStyle)preferredStatusBarStyle;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK26AAInviteLinkViewController")
@interface AAInviteLinkViewController : AAContentTableController
@property (nonatomic, copy) NSString * _Nullable currentUrl;
@property (nonatomic, strong) AACommonRow * _Null_unspecified urlRow;
- (nonnull instancetype)initWithGid:(NSInteger)gid OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
- (void)reloadLink;
@end

@class MKMapView;
@class CLLocationManager;
@class CLLocation;

SWIFT_CLASS("_TtC8ActorSDK26AALocationPickerController")
@interface AALocationPickerController : AAViewController <CLLocationManagerDelegate, MKMapViewDelegate>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)mapView:(MKMapView * _Nonnull)mapView regionWillChangeAnimated:(BOOL)animated;
- (void)mapView:(MKMapView * _Nonnull)mapView regionDidChangeAnimated:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
@end




SWIFT_CLASS("_TtC8ActorSDK13AAMapFastView")
@interface AAMapFastView : UIImageView
- (nonnull instancetype)initWithMapWidth:(CGFloat)mapWidth mapHeight:(CGFloat)mapHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK17AAMapPinPointView")
@interface AAMapPinPointView : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK22AANavigationController")
@interface AANavigationController : UINavigationController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (UIStatusBarStyle)preferredStatusBarStyle;
@end


SWIFT_CLASS("_TtC8ActorSDK27AANoSelectionViewController")
@interface AANoSelectionViewController : AAViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK24AAPhotoPreviewController")
@interface AAPhotoPreviewController : NYTPhotosViewController <NYTPhotosViewControllerDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillAppear:(BOOL)animated;
- (UIView * _Nullable)photosViewController:(NYTPhotosViewController * _Nonnull)photosViewController referenceViewForPhoto:(id <NYTPhoto> _Nonnull)photo;
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8ActorSDK14AAProgressView")
@interface AAProgressView : UIView
- (nonnull instancetype)initWithSize:(CGSize)size OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setButtonType:(FlatButtonType)type animated:(BOOL)animated;
- (void)setProgress:(double)value;
- (void)hideProgress;
- (void)hideButton;
@end

@class ARPromiseResolver;

SWIFT_CLASS("_TtC8ActorSDK13AAPromiseFunc")
@interface AAPromiseFunc : NSObject <ARPromiseFunc>
- (void)exec:(ARPromiseResolver * _Nonnull)resolver;
@end

@class ACDialog;

SWIFT_CLASS("_TtC8ActorSDK22AARecentViewController")
@interface AARecentViewController : AADialogsListContentController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)setEditing:(BOOL)editing animated:(BOOL)animated;
- (void)compose;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (BOOL)recentsDidTap:(AADialogsListContentController * _Nonnull)controller dialog:(ACDialog * _Nonnull)dialog;
- (void)searchDidTap:(AADialogsListContentController * _Nonnull)controller entity:(ACSearchEntity * _Nonnull)entity;
@end


SWIFT_CLASS("_TtC8ActorSDK25AARootSplitViewController")
@interface AARootSplitViewController : UISplitViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration;
- (UIStatusBarStyle)preferredStatusBarStyle;
@end

@class MFMessageComposeViewController;
@class UIAlertView;

SWIFT_CLASS("_TtC8ActorSDK23AARootTabViewController")
@interface AARootTabViewController : UITabBarController <MFMessageComposeViewControllerDelegate, UIAlertViewDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)showAppIsSyncingPlaceholder;
- (void)showAppIsEmptyPlaceholder;
- (void)hidePlaceholders;
- (void)showSmsInvitation:(NSString * _Nullable)phone;
- (void)showSmsInvitation;
- (void)doAddContact;
- (void)viewWillLayoutSubviews;
- (BOOL)shouldAutorotate;
- (UIInterfaceOrientationMask)supportedInterfaceOrientations;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (void)messageComposeViewController:(MFMessageComposeViewController * _Nonnull)controller didFinishWithResult:(MessageComposeResult)result;
- (void)alertView:(UIAlertView * _Nonnull)alertView clickedButtonAtIndex:(NSInteger)buttonIndex;
@end


SWIFT_CLASS("_TtC8ActorSDK28AASettingsLastSeenController")
@interface AASettingsLastSeenController : AATableViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForFooterInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayFooterView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC8ActorSDK37AASettingsNotificationsViewController")
@interface AASettingsNotificationsViewController : AATableViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForFooterInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayFooterView:(UIView * _Nonnull)view forSection:(NSInteger)section;
@end


SWIFT_CLASS("_TtC8ActorSDK31AASettingsPrivacyViewController")
@interface AASettingsPrivacyViewController : AAContentTableController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
@end


SWIFT_CLASS("_TtC8ActorSDK28AASettingsSessionsController")
@interface AASettingsSessionsController : AAContentTableController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
@end


SWIFT_CLASS("_TtC8ActorSDK24AASettingsViewController")
@interface AASettingsViewController : AAContentTableController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
@end


SWIFT_CLASS("_TtC8ActorSDK20AASettingsWallpapper")
@interface AASettingsWallpapper : AACollectionViewController <UICollectionViewDelegateFlowLayout>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section;
@end


SWIFT_CLASS("_TtC8ActorSDK13AAStickerView")
@interface AAStickerView : UIView <YYAsyncLayerDelegate, ACFileEventCallback>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)onDownloadedWithLong:(jlong)fileId;
- (void)setSticker:(ACFileReference * _Nullable)file;
+ (Class _Nonnull)layerClass;
- (YYAsyncLayerDisplayTask * _Nonnull)newAsyncDisplayTask;
@end


SWIFT_CLASS("_TtC8ActorSDK18AAStickersKeyboard")
@interface AAStickersKeyboard : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class ACSticker;

SWIFT_CLASS("_TtC8ActorSDK18AAStickersViewCell")
@interface AAStickersViewCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)bind:(ACSticker * _Null_unspecified)sticker clearPrev:(BOOL)clearPrev;
- (void)layoutSubviews;
- (void)prepareForReuse;
@end




SWIFT_CLASS("_TtC8ActorSDK17AATableViewHeader")
@interface AATableViewHeader : UIView
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK10AATextCell")
@interface AATextCell : AATableViewCell
@property (nonatomic, strong) UILabel * _Nonnull titleLabel;
@property (nonatomic, strong) UILabel * _Nonnull contentLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setContent:(NSString * _Nullable)title content:(NSString * _Nullable)content isAction:(BOOL)isAction;
- (void)layoutSubviews;
+ (CGFloat)measure:(NSString * _Nonnull)text width:(CGFloat)width enableNavigation:(BOOL)enableNavigation;
@end


SWIFT_CLASS("_TtC8ActorSDK9AATextRow")
@interface AATextRow : AAManagedRow
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) BOOL isAction;
@property (nonatomic) BOOL navigate;
@property (nonatomic, copy) void (^ _Nullable bindAction)(AATextRow * _Nonnull);
- (void)reload;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ActorSDK15AAThumbnailView")
@interface AAThumbnailView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

- (void)open;

/// collection view delegate
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;

- (void)reloadView;
- (void)collectionViewSetup;
- (UIImage * _Nonnull)imageByCroppingImage:(UIImage * _Nonnull)image toSize:(CGSize)toSize;
- (void)addSelectedModel:(PHAsset * _Nonnull)model;
- (void)removeSelectedModel:(PHAsset * _Nonnull)model;
- (void)getSelectedAsImages:(void (^ _Nonnull)(NSArray<UIImage *> * _Nonnull))completion;
- (void)dismiss;
@end


SWIFT_CLASS("_TtC8ActorSDK12AATitledCell")
@interface AATitledCell : AATableViewCell
@property (nonatomic, readonly, strong) UILabel * _Nonnull titleLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull contentLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setContent:(NSString * _Nonnull)title content:(NSString * _Nonnull)content isAction:(BOOL)isAction;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK11AATitledRow")
@interface AATitledRow : AAManagedRow
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic) BOOL isAction;
@property (nonatomic) UITableViewCellAccessoryType accessoryType;
@property (nonatomic, copy) void (^ _Nullable bindAction)(AATitledRow * _Nonnull);
- (void)bindCell:(AATitledCell * _Nonnull)res;
- (void)reload;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC8ActorSDK16AAWallpapersCell")
@interface AAWallpapersCell : AATableViewCell
@property (nonatomic, copy) void (^ _Nullable wallpapperDidTap)(NSString * _Nonnull);
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK29AAWallpapperPreviewController")
@interface AAWallpapperPreviewController : AAViewController
- (nonnull instancetype)initWithImageName:(NSString * _Nonnull)imageName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSelectedImage:(UIImage * _Nonnull)selectedImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
@end


SWIFT_CLASS("_TtC8ActorSDK24AAWallpapperSettingsCell")
@interface AAWallpapperSettingsCell : AATableViewCell
@property (nonatomic, copy) void (^ _Nullable wallpapperDidTap)(NSString * _Nonnull);
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class ACWebActionDescriptor;
@class UIWebView;
@class NSURLRequest;

SWIFT_CLASS("_TtC8ActorSDK21AAWebActionController")
@interface AAWebActionController : AAViewController <UIWebViewDelegate>
- (nonnull instancetype)initWithDesc:(ACWebActionDescriptor * _Nonnull)desc OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (BOOL)webView:(UIWebView * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(UIWebViewNavigationType)navigationType;
@end


SWIFT_CLASS("_TtC8ActorSDK19AAWelcomeController")
@interface AAWelcomeController : AAViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLayoutSubviews;
- (void)signupAction;
- (void)signInAction;
- (void)viewWillAppear:(BOOL)animated;
@end


@interface ACCocoaMessenger (SWIFT_EXTENSION(ActorSDK))
- (void)sendUIImage:(UIImage * _Nonnull)image peer:(ACPeer * _Nonnull)peer;
- (void)sendVideo:(NSURL * _Nonnull)url peer:(ACPeer * _Nonnull)peer;
- (void)changeOwnAvatar:(UIImage * _Nonnull)image;
- (void)changeGroupAvatar:(jint)gid image:(UIImage * _Nonnull)image;
- (void)requestFileState:(jlong)fileId notDownloaded:(void (^ _Nullable)(void))notDownloaded onDownloading:(void (^ _Nullable)(double))onDownloading onDownloaded:(void (^ _Nullable)(NSString * _Nonnull))onDownloaded;
- (void)requestFileState:(jlong)fileId onDownloaded:(void (^ _Nullable)(NSString * _Nonnull))onDownloaded;
@end


@interface ACMessage (SWIFT_EXTENSION(ActorSDK))
@property (nonatomic, readonly) BOOL isOut;
@end


@interface ACPeer (SWIFT_EXTENSION(ActorSDK))
@property (nonatomic, readonly) BOOL isGroup;
@property (nonatomic, readonly) BOOL isPrivate;
@end


@interface ARListEngineRecord (SWIFT_EXTENSION(ActorSDK))
- (id _Nonnull)dbQuery;
@end


@interface ARPromise (SWIFT_EXTENSION(ActorSDK))
@end


@interface ARPromise (SWIFT_EXTENSION(ActorSDK))
@end


@interface AVAsset (SWIFT_EXTENSION(ActorSDK))
@end



/// Default empty implementation of SDK Delegate
SWIFT_CLASS("_TtC8ActorSDK23ActorSDKDelegateDefault")
@interface ActorSDKDelegateDefault : NSObject
- (UIViewController * _Nullable)actorControllerForAuthStart;
- (UIViewController * _Nullable)actorControllerForStart;
- (AAViewController * _Nullable)actorControllerForUser:(NSInteger)uid;
- (AAViewController * _Nullable)actorControllerForGroup:(NSInteger)gid;
- (UIViewController * _Nullable)actorControllerForConversation:(ACPeer * _Nonnull)peer;
- (AAViewController * _Nullable)actorControllerForContacts;
- (AAViewController * _Nullable)actorControllerForDialogs;
- (AAViewController * _Nullable)actorControllerForSettings;
- (UIViewController * _Nullable)actorControllerAfterLogIn;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIApplication;
@class UIUserNotificationSettings;
@class NSData;

SWIFT_CLASS("_TtC8ActorSDK24ActorApplicationDelegate")
@interface ActorApplicationDelegate : ActorSDKDelegateDefault <UIApplicationDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)applicationDidFinishLaunching:(UIApplication * _Nonnull)application;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary * _Nullable)launchOptions;
- (void)applicationDidBecomeActive:(UIApplication * _Nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (void)applicationWillResignActive:(UIApplication * _Nonnull)application;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo;
- (void)application:(UIApplication * _Nonnull)application didRegisterUserNotificationSettings:(UIUserNotificationSettings * _Nonnull)notificationSettings;
- (void)application:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (void)application:(UIApplication * _Nonnull)application performFetchWithCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation;
- (BOOL)application:(UIApplication * _Nonnull)application handleOpenURL:(NSURL * _Nonnull)url;
@end

@class UIWindow;
@class PKPushRegistry;
@class PKPushCredentials;
@class PKPushPayload;

SWIFT_CLASS("_TtC8ActorSDK8ActorSDK")
@interface ActorSDK : NSObject <PKPushRegistryDelegate>
+ (ActorSDK * _Nonnull)sharedActor;

/// Main Messenger object
@property (nonatomic, strong) ACCocoaMessenger * _Null_unspecified messenger;

/// Server Endpoints
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull endpoints;

/// Trusted Server Keys
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull trustedKeys;

/// API ID
@property (nonatomic) NSInteger apiId;

/// API Key
@property (nonatomic, copy) NSString * _Nonnull apiKey;

/// Enable phone book import
@property (nonatomic) BOOL enablePhoneBookImport;

/// Invitation URL for apps
@property (nonatomic, copy) NSString * _Nonnull inviteUrl;

/// Privacy Policy URL
@property (nonatomic, copy) NSString * _Nullable privacyPolicyUrl;

/// Privacy Policy Text
@property (nonatomic, copy) NSString * _Nullable privacyPolicyText;

/// Terms of Service URL
@property (nonatomic, copy) NSString * _Nullable termsOfServiceUrl;

/// Terms of Service Text
@property (nonatomic, copy) NSString * _Nullable termsOfServiceText;

/// App name
@property (nonatomic, copy) NSString * _Nonnull appName;

/// Support email
@property (nonatomic, copy) NSString * _Nullable supportEmail;

/// Support email
@property (nonatomic, copy) NSString * _Nullable supportActivationEmail;

/// Support account
@property (nonatomic, copy) NSString * _Nullable supportAccount;

/// Support home page
@property (nonatomic, copy) NSString * _Nullable supportHomepage;

/// Support account
@property (nonatomic, copy) NSString * _Nullable supportTwitter;

/// Invite url scheme
@property (nonatomic, copy) NSString * _Nullable inviteUrlScheme;

/// Web Invite Domain host
@property (nonatomic, copy) NSString * _Nullable inviteUrlHost;

/// Enable voice calls feature
@property (nonatomic) BOOL enableCalls;

/// Enable experimental features
@property (nonatomic) BOOL enableExperimentalFeatures;

/// Is User online
@property (nonatomic, readonly) BOOL isUserOnline;

/// Disable this if you want manually handle online states
@property (nonatomic) BOOL automaticOnlineHandling;

/// Is Actor Started
@property (nonatomic, readonly) BOOL isStarted;
@property (nonatomic, readonly, strong) UIWindow * _Null_unspecified bindedToWindow;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)createActor;
- (void)pushRegistry:(PKPushRegistry * _Null_unspecified)registry didUpdatePushCredentials:(PKPushCredentials * _Null_unspecified)credentials forType:(NSString * _Null_unspecified)type;
- (void)pushRegistry:(PKPushRegistry * _Null_unspecified)registry didInvalidatePushTokenForType:(NSString * _Null_unspecified)type;
- (void)pushRegistry:(PKPushRegistry * _Null_unspecified)registry didReceiveIncomingPushWithPayload:(PKPushPayload * _Null_unspecified)payload forType:(NSString * _Null_unspecified)type;
- (void)presentMessengerInWindow:(UIWindow * _Nonnull)window;
- (void)presentMessengerInNewWindow;
- (NSString * _Nonnull)fullFilePathForDescriptor:(NSString * _Nonnull)descriptor;
- (void)didBecameOnline;
- (void)didBecameOffline;
- (void)applicationDidFinishLaunching:(UIApplication * _Nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * _Nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (void)applicationWillResignActive:(UIApplication * _Nonnull)application;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo;
- (void)application:(UIApplication * _Nonnull)application didRegisterUserNotificationSettings:(UIUserNotificationSettings * _Nonnull)notificationSettings;
- (void)application:(UIApplication * _Nonnull)application performFetchWithCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (BOOL)application:(UIApplication * _Nonnull)application handleOpenURL:(NSURL * _Nonnull)url;
@end


@class UIFont;
@class NSParagraphStyle;
@class NSShadow;
@class NSAttributedString;

SWIFT_CLASS("_TtC8ActorSDK15AttributedLabel")
@interface AttributedLabel : UIView

/// default is 0.
@property (nonatomic) NSInteger numberOfLines;

/// lineFragmentPadding of NSTextContainer. default is 0.
@property (nonatomic) CGFloat padding;

/// default is system font 17 plain.
@property (nonatomic, strong) UIFont * _Nonnull font;

/// default is ByTruncatingTail.
@property (nonatomic) NSLineBreakMode lineBreakMode;

/// default is nil (text draws black).
@property (nonatomic, strong) UIColor * _Nullable textColor;

/// default is nil.
@property (nonatomic, strong) NSParagraphStyle * _Nullable paragraphStyle;

/// default is nil.
@property (nonatomic, strong) NSShadow * _Nullable shadow;

/// default is nil.
@property (nonatomic, strong) NSAttributedString * _Nullable attributedText;

/// default is nil.
@property (nonatomic, copy) NSString * _Nullable text;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setNeedsDisplay;
- (void)drawRect:(CGRect)rect;
- (CGSize)sizeThatFits:(CGSize)size;
- (void)sizeToFit;
@end

@class AAAudioRecorder;
@class UIDocumentMenuViewController;
@class UIDocumentPickerViewController;
@class ABPeoplePickerNavigationController;

SWIFT_CLASS("_TtC8ActorSDK26ConversationViewController")
@interface ConversationViewController : AAConversationContentController <UIDocumentMenuDelegate, UIDocumentPickerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, ABPeoplePickerNavigationControllerDelegate, AAAudioRecorderDelegate>
@property (nonatomic, strong) AAAudioRecorder * _Null_unspecified audioRecorder;

/// /////////////////////////////////////////////////////////
- (nonnull instancetype)initWithPeer:(ACPeer * _Nonnull)peer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Null_unspecified)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;

/// /////////////////////////////////////////////////////////
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;

/// /////////////////////////////////////////////////////////
- (void)textDidUpdate:(BOOL)animated;

/// /////////////////////////////////////////////////////////
- (void)didPressRightButton:(id _Null_unspecified)sender;
- (void)didPressLeftButton:(id _Null_unspecified)sender;

/// /////////////////////////////////////////////////////////
- (void)didChangeAutoCompletionPrefix:(NSString * _Null_unspecified)prefix andWord:(NSString * _Null_unspecified)word;

/// /////////////////////////////////////////////////////////
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)heightForAutoCompletionView;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;

/// /////////////////////////////////////////////////////////
- (void)actionSheetPickCamera;
- (void)actionSheetPickGallery;
- (void)actionSheetPickContact;
- (void)actionSheetPickLocation;
- (void)actionSheetPickedImages:(NSArray<UIImage *> * _Nonnull)images;
- (void)actionSheetPickDocument;
- (void)actionSheetUnblockContact;

/// /////////////////////////////////////////////////////////
- (void)documentMenu:(UIDocumentMenuViewController * _Nonnull)documentMenu didPickDocumentPicker:(UIDocumentPickerViewController * _Nonnull)documentPicker;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentAtURL:(NSURL * _Nonnull)url;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingImage:(UIImage * _Nonnull)image editingInfo:(NSDictionary<NSString *, id> * _Nullable)editingInfo;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *, id> * _Nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;

/// /////////////////////////////////////////////////////////
- (void)locationPickerDidCancelled:(AALocationPickerController * _Nonnull)controller;
- (void)locationPickerDidPicked:(AALocationPickerController * _Nonnull)controller latitude:(double)latitude longitude:(double)longitude;

/// /////////////////////////////////////////////////////////
- (void)peoplePickerNavigationController:(ABPeoplePickerNavigationController * _Nonnull)peoplePicker didSelectPerson:(ABRecordRef _Nonnull)person;
- (void)audioRecorderDidStartRecording;
- (void)stickerDidSelected:(AAStickersKeyboard * _Nonnull)keyboard sticker:(ACSticker * _Nonnull)sticker;
@end


@interface FMDatabase (SWIFT_EXTENSION(ActorSDK))
@end

@class CLTokenInputView;
@class CLToken;

SWIFT_CLASS("_TtC8ActorSDK22GroupMembersController")
@interface GroupMembersController : AAContactsListContentController <CLTokenInputViewDelegate>
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title image:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tableDidLoad;
- (BOOL)contactDidTap:(AAContactsListContentController * _Nonnull)controller contact:(ACContact * _Nonnull)contact;
- (void)doNext;
- (void)tokenInputView:(CLTokenInputView * _Nonnull)view didChangeText:(NSString * _Nullable)text;
- (void)tokenInputView:(CLTokenInputView * _Nonnull)view didChangeHeightTo:(CGFloat)height;
- (void)tokenInputView:(CLTokenInputView * _Nonnull)view didRemoveToken:(CLToken * _Nonnull)token;
- (void)viewDidLayoutSubviews;
@end


@interface IOSObjectArray (SWIFT_EXTENSION(ActorSDK))
@end


@interface JavaLangLong (SWIFT_EXTENSION(ActorSDK))
@end


@interface JavaUtilAbstractCollection (SWIFT_EXTENSION(ActorSDK))
@end


@interface NSAttributedString (SWIFT_EXTENSION(ActorSDK))
- (NSAttributedString * _Nonnull)append:(NSAttributedString * _Nonnull)text;
- (NSAttributedString * _Nonnull)append:(NSString * _Nonnull)text font:(UIFont * _Nonnull)font;
- (nonnull instancetype)initWithString:(NSString * _Nonnull)string font:(UIFont * _Nonnull)font;
@end


@interface NSBundle (SWIFT_EXTENSION(ActorSDK))
+ (NSBundle * _Nonnull)framework;
@end


@interface NSData (SWIFT_EXTENSION(ActorSDK))
@end


@interface NSData (SWIFT_EXTENSION(ActorSDK))
@end


@interface NSData (SWIFT_EXTENSION(ActorSDK))
@end


@interface NSDateFormatter (SWIFT_EXTENSION(ActorSDK))
@end


@interface NSMutableAttributedString (SWIFT_EXTENSION(ActorSDK))
- (void)appendFont:(UIFont * _Nonnull)font;
- (void)appendColor:(UIColor * _Nonnull)color;
@end

@class RTCICECandidate;
@class RTCMediaStream;

@interface RTCPeerConnection (SWIFT_EXTENSION(ActorSDK))
@property (nonatomic, copy) void (^ _Nullable onCandidateReceived)(RTCICECandidate * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onStreamAdded)(RTCMediaStream * _Nonnull);
@end

@class NSNotificationCenter;

SWIFT_CLASS("_TtC8ActorSDK12Reachability")
@interface Reachability : NSObject
@property (nonatomic, copy) void (^ _Nullable whenReachable)(Reachability * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable whenUnreachable)(Reachability * _Nonnull);
@property (nonatomic) BOOL reachableOnWWAN;
@property (nonatomic, strong) NSNotificationCenter * _Nonnull notificationCenter;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentReachabilityString;
- (nonnull instancetype)initWithReachabilityRef:(SCNetworkReachabilityRef _Nonnull)reachabilityRef OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithHostname:(NSString * _Nonnull)hostname error:(NSError * _Nullable * _Null_unspecified)error;
+ (Reachability * _Nullable)reachabilityForInternetConnectionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
+ (Reachability * _Nullable)reachabilityForLocalWiFiAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)startNotifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (void)stopNotifier;
- (BOOL)isReachable;
- (BOOL)isReachableViaWWAN;
- (BOOL)isReachableViaWiFi;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class NSLayoutManager;

SWIFT_CLASS("_TtC8ActorSDK8TapLabel")
@interface TapLabel : UILabel <NSLayoutManagerDelegate>
+ (NSString * _Nonnull)LinkContentName;
+ (NSString * _Nonnull)SelectedForegroudColorName;
@property (nonatomic) NSLineBreakMode lineBreakMode;
@property (nonatomic) NSInteger numberOfLines;
@property (nonatomic, strong) NSAttributedString * _Null_unspecified attributedText;
@property (nonatomic) CGRect frame;
@property (nonatomic) CGRect bounds;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines;
- (void)drawTextInRect:(CGRect)rect;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nullable)touches withEvent:(UIEvent * _Nullable)event;
- (BOOL)layoutManager:(NSLayoutManager * _Nonnull)layoutManager shouldBreakLineByWordBeforeCharacterAtIndex:(NSInteger)charIndex;
@end


@interface UIApplication (SWIFT_EXTENSION(ActorSDK))
@end


@interface UICollectionView (SWIFT_EXTENSION(ActorSDK))
@end


@interface UIColor (SWIFT_EXTENSION(ActorSDK))
- (nonnull instancetype)initWithRgb:(NSUInteger)rgb;
- (nonnull instancetype)initWithRgb:(NSUInteger)rgb alpha:(double)alpha;
- (nonnull instancetype)initWithRed:(NSUInteger)red green:(NSUInteger)green blue:(NSUInteger)blue;
+ (UIColor * _Nonnull)alphaBlack:(double)alpha;
+ (UIColor * _Nonnull)alphaWhite:(double)alpha;
- (UIColor * _Nonnull)alpha:(double)alpha;
- (UIColor * _Nonnull)forTransparentBar;
- (UIColor * _Nonnull)fromTransparentBar;
@end


@interface UIFont (SWIFT_EXTENSION(ActorSDK))
+ (UIFont * _Nonnull)thinSystemFontOfSize:(CGFloat)size;
+ (UIFont * _Nonnull)lightSystemFontOfSize:(CGFloat)size;
+ (UIFont * _Nonnull)mediumSystemFontOfSize:(CGFloat)size;
+ (UIFont * _Nonnull)textFontOfSize:(CGFloat)size;
+ (UIFont * _Nonnull)italicTextFontOfSize:(CGFloat)size;
+ (UIFont * _Nonnull)boldTextFontOfSize:(CGFloat)size;
@end


@interface UIImage (SWIFT_EXTENSION(ActorSDK))
+ (UIImage * _Nullable)bundled:(NSString * _Nonnull)named;
@end


@interface UIImage (SWIFT_EXTENSION(ActorSDK))
- (UIImage * _Nonnull)imageRotatedByDegrees:(CGFloat)degrees flip:(BOOL)flip;
@end


@interface UIImage (SWIFT_EXTENSION(ActorSDK))
- (UIImage * _Nullable)applyLightEffect;
- (UIImage * _Nullable)applyExtraLightEffect;
- (UIImage * _Nullable)applyDarkEffect;
- (UIImage * _Nullable)applyTintEffectWithColor:(UIColor * _Nonnull)tintColor;
- (UIImage * _Nullable)applyBlur:(CGFloat)blurRadius;
- (UIImage * _Nullable)applyBlurWithRadius:(CGFloat)blurRadius tintColor:(UIColor * _Nullable)tintColor saturationDeltaFactor:(CGFloat)saturationDeltaFactor maskImage:(UIImage * _Nullable)maskImage;
@end


@interface UIImage (SWIFT_EXTENSION(ActorSDK))
+ (UIImage * _Nonnull)tinted:(NSString * _Nonnull)named color:(UIColor * _Nonnull)color;
+ (UIImage * _Nonnull)templated:(NSString * _Nonnull)named;
- (UIImage * _Nonnull)tintImage:(UIColor * _Nonnull)color;
- (UIImage * _Nonnull)tintBgImage:(UIColor * _Nonnull)color;
- (UIImage * _Nonnull)roundImage:(NSInteger)newSize;
- (UIImage * _Nonnull)roundCorners:(CGFloat)w h:(CGFloat)h roundSize:(CGFloat)roundSize;
- (UIImage * _Nonnull)resizeSquare:(CGFloat)maxW maxH:(CGFloat)maxH;
- (UIImage * _Nonnull)resizeOptimize:(NSInteger)maxPixels;
- (UIImage * _Nonnull)resize:(CGFloat)w h:(CGFloat)h;
- (UIImage * _Nonnull)aa_imageWithColor:(UIColor * _Nonnull)color1;
@end


@interface UILabel (SWIFT_EXTENSION(ActorSDK))
@property (nonatomic, copy) NSString * _Nullable textLocalized;
@end


@interface UINavigationBar (SWIFT_EXTENSION(ActorSDK))
@end


@interface UITabBarItem (SWIFT_EXTENSION(ActorSDK))
@end


@interface UITableView (SWIFT_EXTENSION(ActorSDK))
- (UITableViewCell * _Nonnull)dequeueCell:(Class _Nonnull)cellClass indexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nullable)visibleCellForIndexPath:(NSIndexPath * _Nonnull)path;
@end


@interface UITapGestureRecognizer (SWIFT_EXTENSION(ActorSDK))
- (nonnull instancetype)initWithClosure:(void (^ _Nonnull)(void))closure;
@end


@interface UIView (SWIFT_EXTENSION(ActorSDK))
@property (nonatomic, copy) void (^ _Nullable viewDidTap)(void);
@end


@interface UIView (SWIFT_EXTENSION(ActorSDK))
- (void)hideView;
- (void)showView;
- (void)showViewAnimated;
- (void)hideViewAnimated;
- (void)centerIn:(CGRect)rect;
- (void)under:(CGRect)rect offset:(CGFloat)offset;
- (void)topIn:(CGRect)rect;
@end


@interface UIViewController (SWIFT_EXTENSION(ActorSDK))
- (void)navigateDetail:(UIViewController * _Nonnull)controller;
@end


@interface UIViewController (SWIFT_EXTENSION(ActorSDK))
- (void)confirmDestructive:(NSString * _Nonnull)message action:(NSString * _Nonnull)action yes:(void (^ _Nonnull)(void))yes;
@end


@interface UIViewController (SWIFT_EXTENSION(ActorSDK))
- (void)navigateNext:(UIViewController * _Nonnull)controller removeCurrent:(BOOL)removeCurrent;
- (void)navigateBack;
@end


@interface UIViewController (SWIFT_EXTENSION(ActorSDK))
@property (nonatomic, readonly) CGFloat navigationBarHeight;
@property (nonatomic, readonly) CGFloat statusBarHeight;
@end


@interface UIViewController (SWIFT_EXTENSION(ActorSDK))
- (void)alertUser:(NSString * _Nonnull)message;
- (void)confirmAlertUser:(NSString * _Nonnull)message action:(NSString * _Nonnull)action tapYes:(void (^ _Nonnull)(void))tapYes tapNo:(void (^ _Nullable)(void))tapNo;
- (void)confirmDangerSheetUser:(NSString * _Nonnull)action tapYes:(void (^ _Nonnull)(void))tapYes tapNo:(void (^ _Nullable)(void))tapNo;
- (void)showActionSheet:(NSString * _Nullable)title buttons:(NSArray<NSString *> * _Nonnull)buttons cancelButton:(NSString * _Nullable)cancelButton destructButton:(NSString * _Nullable)destructButton sourceView:(UIView * _Nonnull)sourceView sourceRect:(CGRect)sourceRect tapClosure:(void (^ _Nonnull)(NSInteger))tapClosure;
- (void)showActionSheet:(NSArray<NSString *> * _Nonnull)buttons cancelButton:(NSString * _Nullable)cancelButton destructButton:(NSString * _Nullable)destructButton sourceView:(UIView * _Nonnull)sourceView sourceRect:(CGRect)sourceRect tapClosure:(void (^ _Nonnull)(NSInteger))tapClosure;
@end

@protocol ACCommand;

@interface UIViewController (SWIFT_EXTENSION(ActorSDK))
- (void)execute:(id <ACCommand> _Nonnull)command;
- (void)executePromise:(ARPromise * _Nonnull)promise;
@end

#pragma clang diagnostic pop
